--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.4.270.0
-- Product Home Page: http://devart.com/dbforge/sql/studio
-- Script date 11/09/2017 11:49:10
-- Source server version: 12.00.2269
-- Source connection string: Data Source=elissia-sql,1433;Integrated Security=False;User ID=elissia-flywaydb
-- Target server version: 12.00.4213
-- Target connection string: Data Source=elissia-sql,1435;Integrated Security=False;User ID=elissia-flywaydb
-- Run this script against $[CLIENT_ENV]_COMMON to synchronize it with $[CLIENT_ENV]_COMMON
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

USE $[CLIENT_ENV]_COMMON
GO
IF DB_NAME() <> N'$[CLIENT_ENV]_COMMON' SET NOEXEC ON
GO


--
-- Set transaction isolation level
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

--
-- Start Transaction
--
BEGIN TRANSACTION


INSERT [CONTROLS] ([CTL_ID], [VALIDATION], [EVENT], [CODE], [WINDOW0], [NAME0], [LANG_CODE], [STATUS], [NUMBER_VALUE], [DATE_VALUE], [DISPLAY_VALUE], [ALPHA_VALUE], [CODE_VALUE], [COMPANY], [DATA_TYPE], [SUB_DATA_TYPE], [CREATED_BY], [CREATED_DATE], [CREATED_TIME], [CREATED_PROCESS], [MODIFY_BY], [MODIFY_DATE], [MODIFY_TIME], [MODIFY_PROCESS]) VALUES (N'SYSTEM_DATE', N' ', CAST(0 AS Decimal(6, 0)), N'SYSTEM_DATE', N' ', N'System Date', N'SYSTEM_DATE', CAST(1 AS Decimal(1, 0)), CAST(0 AS Decimal(15, 0)), CAST(N'2015-08-16 00:00:00.0000000' AS DateTime2), N'2014-02-17T00:00:00', N' ', N'D', CAST(0 AS Decimal(1, 0)), CAST(1 AS Decimal(5, 0)), CAST(0 AS Decimal(5, 0)), N' ', CAST(N'2011-11-04 10:58:05.0000000' AS DateTime2), CAST(N'2011-11-04 10:58:05.0000000' AS DateTime2), N' ', N'AAAAG', CAST(N'2014-02-17 00:00:00.0000000' AS DateTime2), CAST(N'1970-01-01 08:16:45.0000000' AS DateTime2), N'UC')
GO


--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO
