INSERT INTO ${schemaCommon}.[dbo].[USERS]
      ([USR_ID]
      ,[PASSWORD]
      ,[NAME0]
      ,[USER_GROUP]
      ,[STATUS]
      ,[FORCE_PASSWORD_CHANGE]
      ,[MULTIPLE_LOGINS]
      ,[DATE_PASSWORD_CHANGED]
      ,[EMAIL_EXTN]
      ,[FAX_EXTN]
      ,[PRINTING]
      ,[TERMINAL_ID]
      ,[LANGUAGE0]
      ,[TEL_EXTN]
      ,[TITLE]
      ,[CREATED_PROCESS]
      ,[MODIFY_PROCESS]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[CREATED_TIME]
      ,[MODIFY_BY]
      ,[MODIFY_DATE]
      ,[MODIFY_TIME]
      ,[LAST_LOGIN_DATE]
      ,[LAST_LOGIN_TIME]
      ,[LAST_LOGIN_SDATE]
      ,[PRINTER]
      ,[FK_AGENTSAGT_ID]
      ,[FK_CLIENTSCLI_ID]
      ,[LOGIN_ID]
      ,[USER_TYPE]
      ,[LOGIN_ATTEMPTS]
      ,[SALT_VALUE]
      ,[DISP_CATEGORY]
      ,[FK_BRANCHESBCH_ID]
      ,[LAST_LOGIN_IP]
      ,[TIME_PASSWORD_CHANGED]
      ,[USER_PASSWORD_CHANGED_BY]
      ,[LOCK_TIMESTAMP]
      ,[THEME]
      ,[USER_TOKEN]
      ,[USER_TOKEN_EXPIRY])
     select 
		CONCAT('U',max(CAST((SUBSTRING(usr_id,2,8)) as INT))+1) as id, 
		'password', 'Technical batch user', 0,1,0,null, GETDATE(), 'batch-svc@wealins.com', null, null, null,1, null,1,'JDBC',null, 'AAAAA', GETDATE(), GETDATE(), 'AAAAA',GETDATE(), GETDATE(),
        null, null, null, null, null, null, 'batch-svc', 1, null, 'bb0vhYpcIVk=', 0,null, null, GETDATE(), 'AAAAA', null, 'fisa', null,null   
	 from ${schemaCommon}.[dbo].[USERS] where usr_id like 'U%';