--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.4.270.0
-- Product Home Page: http://devart.com/dbforge/sql/studio
-- Script date 14/09/2017 16:53:33
-- Source server version: 12.00.2269
-- Source connection string: Data Source=elissia-sql,1433;Integrated Security=False;User ID=elissia-flywaydb
-- Target server version: 12.00.4213
-- Target connection string: Data Source=elissia-sql,1435;Integrated Security=False;User ID=elissia-flywaydb
-- Run this script against $[CLIENT_ENV]_COMMON to synchronize it with $[CLIENT_ENV]_COMMON
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

USE $[CLIENT_ENV]_COMMON
GO
IF DB_NAME() <> N'$[CLIENT_ENV]_COMMON' SET NOEXEC ON
GO


--
-- Set transaction isolation level
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

--
-- Start Transaction
--
BEGIN TRANSACTION

--
-- Dropping constraints from dbo.USER_PERMISSIONS
--
ALTER TABLE dbo.USER_PERMISSIONS
  DROP CONSTRAINT FK_PROCESSESPRS_ID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table dbo.PROCESSES
--
INSERT dbo.PROCESSES(PRS_ID, FIN_LIMIT_DISABLE, CREATE_DISABLE, AMEND_DISABLE, CREATED_PROCESS, STATUS, CREATED_BY, CREATED_DATE, CREATED_TIME, NAME0, TYPE0, DESCRIPTION, MODULE) VALUES (N'XVIVR', N'X', N'X', N'X', N'LISS', 1, N'SQL', '2017-08-31 17:49:05.0000000', '2017-08-31 17:49:05.0000000', N'Validate Imported Validation Rule', 2, NULL, 5)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for dbo.USER_PERMISSIONS
--
ALTER TABLE dbo.USER_PERMISSIONS WITH NOCHECK
  ADD CONSTRAINT FK_PROCESSESPRS_ID FOREIGN KEY (FK_PROCESSESPRS_ID) REFERENCES dbo.PROCESSES(PRS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END


--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO
