--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.1.178.0
-- Product Home Page: http://www.devart.com/dbforge/sql/studio
-- Script date 27/08/2017 08:45:17
-- Source server version: 12.00.2569
-- Source connection string: Data Source=localhost,1433;Integrated Security=False;User ID=elissia-flywaydb
-- Target server version: 12.00.2569
-- Target connection string: Data Source=localhost,1435;Integrated Security=False;User ID=elissia-flywaydb
-- Run this script against $[CLIENT_ENV]_COMMON to synchronize it with $[CLIENT_ENV]_COMMON
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

USE $[CLIENT_ENV]_COMMON
GO
IF DB_NAME() <> N'$[CLIENT_ENV]_COMMON' SET NOEXEC ON
GO


--
-- Start Transaction
--
BEGIN TRANSACTION

--
-- Deleting data from table dbo.SYSTEM_PROPERTIES
--
DELETE dbo.SYSTEM_PROPERTIES WHERE ID = 136690
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO