package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * AccountEntity generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNTS"

)
public class AccountEntity implements java.io.Serializable {

	@Transient
	public static final int ACCID_LENGTH = 12;

	private String accId;
	private String name;
	private Integer systemAcc;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Integer statutoryType;
	private Integer acctCentreTypes;
	private int type;
	private String view0;
	private Integer useage;
	private Integer ledger;
	private Set<AccountBalanceEntity> accountBalances = new HashSet<AccountBalanceEntity>(0);

	@Id
	@Column(name = "ACC_ID", unique = true, nullable = false, length = 12)
	public String getAccId() {
		return this.accId;
	}

	public void setAccId(String accId) {
		this.accId = accId;
	}

	@Column(name = "NAME", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SYSTEM_ACC")
	public Integer getSystemAcc() {
		return this.systemAcc;
	}

	public void setSystemAcc(Integer systemAcc) {
		this.systemAcc = systemAcc;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUTORY_TYPE")
	public Integer getStatutoryType() {
		return this.statutoryType;
	}

	public void setStatutoryType(Integer statutoryType) {
		this.statutoryType = statutoryType;
	}

	@Column(name = "ACCT_CENTRE_TYPES")
	public Integer getAcctCentreTypes() {
		return this.acctCentreTypes;
	}

	public void setAcctCentreTypes(Integer acctCentreTypes) {
		this.acctCentreTypes = acctCentreTypes;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "VIEW0", length = 20)
	public String getView0() {
		return this.view0;
	}

	public void setView0(String view0) {
		this.view0 = view0;
	}

	@Column(name = "USEAGE")
	public Integer getUseage() {
		return this.useage;
	}

	public void setUseage(Integer useage) {
		this.useage = useage;
	}

	@Column(name = "LEDGER")
	public Integer getLedger() {
		return this.ledger;
	}

	public void setLedger(Integer ledger) {
		this.ledger = ledger;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<AccountBalanceEntity> getAccountBalances() {
		return this.accountBalances;
	}

	public void setAccountBalances(Set<AccountBalanceEntity> accountBalances) {
		this.accountBalances = accountBalances;
	}

}
