package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AgentContractEntity generated by hbm2java
 */
@Entity
@Table(name="AGENT_CONTRACTS"
    
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler","createdProcess","modifyProcess","createdBy","createdDate","createdTime","modifyDate","modifyTime","modifyBy"})
public class AgentContractEntity  implements java.io.Serializable {


     private String acnId;
     private String description;
     private int status;
     private String createdBy;
     private Date createdDate;
     private Date createdTime;
     private String createdProcess;
     private String modifyBy;
     private Date modifyDate;
     private Date modifyTime;
     private String modifyProcess;
     @JsonIgnore
     private Set<AgentEntity> agents = new HashSet<AgentEntity>(0);

     @Id 
    @Column(name="ACN_ID", unique=true, nullable=false, length=6)
    public String getAcnId() {
        return this.acnId;
    }
    
    public void setAcnId(String acnId) {
        this.acnId = acnId;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="CREATED_BY", length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    
    @Column(name="CREATED_PROCESS", length=15)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }

    
    @Column(name="MODIFY_BY", length=5)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    
    @Column(name="MODIFY_PROCESS", length=15)
    public String getModifyProcess() {
        return this.modifyProcess;
    }
    
    public void setModifyProcess(String modifyProcess) {
        this.modifyProcess = modifyProcess;
    }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentContract")
	public Set<AgentEntity> getAgents() {
        return this.agents;
    }
    
	public void setAgents(Set<AgentEntity> agents) {
		this.agents = agents;
    }




}


