package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AgentHistoryDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "AGENT_HISTORY_DETAILS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class AgentHistoryDetailEntity implements java.io.Serializable {

	private long ahiId;
	@JsonIgnore
	private AgentEntity agent;
	private Date effectiveDate;
	private String name;
	private String number;
	private String branch;
	private int type;
	private Integer limitCode;
	private String limitCurrency;
	private BigDecimal limitAmount;
	private Integer lastStatementNo;
	private Integer paymentCode;
	private Integer paymentFrequency;
	private Integer paymentMethod;
	private String paymentCcy;
	private String contractNo;
	private String category;
	private String country;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String town;
	private String county;
	private String postcode;
	private String fax;
	private String telephone;
	private String email;
	private String channel;
	private String location;
	private String createdProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String servicingAgent;
	private Date dateOfTermination;
	private Integer terminationBasis;
	private String terminationReason;
	private String banding;

	@Id
	@Column(name = "AHI_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getAhiId() {
		return this.ahiId;
	}

	public void setAhiId(long ahiId) {
		this.ahiId = ahiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_AGENTSAGT_ID")
	public AgentEntity getAgent() {
		return this.agent;
	}

	public void setAgent(AgentEntity agent) {
		this.agent = agent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_DATE", length = 23)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "NAME", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NUMBER", nullable = false, length = 8)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "BRANCH", length = 10)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "LIMIT_CODE")
	public Integer getLimitCode() {
		return this.limitCode;
	}

	public void setLimitCode(Integer limitCode) {
		this.limitCode = limitCode;
	}

	@Column(name = "LIMIT_CURRENCY", length = 4)
	public String getLimitCurrency() {
		return this.limitCurrency;
	}

	public void setLimitCurrency(String limitCurrency) {
		this.limitCurrency = limitCurrency;
	}

	@Column(name = "LIMIT_AMOUNT", precision = 15)
	public BigDecimal getLimitAmount() {
		return this.limitAmount;
	}

	public void setLimitAmount(BigDecimal limitAmount) {
		this.limitAmount = limitAmount;
	}

	@Column(name = "LAST_STATEMENT_NO")
	public Integer getLastStatementNo() {
		return this.lastStatementNo;
	}

	public void setLastStatementNo(Integer lastStatementNo) {
		this.lastStatementNo = lastStatementNo;
	}

	@Column(name = "PAYMENT_CODE")
	public Integer getPaymentCode() {
		return this.paymentCode;
	}

	public void setPaymentCode(Integer paymentCode) {
		this.paymentCode = paymentCode;
	}

	@Column(name = "PAYMENT_FREQUENCY")
	public Integer getPaymentFrequency() {
		return this.paymentFrequency;
	}

	public void setPaymentFrequency(Integer paymentFrequency) {
		this.paymentFrequency = paymentFrequency;
	}

	@Column(name = "PAYMENT_METHOD")
	public Integer getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(Integer paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "PAYMENT_CCY", length = 4)
	public String getPaymentCcy() {
		return this.paymentCcy;
	}

	public void setPaymentCcy(String paymentCcy) {
		this.paymentCcy = paymentCcy;
	}

	@Column(name = "CONTRACT_NO", length = 6)
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Column(name = "CATEGORY", length = 4)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "COUNTRY", length = 3)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ADDRESS_LINE_1", length = 40)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE_2", length = 40)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "ADDRESS_LINE_3", length = 40)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "ADDRESS_LINE_4", length = 40)
	public String getAddressLine4() {
		return this.addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Column(name = "TOWN", length = 30)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Column(name = "COUNTY", length = 30)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "POSTCODE", length = 12)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "TELEPHONE", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "EMAIL", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CHANNEL", length = 8)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "LOCATION", length = 8)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "SERVICING_AGENT", length = 10)
	public String getServicingAgent() {
		return this.servicingAgent;
	}

	public void setServicingAgent(String servicingAgent) {
		this.servicingAgent = servicingAgent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_TERMINATION", length = 23)
	public Date getDateOfTermination() {
		return this.dateOfTermination;
	}

	public void setDateOfTermination(Date dateOfTermination) {
		this.dateOfTermination = dateOfTermination;
	}

	@Column(name = "TERMINATION_BASIS")
	public Integer getTerminationBasis() {
		return this.terminationBasis;
	}

	public void setTerminationBasis(Integer terminationBasis) {
		this.terminationBasis = terminationBasis;
	}

	@Column(name = "TERMINATION_REASON", length = 8)
	public String getTerminationReason() {
		return this.terminationReason;
	}

	public void setTerminationReason(String terminationReason) {
		this.terminationReason = terminationReason;
	}

	@Column(name = "BANDING", length = 8)
	public String getBanding() {
		return this.banding;
	}

	public void setBanding(String banding) {
		this.banding = banding;
	}

}
