package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lu.wealins.liability.services.core.utils.Historizable;

/**
 * AssetManagerStrategyEntity generated by hbm2java
 */
@Entity
@Table(name = "ASSET_MANAGER_STRATEGIES")
@Historizable(id = "amsId")
public class AssetManagerStrategyEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2190458312622724003L;

	private Long amsId;
	@JsonIgnore
	private AgentEntity agent;
	private String agentNo;
	private String riskProfile;
	private String riskProfileDescription;
	private String riskType;
	private String classOfRisk;
	private String status;

	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;

	@Id
	@Column(name = "AMS_ID", unique = true, nullable = false)
	public Long getAmsId() {
		return this.amsId;
	}

	public void setAmsId(Long amsId) {
		this.amsId = amsId;
	}

	@Column(name = "RISK_TYPE", nullable = false, length = 10)
	public String getRiskType() {
		return riskType;
	}

	public void setRiskType(String riskType) {
		this.riskType = riskType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_AGENTSAGT_ID")
	public AgentEntity getAgent() {
		return this.agent;
	}

	public void setAgent(AgentEntity agent) {
		this.agent = agent;
	}

	@Column(name = "AGENT_NO", length = 8)
	public String getAgentNo() {
		return this.agentNo;
	}

	public void setAgentNo(String agentNo) {
		this.agentNo = agentNo;
	}

	@Column(name = "RISK_PROFILE", length = 8)
	public String getRiskProfile() {
		return riskProfile;
	}

	public void setRiskProfile(String riskProfile) {
		this.riskProfile = riskProfile;
	}

	@Column(name = "RISK_PROFILE_DESCRIPTION", length = 80)
	public String getRiskProfileDescription() {
		return riskProfileDescription;
	}

	public void setRiskProfileDescription(String riskProfileDescription) {
		this.riskProfileDescription = riskProfileDescription;
	}

	@Column(name = "CLASS_OF_RISK", length = 1)
	public String getClassOfRisk() {
		return this.classOfRisk;
	}

	public void setClassOfRisk(String classOfRisk) {
		this.classOfRisk = classOfRisk;
	}

	@Column(name = "STATUS", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

}
