package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * BankAccountEntity generated by hbm2java
 */
@Entity
@Table(name = "BANK_ACCOUNTS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifiedDate", "modifiedTime", "modifiedBy" })
public class BankAccountEntity implements java.io.Serializable, ChangeMetadata {

	private long bkaId;
	private ClientEntity client;
	private Long clientId;
	private int accountNo;
	private int type;
	private String accountName;
	private String sortCode;
	private String accountCode;
	private String supplementaryCode;
	private String bankName;
	private String bankAddress1;
	private String bankAddress2;
	private Integer collectionMethod;
	private String classification;
	private Integer billingDay;
	private int status;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private String modifiedBy;
	private Date modifiedTime;
	private Date modifiedDate;
	private String modifiedProcess;
	private Integer cardExpiryDate;
	private Integer seriesNo;
	private Integer cardType;
	private Date mandateExpiryDate;
	private String clientReference;
	private String premiumSource;

	@Id
	@Column(name = "BKA_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getBkaId() {
		return this.bkaId;
	}

	public void setBkaId(long bkaId) {
		this.bkaId = bkaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLIENTSCLI_ID")
	public ClientEntity getClient() {
		return this.client;
	}

	public void setClient(ClientEntity client) {
		this.client = client;
	}

	@Column(name = "CLIENT", precision = 10, scale = 0)
	public Long getClientId() {
		return this.clientId;
	}

	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	@Column(name = "ACCOUNT_NO", nullable = false)
	public int getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(int accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "ACCOUNT_NAME", length = 40)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "SORT_CODE", length = 15)
	public String getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(String sortCode) {
		this.sortCode = sortCode;
	}

	@Column(name = "ACCOUNT_CODE", length = 35)
	public String getAccountCode() {
		return this.accountCode;
	}

	public void setAccountCode(String accountCode) {
		this.accountCode = accountCode;
	}

	@Column(name = "SUPPLEMENTARY_CODE", length = 15)
	public String getSupplementaryCode() {
		return this.supplementaryCode;
	}

	public void setSupplementaryCode(String supplementaryCode) {
		this.supplementaryCode = supplementaryCode;
	}

	@Column(name = "BANK_NAME", length = 30)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "BANK_ADDRESS1", length = 40)
	public String getBankAddress1() {
		return this.bankAddress1;
	}

	public void setBankAddress1(String bankAddress1) {
		this.bankAddress1 = bankAddress1;
	}

	@Column(name = "BANK_ADDRESS2", length = 40)
	public String getBankAddress2() {
		return this.bankAddress2;
	}

	public void setBankAddress2(String bankAddress2) {
		this.bankAddress2 = bankAddress2;
	}

	@Column(name = "COLLECTION_METHOD")
	public Integer getCollectionMethod() {
		return this.collectionMethod;
	}

	public void setCollectionMethod(Integer collectionMethod) {
		this.collectionMethod = collectionMethod;
	}

	@Column(name = "CLASSIFICATION", length = 8)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "BILLING_DAY")
	public Integer getBillingDay() {
		return this.billingDay;
	}

	public void setBillingDay(Integer billingDay) {
		this.billingDay = billingDay;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFIED_BY", length = 5)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_TIME", length = 23)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 23)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_PROCESS", length = 15)
	public String getModifiedProcess() {
		return this.modifiedProcess;
	}

	public void setModifiedProcess(String modifiedProcess) {
		this.modifiedProcess = modifiedProcess;
	}

	@Column(name = "CARD_EXPIRY_DATE")
	public Integer getCardExpiryDate() {
		return this.cardExpiryDate;
	}

	public void setCardExpiryDate(Integer cardExpiryDate) {
		this.cardExpiryDate = cardExpiryDate;
	}

	@Column(name = "SERIES_NO")
	public Integer getSeriesNo() {
		return this.seriesNo;
	}

	public void setSeriesNo(Integer seriesNo) {
		this.seriesNo = seriesNo;
	}

	@Column(name = "CARD_TYPE")
	public Integer getCardType() {
		return this.cardType;
	}

	public void setCardType(Integer cardType) {
		this.cardType = cardType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MANDATE_EXPIRY_DATE", length = 23)
	public Date getMandateExpiryDate() {
		return this.mandateExpiryDate;
	}

	public void setMandateExpiryDate(Date mandateExpiryDate) {
		this.mandateExpiryDate = mandateExpiryDate;
	}

	@Column(name = "CLIENT_REFERENCE", length = 12)
	public String getClientReference() {
		return this.clientReference;
	}

	public void setClientReference(String clientReference) {
		this.clientReference = clientReference;
	}

	@Column(name = "PREMIUM_SOURCE", length = 8)
	public String getPremiumSource() {
		return this.premiumSource;
	}

	public void setPremiumSource(String premiumSource) {
		this.premiumSource = premiumSource;
	}

}
