package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchErrorEntity generated by hbm2java
 */
@Entity
@Table(name = "BATCH_ERRORS"

)
public class BatchErrorEntity implements java.io.Serializable {

	private long berId;
	private QueuedTaskDateEntity queuedTaskDate;
	private QueuedTaskEntity queuedTask;
	private String user0;
	private String errorParameters;
	private String errorNo;
	private Integer task;
	private Integer severity;
	private Integer occurred;
	private String policy;
	private Integer status;
	private Date creationDate;
	private Date creationTime;

	@Id
	@Column(name = "BER_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getBerId() {
		return this.berId;
	}

	public void setBerId(long berId) {
		this.berId = berId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_QUEUED_TASK_QTD_ID")
	public QueuedTaskDateEntity getQueuedTaskDate() {
		return this.queuedTaskDate;
	}

	public void setQueuedTaskDate(QueuedTaskDateEntity queuedTaskDate) {
		this.queuedTaskDate = queuedTaskDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_QUEUED_TASKSQTA_ID")
	public QueuedTaskEntity getQueuedTask() {
		return this.queuedTask;
	}

	public void setQueuedTask(QueuedTaskEntity queuedTask) {
		this.queuedTask = queuedTask;
	}

	@Column(name = "USER0", length = 12)
	public String getUser0() {
		return this.user0;
	}

	public void setUser0(String user0) {
		this.user0 = user0;
	}

	@Column(name = "ERROR_PARAMETERS", length = 15)
	public String getErrorParameters() {
		return this.errorParameters;
	}

	public void setErrorParameters(String errorParameters) {
		this.errorParameters = errorParameters;
	}

	@Column(name = "ERROR_NO", length = 8)
	public String getErrorNo() {
		return this.errorNo;
	}

	public void setErrorNo(String errorNo) {
		this.errorNo = errorNo;
	}

	@Column(name = "TASK")
	public Integer getTask() {
		return this.task;
	}

	public void setTask(Integer task) {
		this.task = task;
	}

	@Column(name = "SEVERITY")
	public Integer getSeverity() {
		return this.severity;
	}

	public void setSeverity(Integer severity) {
		this.severity = severity;
	}

	@Column(name = "OCCURRED")
	public Integer getOccurred() {
		return this.occurred;
	}

	public void setOccurred(Integer occurred) {
		this.occurred = occurred;
	}

	@Column(name = "POLICY", length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", length = 23)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_TIME", length = 23)
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

}
