package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ClaimLineEntity generated by hbm2java
 */
@Entity
@Table(name="CLAIM_LINES"
    
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler","createdProcess","modifyProcess","createdBy","createdDate","createdTime","modifyDate","modifyTime","modifyBy"})
public class ClaimLineEntity  implements java.io.Serializable {


     private long cmlId;
     private ClaimEntity claim;
	private Long claimId;
     private int line;
     private Integer coverage;
     private Long clientNo;
     private Date notificationDate;
     private Date incidentDate;
     private String benefit;
     private String subBenefit;
     private int factor;
     private BigDecimal estimatedClaim;
     private String estimatedClaimCcy;
     private BigDecimal enteredClaim;
     private String enteredClaimCcy;
     private BigDecimal paidClaim;
     private String paidClaimCcy;
     private int ppo;
     private int status;
     private String createdBy;
     private Date createdTime;
     private Date createdDate;
     private String createdProcess;
     private String modifyBy;
     private Date modifyTime;
     private Date modifyDate;
     private String modifyProcess;
     private BigDecimal rateOrPercentage;
     private Integer modifier;
   
     @Id 
    @Column(name="CML_ID", unique=true, nullable=false, precision=13, scale=0)
    public long getCmlId() {
        return this.cmlId;
    }
    
    public void setCmlId(long cmlId) {
        this.cmlId = cmlId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_CLAIMSCLM_ID")
    public ClaimEntity getClaim() {
        return this.claim;
    }
    
    public void setClaim(ClaimEntity claim) {
        this.claim = claim;
    }

    
    @Column(name="CLAIM", precision=10, scale=0)
	public Long getClaimId() {
		return this.claimId;
    }
    
	public void setClaimId(Long claimId) {
		this.claimId = claimId;
    }

    
    @Column(name="LINE", nullable=false)
    public int getLine() {
        return this.line;
    }
    
    public void setLine(int line) {
        this.line = line;
    }

    
    @Column(name="COVERAGE")
    public Integer getCoverage() {
        return this.coverage;
    }
    
    public void setCoverage(Integer coverage) {
        this.coverage = coverage;
    }

    
    @Column(name="CLIENT_NO", precision=10, scale=0)
    public Long getClientNo() {
        return this.clientNo;
    }
    
    public void setClientNo(Long clientNo) {
        this.clientNo = clientNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NOTIFICATION_DATE", length=23)
    public Date getNotificationDate() {
        return this.notificationDate;
    }
    
    public void setNotificationDate(Date notificationDate) {
        this.notificationDate = notificationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INCIDENT_DATE", length=23)
    public Date getIncidentDate() {
        return this.incidentDate;
    }
    
    public void setIncidentDate(Date incidentDate) {
        this.incidentDate = incidentDate;
    }

    
    @Column(name="BENEFIT", length=8)
    public String getBenefit() {
        return this.benefit;
    }
    
    public void setBenefit(String benefit) {
        this.benefit = benefit;
    }

    
    @Column(name="SUB_BENEFIT", length=8)
    public String getSubBenefit() {
        return this.subBenefit;
    }
    
    public void setSubBenefit(String subBenefit) {
        this.subBenefit = subBenefit;
    }

    
    @Column(name="FACTOR", nullable=false)
    public int getFactor() {
        return this.factor;
    }
    
    public void setFactor(int factor) {
        this.factor = factor;
    }

    
    @Column(name="ESTIMATED_CLAIM", precision=15)
    public BigDecimal getEstimatedClaim() {
        return this.estimatedClaim;
    }
    
    public void setEstimatedClaim(BigDecimal estimatedClaim) {
        this.estimatedClaim = estimatedClaim;
    }

    
    @Column(name="ESTIMATED_CLAIM_CCY", length=3)
    public String getEstimatedClaimCcy() {
        return this.estimatedClaimCcy;
    }
    
    public void setEstimatedClaimCcy(String estimatedClaimCcy) {
        this.estimatedClaimCcy = estimatedClaimCcy;
    }

    
    @Column(name="ENTERED_CLAIM", precision=15)
    public BigDecimal getEnteredClaim() {
        return this.enteredClaim;
    }
    
    public void setEnteredClaim(BigDecimal enteredClaim) {
        this.enteredClaim = enteredClaim;
    }

    
    @Column(name="ENTERED_CLAIM_CCY", length=3)
    public String getEnteredClaimCcy() {
        return this.enteredClaimCcy;
    }
    
    public void setEnteredClaimCcy(String enteredClaimCcy) {
        this.enteredClaimCcy = enteredClaimCcy;
    }

    
    @Column(name="PAID_CLAIM", precision=15)
    public BigDecimal getPaidClaim() {
        return this.paidClaim;
    }
    
    public void setPaidClaim(BigDecimal paidClaim) {
        this.paidClaim = paidClaim;
    }

    
    @Column(name="PAID_CLAIM_CCY", length=3)
    public String getPaidClaimCcy() {
        return this.paidClaimCcy;
    }
    
    public void setPaidClaimCcy(String paidClaimCcy) {
        this.paidClaimCcy = paidClaimCcy;
    }

    
    @Column(name="PPO", nullable=false)
    public int getPpo() {
        return this.ppo;
    }
    
    public void setPpo(int ppo) {
        this.ppo = ppo;
    }

    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CREATED_PROCESS", nullable=false, length=12)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }

    
    @Column(name="MODIFY_BY", length=5)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    
    @Column(name="MODIFY_PROCESS", length=15)
    public String getModifyProcess() {
        return this.modifyProcess;
    }
    
    public void setModifyProcess(String modifyProcess) {
        this.modifyProcess = modifyProcess;
    }

    
    @Column(name="RATE_OR_PERCENTAGE", precision=15, scale=8)
    public BigDecimal getRateOrPercentage() {
        return this.rateOrPercentage;
    }
    
    public void setRateOrPercentage(BigDecimal rateOrPercentage) {
        this.rateOrPercentage = rateOrPercentage;
    }

    
    @Column(name="MODIFIER")
    public Integer getModifier() {
        return this.modifier;
    }
    
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }




}


