package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CliCliRelationEntity generated by hbm2java
 */
@Entity
@Table(name = "CLI_CLI_RELATIONS"

)
public class CliCliRelationEntity implements java.io.Serializable {

	private long ccrId;
	private int clientNumber;
	private Date endDate;
	private Long relatedToClient;
	private Date activeDate;
	private int type;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Set<ClientEntity> clients = new HashSet<ClientEntity>(0);

	@Id
	@Column(name = "CCR_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getCcrId() {
		return this.ccrId;
	}

	public void setCcrId(long ccrId) {
		this.ccrId = ccrId;
	}

	@Column(name = "CLIENT_NUMBER", nullable = false)
	public int getClientNumber() {
		return this.clientNumber;
	}

	public void setClientNumber(int clientNumber) {
		this.clientNumber = clientNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", nullable = false, length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "RELATED_TO_CLIENT", precision = 10, scale = 0)
	public Long getRelatedToClient() {
		return this.relatedToClient;
	}

	public void setRelatedToClient(Long relatedToClient) {
		this.relatedToClient = relatedToClient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVE_DATE", nullable = false, length = 23)
	public Date getActiveDate() {
		return this.activeDate;
	}

	public void setActiveDate(Date activeDate) {
		this.activeDate = activeDate;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "HAVE", joinColumns = {
			@JoinColumn(name = "FK_CLI_CLI_RELACCR_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "FK_CLIENTSCLI_ID", nullable = false, updatable = false) })
	public Set<ClientEntity> getClients() {
		return this.clients;
	}

	public void setClients(Set<ClientEntity> clients) {
		this.clients = clients;
	}

}
