package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentFieldEntity generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT_FIELDS"

)
public class DocumentFieldEntity implements java.io.Serializable {

	private int dflId;
	private String name;
	private String description;
	private Integer outputConversion;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private Set<DocumentDefinitionEntity> documentDefinitions = new HashSet<DocumentDefinitionEntity>(0);

	@Id
	@Column(name = "DFL_ID", unique = true, nullable = false)
	public int getDflId() {
		return this.dflId;
	}

	public void setDflId(int dflId) {
		this.dflId = dflId;
	}

	@Column(name = "NAME", length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 25)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "OUTPUT_CONVERSION")
	public Integer getOutputConversion() {
		return this.outputConversion;
	}

	public void setOutputConversion(Integer outputConversion) {
		this.outputConversion = outputConversion;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "IS_USED_IN", joinColumns = {
			@JoinColumn(name = "FK_DOCUMENT_FIEDFL_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "FK_DOCUMENT_DEFDDF_ID", nullable = false, updatable = false) })
	public Set<DocumentDefinitionEntity> getDocumentDefinitions() {
		return this.documentDefinitions;
	}

	public void setDocumentDefinitions(Set<DocumentDefinitionEntity> documentDefinitions) {
		this.documentDefinitions = documentDefinitions;
	}

}
