package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentCorrespEntityId generated by hbm2java
 */
@Embeddable
public class DocumentCorrespEntityId  implements java.io.Serializable {


     private String dcpId;
     private int language;

    public DocumentCorrespEntityId() {
    }

    public DocumentCorrespEntityId(String dcpId, int language) {
       this.dcpId = dcpId;
       this.language = language;
    }
   


    @Column(name="DCP_ID", nullable=false, length=15)
    public String getDcpId() {
        return this.dcpId;
    }
    
    public void setDcpId(String dcpId) {
        this.dcpId = dcpId;
    }


    @Column(name="LANGUAGE", nullable=false)
    public int getLanguage() {
        return this.language;
    }
    
    public void setLanguage(int language) {
        this.language = language;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentCorrespEntityId) ) return false;
		 DocumentCorrespEntityId castOther = ( DocumentCorrespEntityId ) other; 
         
		 return ( (this.getDcpId()==castOther.getDcpId()) || ( this.getDcpId()!=null && castOther.getDcpId()!=null && this.getDcpId().equals(castOther.getDcpId()) ) )
 && (this.getLanguage()==castOther.getLanguage());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDcpId() == null ? 0 : this.getDcpId().hashCode() );
         result = 37 * result + this.getLanguage();
         return result;
   }   


}


