package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * FundEventEntity generated by hbm2java
 */
@Entity
@Table(name="FUND_EVENTS"
    
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler","createdProcess","modifyProcess","createdBy","createdDate","createdTime","modifyDate","modifyTime","modifyBy"})
public class FundEventEntity  implements java.io.Serializable {


     private int fevId;
     @JsonIgnore
     private FundEntity fund;
     private int status;
     private Date createdTime;
     private Date createdDate;
     private String createdBy;
     private String createdProcess;
     private Integer occurrence;
     private Date actualEventDate;
	private String fundId;
     private Date systemDate;
     private Date effectiveDate;
     private String event;

     @Id 

    
    @Column(name="FEV_ID", unique=true, nullable=false)
    public int getFevId() {
        return this.fevId;
    }
    
    public void setFevId(int fevId) {
        this.fevId = fevId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_FUNDSFDS_ID")
	@NotFound(action=NotFoundAction.IGNORE)
    public FundEntity getFund() {
        return this.fund;
    }
    
    public void setFund(FundEntity fund) {
        this.fund = fund;
    }

    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="CREATED_PROCESS", nullable=false, length=15)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }

    
    @Column(name="OCCURRENCE")
    public Integer getOccurrence() {
        return this.occurrence;
    }
    
    public void setOccurrence(Integer occurrence) {
        this.occurrence = occurrence;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_EVENT_DATE", nullable=false, length=23)
    public Date getActualEventDate() {
        return this.actualEventDate;
    }
    
    public void setActualEventDate(Date actualEventDate) {
        this.actualEventDate = actualEventDate;
    }

    
    @Column(name="FUND", nullable=false, length=8)
	public String getFundId() {
		return this.fundId;
    }
    
	public void setFundId(String fundId) {
		this.fundId = fundId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SYSTEM_DATE", nullable=false, length=23)
    public Date getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(Date systemDate) {
        this.systemDate = systemDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE", nullable=false, length=23)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    
    @Column(name="EVENT", nullable=false, length=35)
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }




}


