package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FundsHistoryEntityId generated by hbm2java
 */
@Embeddable
public class FundsHistoryEntityId  implements java.io.Serializable {


     private String histId;
     private String action0;
     private String actionBy;
     private Date actionDatetime;
     private String fdsId;
     private String currency;
     private int fundType;
     private String name;
     private int pricingFrequency;
     private Integer pricingDay;
     private Integer pricingDayOfMonth;
     private int priceBasis;
     private BigDecimal bidOfferSpread;
     private int status;
     private int unitTypes;
     private Integer fwdPriceReportDays;
     private String groupingCode;
     private String createdBy;
     private Date createdDate;
     private Date createdTime;
     private String createdProcess;
     private String modifyBy;
     private Date modifyDate;
     private Date modifyTime;
     private String modifyProcess;
     private Date pricingTime;
     private Integer accountingStream;
     private String documentationName;
     private String isinCode;
     private String nlProduct;
     private Date cutOffTime;
     private String ulFundType;
     private BigDecimal maxAllocationPercent;
     private String assetManager;
     private String depositBank;
     private String country;
     private BigDecimal navEntryFee;
     private BigDecimal navExitFee;
     private String riskProfile;
     private String riskCurrency;
     private String investCat;
     private String investObjective;
     private String alternativeFunds;
     private Date riskProfileDate;
     private String notes;
     private Integer pricingDelay;
     private String iban;
     private String salesRep;
     private BigDecimal investCashLimit;
     private Integer poa;
     private String poaType;
     private String mandateHolder;
     private Date poaDate;

    public FundsHistoryEntityId() {
    }

	
    public FundsHistoryEntityId(String histId, String fdsId, String currency, int fundType, String name, int pricingFrequency, int priceBasis, int status, int unitTypes, String createdBy, Date createdDate, Date createdTime) {
        this.histId = histId;
        this.fdsId = fdsId;
        this.currency = currency;
        this.fundType = fundType;
        this.name = name;
        this.pricingFrequency = pricingFrequency;
        this.priceBasis = priceBasis;
        this.status = status;
        this.unitTypes = unitTypes;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.createdTime = createdTime;
    }
    public FundsHistoryEntityId(String histId, String action0, String actionBy, Date actionDatetime, String fdsId, String currency, int fundType, String name, int pricingFrequency, Integer pricingDay, Integer pricingDayOfMonth, int priceBasis, BigDecimal bidOfferSpread, int status, int unitTypes, Integer fwdPriceReportDays, String groupingCode, String createdBy, Date createdDate, Date createdTime, String createdProcess, String modifyBy, Date modifyDate, Date modifyTime, String modifyProcess, Date pricingTime, Integer accountingStream, String documentationName, String isinCode, String nlProduct, Date cutOffTime, String ulFundType, BigDecimal maxAllocationPercent, String assetManager, String depositBank, String country, BigDecimal navEntryFee, BigDecimal navExitFee, String riskProfile, String riskCurrency, String investCat, String investObjective, String alternativeFunds, Date riskProfileDate, String notes, Integer pricingDelay, String iban, String salesRep, BigDecimal investCashLimit, Integer poa, String poaType, String mandateHolder, Date poaDate) {
       this.histId = histId;
       this.action0 = action0;
       this.actionBy = actionBy;
       this.actionDatetime = actionDatetime;
       this.fdsId = fdsId;
       this.currency = currency;
       this.fundType = fundType;
       this.name = name;
       this.pricingFrequency = pricingFrequency;
       this.pricingDay = pricingDay;
       this.pricingDayOfMonth = pricingDayOfMonth;
       this.priceBasis = priceBasis;
       this.bidOfferSpread = bidOfferSpread;
       this.status = status;
       this.unitTypes = unitTypes;
       this.fwdPriceReportDays = fwdPriceReportDays;
       this.groupingCode = groupingCode;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.createdProcess = createdProcess;
       this.modifyBy = modifyBy;
       this.modifyDate = modifyDate;
       this.modifyTime = modifyTime;
       this.modifyProcess = modifyProcess;
       this.pricingTime = pricingTime;
       this.accountingStream = accountingStream;
       this.documentationName = documentationName;
       this.isinCode = isinCode;
       this.nlProduct = nlProduct;
       this.cutOffTime = cutOffTime;
       this.ulFundType = ulFundType;
       this.maxAllocationPercent = maxAllocationPercent;
       this.assetManager = assetManager;
       this.depositBank = depositBank;
       this.country = country;
       this.navEntryFee = navEntryFee;
       this.navExitFee = navExitFee;
       this.riskProfile = riskProfile;
       this.riskCurrency = riskCurrency;
       this.investCat = investCat;
       this.investObjective = investObjective;
       this.alternativeFunds = alternativeFunds;
       this.riskProfileDate = riskProfileDate;
       this.notes = notes;
       this.pricingDelay = pricingDelay;
       this.iban = iban;
       this.salesRep = salesRep;
       this.investCashLimit = investCashLimit;
       this.poa = poa;
       this.poaType = poaType;
       this.mandateHolder = mandateHolder;
       this.poaDate = poaDate;
    }
   


    @Column(name="HIST_ID", nullable=false, length=60)
    public String getHistId() {
        return this.histId;
    }
    
    public void setHistId(String histId) {
        this.histId = histId;
    }


    @Column(name="Action0", length=20)
    public String getAction0() {
        return this.action0;
    }
    
    public void setAction0(String action0) {
        this.action0 = action0;
    }


    @Column(name="Action_by", length=100)
    public String getActionBy() {
        return this.actionBy;
    }
    
    public void setActionBy(String actionBy) {
        this.actionBy = actionBy;
    }


    @Column(name="Action_datetime", length=23)
    public Date getActionDatetime() {
        return this.actionDatetime;
    }
    
    public void setActionDatetime(Date actionDatetime) {
        this.actionDatetime = actionDatetime;
    }


    @Column(name="FDS_ID", nullable=false, length=8)
    public String getFdsId() {
        return this.fdsId;
    }
    
    public void setFdsId(String fdsId) {
        this.fdsId = fdsId;
    }


    @Column(name="CURRENCY", nullable=false, length=5)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }


    @Column(name="FUND_TYPE", nullable=false)
    public int getFundType() {
        return this.fundType;
    }
    
    public void setFundType(int fundType) {
        this.fundType = fundType;
    }


    @Column(name="NAME", nullable=false, length=35)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


    @Column(name="PRICING_FREQUENCY", nullable=false)
    public int getPricingFrequency() {
        return this.pricingFrequency;
    }
    
    public void setPricingFrequency(int pricingFrequency) {
        this.pricingFrequency = pricingFrequency;
    }


    @Column(name="PRICING_DAY")
    public Integer getPricingDay() {
        return this.pricingDay;
    }
    
    public void setPricingDay(Integer pricingDay) {
        this.pricingDay = pricingDay;
    }


    @Column(name="PRICING_DAY_OF_MONTH")
    public Integer getPricingDayOfMonth() {
        return this.pricingDayOfMonth;
    }
    
    public void setPricingDayOfMonth(Integer pricingDayOfMonth) {
        this.pricingDayOfMonth = pricingDayOfMonth;
    }


    @Column(name="PRICE_BASIS", nullable=false)
    public int getPriceBasis() {
        return this.priceBasis;
    }
    
    public void setPriceBasis(int priceBasis) {
        this.priceBasis = priceBasis;
    }


    @Column(name="BID_OFFER_SPREAD", precision=8, scale=4)
    public BigDecimal getBidOfferSpread() {
        return this.bidOfferSpread;
    }
    
    public void setBidOfferSpread(BigDecimal bidOfferSpread) {
        this.bidOfferSpread = bidOfferSpread;
    }


    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }


    @Column(name="UNIT_TYPES", nullable=false)
    public int getUnitTypes() {
        return this.unitTypes;
    }
    
    public void setUnitTypes(int unitTypes) {
        this.unitTypes = unitTypes;
    }


    @Column(name="FWD_PRICE_REPORT_DAYS")
    public Integer getFwdPriceReportDays() {
        return this.fwdPriceReportDays;
    }
    
    public void setFwdPriceReportDays(Integer fwdPriceReportDays) {
        this.fwdPriceReportDays = fwdPriceReportDays;
    }


    @Column(name="GROUPING_CODE", length=10)
    public String getGroupingCode() {
        return this.groupingCode;
    }
    
    public void setGroupingCode(String groupingCode) {
        this.groupingCode = groupingCode;
    }


    @Column(name="CREATED_BY", nullable=false, length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }


    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }


    @Column(name="CREATED_PROCESS", length=12)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }


    @Column(name="MODIFY_BY", length=5)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }


    @Column(name="MODIFY_DATE", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }


    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }


    @Column(name="MODIFY_PROCESS", length=12)
    public String getModifyProcess() {
        return this.modifyProcess;
    }
    
    public void setModifyProcess(String modifyProcess) {
        this.modifyProcess = modifyProcess;
    }


    @Column(name="PRICING_TIME", length=23)
    public Date getPricingTime() {
        return this.pricingTime;
    }
    
    public void setPricingTime(Date pricingTime) {
        this.pricingTime = pricingTime;
    }


    @Column(name="ACCOUNTING_STREAM")
    public Integer getAccountingStream() {
        return this.accountingStream;
    }
    
    public void setAccountingStream(Integer accountingStream) {
        this.accountingStream = accountingStream;
    }


    @Column(name="DOCUMENTATION_NAME", length=100)
    public String getDocumentationName() {
        return this.documentationName;
    }
    
    public void setDocumentationName(String documentationName) {
        this.documentationName = documentationName;
    }


    @Column(name="ISIN_CODE", length=12)
    public String getIsinCode() {
        return this.isinCode;
    }
    
    public void setIsinCode(String isinCode) {
        this.isinCode = isinCode;
    }


    @Column(name="NL_PRODUCT", length=3)
    public String getNlProduct() {
        return this.nlProduct;
    }
    
    public void setNlProduct(String nlProduct) {
        this.nlProduct = nlProduct;
    }


    @Column(name="CUT_OFF_TIME", length=23)
    public Date getCutOffTime() {
        return this.cutOffTime;
    }
    
    public void setCutOffTime(Date cutOffTime) {
        this.cutOffTime = cutOffTime;
    }


    @Column(name="UL_FUND_TYPE", length=8)
    public String getUlFundType() {
        return this.ulFundType;
    }
    
    public void setUlFundType(String ulFundType) {
        this.ulFundType = ulFundType;
    }


    @Column(name="MAX_ALLOCATION_PERCENT", precision=8, scale=4)
    public BigDecimal getMaxAllocationPercent() {
        return this.maxAllocationPercent;
    }
    
    public void setMaxAllocationPercent(BigDecimal maxAllocationPercent) {
        this.maxAllocationPercent = maxAllocationPercent;
    }


    @Column(name="ASSET_MANAGER", length=8)
    public String getAssetManager() {
        return this.assetManager;
    }
    
    public void setAssetManager(String assetManager) {
        this.assetManager = assetManager;
    }


    @Column(name="DEPOSIT_BANK", length=8)
    public String getDepositBank() {
        return this.depositBank;
    }
    
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank;
    }


    @Column(name="COUNTRY", length=27)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }


    @Column(name="NAV_ENTRY_FEE", precision=15, scale=6)
    public BigDecimal getNavEntryFee() {
        return this.navEntryFee;
    }
    
    public void setNavEntryFee(BigDecimal navEntryFee) {
        this.navEntryFee = navEntryFee;
    }


    @Column(name="NAV_EXIT_FEE", precision=15, scale=6)
    public BigDecimal getNavExitFee() {
        return this.navExitFee;
    }
    
    public void setNavExitFee(BigDecimal navExitFee) {
        this.navExitFee = navExitFee;
    }


    @Column(name="RISK_PROFILE", length=8)
    public String getRiskProfile() {
        return this.riskProfile;
    }
    
    public void setRiskProfile(String riskProfile) {
        this.riskProfile = riskProfile;
    }


    @Column(name="RISK_CURRENCY", length=8)
    public String getRiskCurrency() {
        return this.riskCurrency;
    }
    
    public void setRiskCurrency(String riskCurrency) {
        this.riskCurrency = riskCurrency;
    }


    @Column(name="INVEST_CAT", length=8)
    public String getInvestCat() {
        return this.investCat;
    }
    
    public void setInvestCat(String investCat) {
        this.investCat = investCat;
    }


    @Column(name="INVEST_OBJECTIVE", length=8)
    public String getInvestObjective() {
        return this.investObjective;
    }
    
    public void setInvestObjective(String investObjective) {
        this.investObjective = investObjective;
    }


    @Column(name="ALTERNATIVE_FUNDS", length=8)
    public String getAlternativeFunds() {
        return this.alternativeFunds;
    }
    
    public void setAlternativeFunds(String alternativeFunds) {
        this.alternativeFunds = alternativeFunds;
    }


    @Column(name="RISK_PROFILE_DATE", length=23)
    public Date getRiskProfileDate() {
        return this.riskProfileDate;
    }
    
    public void setRiskProfileDate(Date riskProfileDate) {
        this.riskProfileDate = riskProfileDate;
    }


    @Column(name="NOTES", length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }


    @Column(name="PRICING_DELAY")
    public Integer getPricingDelay() {
        return this.pricingDelay;
    }
    
    public void setPricingDelay(Integer pricingDelay) {
        this.pricingDelay = pricingDelay;
    }


    @Column(name="IBAN", length=35)
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }


    @Column(name="SALES_REP", length=8)
    public String getSalesRep() {
        return this.salesRep;
    }
    
    public void setSalesRep(String salesRep) {
        this.salesRep = salesRep;
    }


    @Column(name="INVEST_CASH_LIMIT", precision=15)
    public BigDecimal getInvestCashLimit() {
        return this.investCashLimit;
    }
    
    public void setInvestCashLimit(BigDecimal investCashLimit) {
        this.investCashLimit = investCashLimit;
    }


    @Column(name="POA")
    public Integer getPoa() {
        return this.poa;
    }
    
    public void setPoa(Integer poa) {
        this.poa = poa;
    }


    @Column(name="POA_TYPE", length=12)
    public String getPoaType() {
        return this.poaType;
    }
    
    public void setPoaType(String poaType) {
        this.poaType = poaType;
    }


    @Column(name="MANDATE_HOLDER", length=8)
    public String getMandateHolder() {
        return this.mandateHolder;
    }
    
    public void setMandateHolder(String mandateHolder) {
        this.mandateHolder = mandateHolder;
    }


    @Column(name="POA_DATE", length=23)
    public Date getPoaDate() {
        return this.poaDate;
    }
    
    public void setPoaDate(Date poaDate) {
        this.poaDate = poaDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FundsHistoryEntityId) ) return false;
		 FundsHistoryEntityId castOther = ( FundsHistoryEntityId ) other; 
         
		 return ( (this.getHistId()==castOther.getHistId()) || ( this.getHistId()!=null && castOther.getHistId()!=null && this.getHistId().equals(castOther.getHistId()) ) )
 && ( (this.getAction0()==castOther.getAction0()) || ( this.getAction0()!=null && castOther.getAction0()!=null && this.getAction0().equals(castOther.getAction0()) ) )
 && ( (this.getActionBy()==castOther.getActionBy()) || ( this.getActionBy()!=null && castOther.getActionBy()!=null && this.getActionBy().equals(castOther.getActionBy()) ) )
 && ( (this.getActionDatetime()==castOther.getActionDatetime()) || ( this.getActionDatetime()!=null && castOther.getActionDatetime()!=null && this.getActionDatetime().equals(castOther.getActionDatetime()) ) )
 && ( (this.getFdsId()==castOther.getFdsId()) || ( this.getFdsId()!=null && castOther.getFdsId()!=null && this.getFdsId().equals(castOther.getFdsId()) ) )
 && ( (this.getCurrency()==castOther.getCurrency()) || ( this.getCurrency()!=null && castOther.getCurrency()!=null && this.getCurrency().equals(castOther.getCurrency()) ) )
 && (this.getFundType()==castOther.getFundType())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && (this.getPricingFrequency()==castOther.getPricingFrequency())
 && ( (this.getPricingDay()==castOther.getPricingDay()) || ( this.getPricingDay()!=null && castOther.getPricingDay()!=null && this.getPricingDay().equals(castOther.getPricingDay()) ) )
 && ( (this.getPricingDayOfMonth()==castOther.getPricingDayOfMonth()) || ( this.getPricingDayOfMonth()!=null && castOther.getPricingDayOfMonth()!=null && this.getPricingDayOfMonth().equals(castOther.getPricingDayOfMonth()) ) )
 && (this.getPriceBasis()==castOther.getPriceBasis())
 && ( (this.getBidOfferSpread()==castOther.getBidOfferSpread()) || ( this.getBidOfferSpread()!=null && castOther.getBidOfferSpread()!=null && this.getBidOfferSpread().equals(castOther.getBidOfferSpread()) ) )
 && (this.getStatus()==castOther.getStatus())
 && (this.getUnitTypes()==castOther.getUnitTypes())
 && ( (this.getFwdPriceReportDays()==castOther.getFwdPriceReportDays()) || ( this.getFwdPriceReportDays()!=null && castOther.getFwdPriceReportDays()!=null && this.getFwdPriceReportDays().equals(castOther.getFwdPriceReportDays()) ) )
 && ( (this.getGroupingCode()==castOther.getGroupingCode()) || ( this.getGroupingCode()!=null && castOther.getGroupingCode()!=null && this.getGroupingCode().equals(castOther.getGroupingCode()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && this.getCreatedDate().equals(castOther.getCreatedDate()) ) )
 && ( (this.getCreatedTime()==castOther.getCreatedTime()) || ( this.getCreatedTime()!=null && castOther.getCreatedTime()!=null && this.getCreatedTime().equals(castOther.getCreatedTime()) ) )
 && ( (this.getCreatedProcess()==castOther.getCreatedProcess()) || ( this.getCreatedProcess()!=null && castOther.getCreatedProcess()!=null && this.getCreatedProcess().equals(castOther.getCreatedProcess()) ) )
 && ( (this.getModifyBy()==castOther.getModifyBy()) || ( this.getModifyBy()!=null && castOther.getModifyBy()!=null && this.getModifyBy().equals(castOther.getModifyBy()) ) )
 && ( (this.getModifyDate()==castOther.getModifyDate()) || ( this.getModifyDate()!=null && castOther.getModifyDate()!=null && this.getModifyDate().equals(castOther.getModifyDate()) ) )
 && ( (this.getModifyTime()==castOther.getModifyTime()) || ( this.getModifyTime()!=null && castOther.getModifyTime()!=null && this.getModifyTime().equals(castOther.getModifyTime()) ) )
 && ( (this.getModifyProcess()==castOther.getModifyProcess()) || ( this.getModifyProcess()!=null && castOther.getModifyProcess()!=null && this.getModifyProcess().equals(castOther.getModifyProcess()) ) )
 && ( (this.getPricingTime()==castOther.getPricingTime()) || ( this.getPricingTime()!=null && castOther.getPricingTime()!=null && this.getPricingTime().equals(castOther.getPricingTime()) ) )
 && ( (this.getAccountingStream()==castOther.getAccountingStream()) || ( this.getAccountingStream()!=null && castOther.getAccountingStream()!=null && this.getAccountingStream().equals(castOther.getAccountingStream()) ) )
 && ( (this.getDocumentationName()==castOther.getDocumentationName()) || ( this.getDocumentationName()!=null && castOther.getDocumentationName()!=null && this.getDocumentationName().equals(castOther.getDocumentationName()) ) )
 && ( (this.getIsinCode()==castOther.getIsinCode()) || ( this.getIsinCode()!=null && castOther.getIsinCode()!=null && this.getIsinCode().equals(castOther.getIsinCode()) ) )
 && ( (this.getNlProduct()==castOther.getNlProduct()) || ( this.getNlProduct()!=null && castOther.getNlProduct()!=null && this.getNlProduct().equals(castOther.getNlProduct()) ) )
 && ( (this.getCutOffTime()==castOther.getCutOffTime()) || ( this.getCutOffTime()!=null && castOther.getCutOffTime()!=null && this.getCutOffTime().equals(castOther.getCutOffTime()) ) )
 && ( (this.getUlFundType()==castOther.getUlFundType()) || ( this.getUlFundType()!=null && castOther.getUlFundType()!=null && this.getUlFundType().equals(castOther.getUlFundType()) ) )
 && ( (this.getMaxAllocationPercent()==castOther.getMaxAllocationPercent()) || ( this.getMaxAllocationPercent()!=null && castOther.getMaxAllocationPercent()!=null && this.getMaxAllocationPercent().equals(castOther.getMaxAllocationPercent()) ) )
 && ( (this.getAssetManager()==castOther.getAssetManager()) || ( this.getAssetManager()!=null && castOther.getAssetManager()!=null && this.getAssetManager().equals(castOther.getAssetManager()) ) )
 && ( (this.getDepositBank()==castOther.getDepositBank()) || ( this.getDepositBank()!=null && castOther.getDepositBank()!=null && this.getDepositBank().equals(castOther.getDepositBank()) ) )
 && ( (this.getCountry()==castOther.getCountry()) || ( this.getCountry()!=null && castOther.getCountry()!=null && this.getCountry().equals(castOther.getCountry()) ) )
 && ( (this.getNavEntryFee()==castOther.getNavEntryFee()) || ( this.getNavEntryFee()!=null && castOther.getNavEntryFee()!=null && this.getNavEntryFee().equals(castOther.getNavEntryFee()) ) )
 && ( (this.getNavExitFee()==castOther.getNavExitFee()) || ( this.getNavExitFee()!=null && castOther.getNavExitFee()!=null && this.getNavExitFee().equals(castOther.getNavExitFee()) ) )
 && ( (this.getRiskProfile()==castOther.getRiskProfile()) || ( this.getRiskProfile()!=null && castOther.getRiskProfile()!=null && this.getRiskProfile().equals(castOther.getRiskProfile()) ) )
 && ( (this.getRiskCurrency()==castOther.getRiskCurrency()) || ( this.getRiskCurrency()!=null && castOther.getRiskCurrency()!=null && this.getRiskCurrency().equals(castOther.getRiskCurrency()) ) )
 && ( (this.getInvestCat()==castOther.getInvestCat()) || ( this.getInvestCat()!=null && castOther.getInvestCat()!=null && this.getInvestCat().equals(castOther.getInvestCat()) ) )
 && ( (this.getInvestObjective()==castOther.getInvestObjective()) || ( this.getInvestObjective()!=null && castOther.getInvestObjective()!=null && this.getInvestObjective().equals(castOther.getInvestObjective()) ) )
 && ( (this.getAlternativeFunds()==castOther.getAlternativeFunds()) || ( this.getAlternativeFunds()!=null && castOther.getAlternativeFunds()!=null && this.getAlternativeFunds().equals(castOther.getAlternativeFunds()) ) )
 && ( (this.getRiskProfileDate()==castOther.getRiskProfileDate()) || ( this.getRiskProfileDate()!=null && castOther.getRiskProfileDate()!=null && this.getRiskProfileDate().equals(castOther.getRiskProfileDate()) ) )
 && ( (this.getNotes()==castOther.getNotes()) || ( this.getNotes()!=null && castOther.getNotes()!=null && this.getNotes().equals(castOther.getNotes()) ) )
 && ( (this.getPricingDelay()==castOther.getPricingDelay()) || ( this.getPricingDelay()!=null && castOther.getPricingDelay()!=null && this.getPricingDelay().equals(castOther.getPricingDelay()) ) )
 && ( (this.getIban()==castOther.getIban()) || ( this.getIban()!=null && castOther.getIban()!=null && this.getIban().equals(castOther.getIban()) ) )
 && ( (this.getSalesRep()==castOther.getSalesRep()) || ( this.getSalesRep()!=null && castOther.getSalesRep()!=null && this.getSalesRep().equals(castOther.getSalesRep()) ) )
 && ( (this.getInvestCashLimit()==castOther.getInvestCashLimit()) || ( this.getInvestCashLimit()!=null && castOther.getInvestCashLimit()!=null && this.getInvestCashLimit().equals(castOther.getInvestCashLimit()) ) )
 && ( (this.getPoa()==castOther.getPoa()) || ( this.getPoa()!=null && castOther.getPoa()!=null && this.getPoa().equals(castOther.getPoa()) ) )
 && ( (this.getPoaType()==castOther.getPoaType()) || ( this.getPoaType()!=null && castOther.getPoaType()!=null && this.getPoaType().equals(castOther.getPoaType()) ) )
 && ( (this.getMandateHolder()==castOther.getMandateHolder()) || ( this.getMandateHolder()!=null && castOther.getMandateHolder()!=null && this.getMandateHolder().equals(castOther.getMandateHolder()) ) )
 && ( (this.getPoaDate()==castOther.getPoaDate()) || ( this.getPoaDate()!=null && castOther.getPoaDate()!=null && this.getPoaDate().equals(castOther.getPoaDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHistId() == null ? 0 : this.getHistId().hashCode() );
         result = 37 * result + ( getAction0() == null ? 0 : this.getAction0().hashCode() );
         result = 37 * result + ( getActionBy() == null ? 0 : this.getActionBy().hashCode() );
         result = 37 * result + ( getActionDatetime() == null ? 0 : this.getActionDatetime().hashCode() );
         result = 37 * result + ( getFdsId() == null ? 0 : this.getFdsId().hashCode() );
         result = 37 * result + ( getCurrency() == null ? 0 : this.getCurrency().hashCode() );
         result = 37 * result + this.getFundType();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + this.getPricingFrequency();
         result = 37 * result + ( getPricingDay() == null ? 0 : this.getPricingDay().hashCode() );
         result = 37 * result + ( getPricingDayOfMonth() == null ? 0 : this.getPricingDayOfMonth().hashCode() );
         result = 37 * result + this.getPriceBasis();
         result = 37 * result + ( getBidOfferSpread() == null ? 0 : this.getBidOfferSpread().hashCode() );
         result = 37 * result + this.getStatus();
         result = 37 * result + this.getUnitTypes();
         result = 37 * result + ( getFwdPriceReportDays() == null ? 0 : this.getFwdPriceReportDays().hashCode() );
         result = 37 * result + ( getGroupingCode() == null ? 0 : this.getGroupingCode().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode() );
         result = 37 * result + ( getCreatedTime() == null ? 0 : this.getCreatedTime().hashCode() );
         result = 37 * result + ( getCreatedProcess() == null ? 0 : this.getCreatedProcess().hashCode() );
         result = 37 * result + ( getModifyBy() == null ? 0 : this.getModifyBy().hashCode() );
         result = 37 * result + ( getModifyDate() == null ? 0 : this.getModifyDate().hashCode() );
         result = 37 * result + ( getModifyTime() == null ? 0 : this.getModifyTime().hashCode() );
         result = 37 * result + ( getModifyProcess() == null ? 0 : this.getModifyProcess().hashCode() );
         result = 37 * result + ( getPricingTime() == null ? 0 : this.getPricingTime().hashCode() );
         result = 37 * result + ( getAccountingStream() == null ? 0 : this.getAccountingStream().hashCode() );
         result = 37 * result + ( getDocumentationName() == null ? 0 : this.getDocumentationName().hashCode() );
         result = 37 * result + ( getIsinCode() == null ? 0 : this.getIsinCode().hashCode() );
         result = 37 * result + ( getNlProduct() == null ? 0 : this.getNlProduct().hashCode() );
         result = 37 * result + ( getCutOffTime() == null ? 0 : this.getCutOffTime().hashCode() );
         result = 37 * result + ( getUlFundType() == null ? 0 : this.getUlFundType().hashCode() );
         result = 37 * result + ( getMaxAllocationPercent() == null ? 0 : this.getMaxAllocationPercent().hashCode() );
         result = 37 * result + ( getAssetManager() == null ? 0 : this.getAssetManager().hashCode() );
         result = 37 * result + ( getDepositBank() == null ? 0 : this.getDepositBank().hashCode() );
         result = 37 * result + ( getCountry() == null ? 0 : this.getCountry().hashCode() );
         result = 37 * result + ( getNavEntryFee() == null ? 0 : this.getNavEntryFee().hashCode() );
         result = 37 * result + ( getNavExitFee() == null ? 0 : this.getNavExitFee().hashCode() );
         result = 37 * result + ( getRiskProfile() == null ? 0 : this.getRiskProfile().hashCode() );
         result = 37 * result + ( getRiskCurrency() == null ? 0 : this.getRiskCurrency().hashCode() );
         result = 37 * result + ( getInvestCat() == null ? 0 : this.getInvestCat().hashCode() );
         result = 37 * result + ( getInvestObjective() == null ? 0 : this.getInvestObjective().hashCode() );
         result = 37 * result + ( getAlternativeFunds() == null ? 0 : this.getAlternativeFunds().hashCode() );
         result = 37 * result + ( getRiskProfileDate() == null ? 0 : this.getRiskProfileDate().hashCode() );
         result = 37 * result + ( getNotes() == null ? 0 : this.getNotes().hashCode() );
         result = 37 * result + ( getPricingDelay() == null ? 0 : this.getPricingDelay().hashCode() );
         result = 37 * result + ( getIban() == null ? 0 : this.getIban().hashCode() );
         result = 37 * result + ( getSalesRep() == null ? 0 : this.getSalesRep().hashCode() );
         result = 37 * result + ( getInvestCashLimit() == null ? 0 : this.getInvestCashLimit().hashCode() );
         result = 37 * result + ( getPoa() == null ? 0 : this.getPoa().hashCode() );
         result = 37 * result + ( getPoaType() == null ? 0 : this.getPoaType().hashCode() );
         result = 37 * result + ( getMandateHolder() == null ? 0 : this.getMandateHolder().hashCode() );
         result = 37 * result + ( getPoaDate() == null ? 0 : this.getPoaDate().hashCode() );
         return result;
   }   


}


