package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * FundTransactionDateEntity generated by hbm2java
 */
@Entity
@Table(name = "FUND_TRANSACTION_DATES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class FundTransactionDateEntity implements java.io.Serializable {

	private String ftdId;
	@JsonIgnore
	private FundEntity fund;
	private Date date0;
	private int unitTypes;
	private Integer transactionsWaiting;
	private String fundId;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private Date createdSystemDate;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Date modifySystemDate;
	private String modifyProcess;
	@JsonIgnore
	private Set<FundTransactionEntity> fundTransactions = new HashSet<FundTransactionEntity>(0);

	@Id
	@Column(name = "FTD_ID", unique = true, nullable = false, length = 20)
	public String getFtdId() {
		return this.ftdId;
	}

	public void setFtdId(String ftdId) {
		this.ftdId = ftdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_FUNDSFDS_ID")
	@NotFound(action = NotFoundAction.IGNORE)
	public FundEntity getFund() {
		return this.fund;
	}

	public void setFund(FundEntity fund) {
		this.fund = fund;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE0", nullable = false, length = 23)
	public Date getDate0() {
		return this.date0;
	}

	public void setDate0(Date date0) {
		this.date0 = date0;
	}

	@Column(name = "UNIT_TYPES", nullable = false)
	public int getUnitTypes() {
		return this.unitTypes;
	}

	public void setUnitTypes(int unitTypes) {
		this.unitTypes = unitTypes;
	}

	@Column(name = "TRANSACTIONS_WAITING")
	public Integer getTransactionsWaiting() {
		return this.transactionsWaiting;
	}

	public void setTransactionsWaiting(Integer transactionsWaiting) {
		this.transactionsWaiting = transactionsWaiting;
	}

	@Column(name = "FUND", nullable = false, length = 8)
	public String getFundId() {
		return this.fundId;
	}

	public void setFundId(String fundId) {
		this.fundId = fundId;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_SYSTEM_DATE", length = 23)
	public Date getModifySystemDate() {
		return this.modifySystemDate;
	}

	public void setModifySystemDate(Date modifySystemDate) {
		this.modifySystemDate = modifySystemDate;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundTransactionDate")
	public Set<FundTransactionEntity> getFundTransactions() {
		return this.fundTransactions;
	}

	public void setFundTransactions(Set<FundTransactionEntity> fundTransactions) {
		this.fundTransactions = fundTransactions;
	}

}
