package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * FundHoldingEntity generated by hbm2java
 */
@Entity
@Table(name="FUND_HOLDINGS"
    
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler","createdProcess","modifyProcess","createdBy","createdDate","createdTime","modifyDate","modifyTime","modifyBy"})
public class FundHoldingEntity  implements java.io.Serializable {


     private String fdhId;
     @JsonIgnore
     private FundEntity fund;
	private String fundId;
     private BigDecimal units;
     private Integer fundType;
     private int status;
     private String createdBy;
     private Date createdDate;
     private Date createdTime;
     private String createdProcess;
     private String modifyBy;
     private Date modifyDate;
     private Date modifyTime;
     private String modifyProcess;
     private Integer holdingType;
     private Date effectiveDate;

     @Id 
    @Column(name="FDH_ID", unique=true, nullable=false, length=20)
    public String getFdhId() {
        return this.fdhId;
    }
    
    public void setFdhId(String fdhId) {
        this.fdhId = fdhId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_FUNDSFDS_ID")
	@NotFound(action=NotFoundAction.IGNORE)
    public FundEntity getFund() {
        return this.fund;
    }
    
    public void setFund(FundEntity fund) {
        this.fund = fund;
    }

    
    @Column(name="FUND", nullable=false, length=8)
	public String getFundId() {
		return this.fundId;
    }
    
	public void setFundId(String fundId) {
		this.fundId = fundId;
    }

    
    @Column(name="UNITS", precision=15, scale=6)
    public BigDecimal getUnits() {
        return this.units;
    }
    
    public void setUnits(BigDecimal units) {
        this.units = units;
    }

    
    @Column(name="FUND_TYPE")
    public Integer getFundType() {
        return this.fundType;
    }
    
    public void setFundType(Integer fundType) {
        this.fundType = fundType;
    }

    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    
    @Column(name="CREATED_PROCESS", nullable=false, length=15)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }

    
    @Column(name="MODIFY_BY", length=5)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    
    @Column(name="MODIFY_PROCESS", length=15)
    public String getModifyProcess() {
        return this.modifyProcess;
    }
    
    public void setModifyProcess(String modifyProcess) {
        this.modifyProcess = modifyProcess;
    }

    
    @Column(name="HOLDING_TYPE")
    public Integer getHoldingType() {
        return this.holdingType;
    }
    
    public void setHoldingType(Integer holdingType) {
        this.holdingType = holdingType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE", length=23)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }




}


