package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImportTaxPaidEntity generated by hbm2java
 */
@Entity
@Table(name = "IMPORT_TAX_PAID"

)
public class ImportTaxPaidEntity implements java.io.Serializable {

	private long itpId;
	private String bankDep;
	private Date valuationDate;
	private String fkPfoId;
	private String pflioNumber;
	private String securityName;
	private String pflioCcy;
	private String isinCode;
	private String issueCountry;
	private String rateCcy;
	private Date valueDate;
	private Double grossAmount;
	private Double taxAmount;

	@Id
	@Column(name = "ITP_ID", unique = true, nullable = false)
	public long getItpId() {
		return this.itpId;
	}

	public void setItpId(long itpId) {
		this.itpId = itpId;
	}

	@Column(name = "BANK_DEP", length = 10)
	public String getBankDep() {
		return this.bankDep;
	}

	public void setBankDep(String bankDep) {
		this.bankDep = bankDep;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALUATION_DATE", length = 23)
	public Date getValuationDate() {
		return this.valuationDate;
	}

	public void setValuationDate(Date valuationDate) {
		this.valuationDate = valuationDate;
	}

	@Column(name = "FK_PFO_ID", length = 35)
	public String getFkPfoId() {
		return this.fkPfoId;
	}

	public void setFkPfoId(String fkPfoId) {
		this.fkPfoId = fkPfoId;
	}

	@Column(name = "PFLIO_NUMBER", length = 20)
	public String getPflioNumber() {
		return this.pflioNumber;
	}

	public void setPflioNumber(String pflioNumber) {
		this.pflioNumber = pflioNumber;
	}

	@Column(name = "SECURITY_NAME", length = 150)
	public String getSecurityName() {
		return this.securityName;
	}

	public void setSecurityName(String securityName) {
		this.securityName = securityName;
	}

	@Column(name = "PFLIO_CCY", length = 4)
	public String getPflioCcy() {
		return this.pflioCcy;
	}

	public void setPflioCcy(String pflioCcy) {
		this.pflioCcy = pflioCcy;
	}

	@Column(name = "ISIN_CODE", length = 20)
	public String getIsinCode() {
		return this.isinCode;
	}

	public void setIsinCode(String isinCode) {
		this.isinCode = isinCode;
	}

	@Column(name = "ISSUE_COUNTRY", length = 100)
	public String getIssueCountry() {
		return this.issueCountry;
	}

	public void setIssueCountry(String issueCountry) {
		this.issueCountry = issueCountry;
	}

	@Column(name = "RATE_CCY", length = 4)
	public String getRateCcy() {
		return this.rateCcy;
	}

	public void setRateCcy(String rateCcy) {
		this.rateCcy = rateCcy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALUE_DATE", length = 23)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	@Column(name = "GROSS_AMOUNT", precision = 53, scale = 0)
	public Double getGrossAmount() {
		return this.grossAmount;
	}

	public void setGrossAmount(Double grossAmount) {
		this.grossAmount = grossAmount;
	}

	@Column(name = "TAX_AMOUNT", precision = 53, scale = 0)
	public Double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(Double taxAmount) {
		this.taxAmount = taxAmount;
	}

}
