package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsSentToEntity generated by hbm2java
 */
@Entity
@Table(name = "IS_SENT_TO"

)
public class IsSentToEntity implements java.io.Serializable {

	private IsSentToEntityId id;
	private ClientEntity client;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fkClientscliId", column = @Column(name = "FK_CLIENTSCLI_ID", nullable = false)),
			@AttributeOverride(name = "fkDocumentReqdrqId", column = @Column(name = "FK_DOCUMENT_REQDRQ_ID", nullable = false, precision = 53, scale = 0)) })
	public IsSentToEntityId getId() {
		return this.id;
	}

	public void setId(IsSentToEntityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLIENTSCLI_ID", nullable = false, insertable = false, updatable = false)
	public ClientEntity getClient() {
		return this.client;
	}

	public void setClient(ClientEntity client) {
		this.client = client;
	}

}
