package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IsSentToEntityId generated by hbm2java
 */
@Embeddable
public class IsSentToEntityId  implements java.io.Serializable {


     private int fkClientscliId;
     private double fkDocumentReqdrqId;

    public IsSentToEntityId() {
    }

    public IsSentToEntityId(int fkClientscliId, double fkDocumentReqdrqId) {
       this.fkClientscliId = fkClientscliId;
       this.fkDocumentReqdrqId = fkDocumentReqdrqId;
    }
   


    @Column(name="FK_CLIENTSCLI_ID", nullable=false)
    public int getFkClientscliId() {
        return this.fkClientscliId;
    }
    
    public void setFkClientscliId(int fkClientscliId) {
        this.fkClientscliId = fkClientscliId;
    }


    @Column(name="FK_DOCUMENT_REQDRQ_ID", nullable=false, precision=53, scale=0)
    public double getFkDocumentReqdrqId() {
        return this.fkDocumentReqdrqId;
    }
    
    public void setFkDocumentReqdrqId(double fkDocumentReqdrqId) {
        this.fkDocumentReqdrqId = fkDocumentReqdrqId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IsSentToEntityId) ) return false;
		 IsSentToEntityId castOther = ( IsSentToEntityId ) other; 
         
		 return (this.getFkClientscliId()==castOther.getFkClientscliId())
 && (this.getFkDocumentReqdrqId()==castOther.getFkDocumentReqdrqId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkClientscliId();
         result = 37 * result + (int) this.getFkDocumentReqdrqId();
         return result;
   }   


}


