package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MessageTextEntity generated by hbm2java
 */
@Entity
@Table(name = "MESSAGE_TEXT"

)
public class MessageTextEntity implements java.io.Serializable {

	private String txtId;
	private String code;
	private String type;
	private Integer language0;
	private String alphaValue;
	private String optionValue;

	@Id
	@Column(name = "TXT_ID", unique = true, nullable = false, length = 25)
	public String getTxtId() {
		return this.txtId;
	}

	public void setTxtId(String txtId) {
		this.txtId = txtId;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "TYPE", length = 3)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "LANGUAGE0")
	public Integer getLanguage0() {
		return this.language0;
	}

	public void setLanguage0(Integer language0) {
		this.language0 = language0;
	}

	@Column(name = "ALPHA_VALUE", length = 40)
	public String getAlphaValue() {
		return this.alphaValue;
	}

	public void setAlphaValue(String alphaValue) {
		this.alphaValue = alphaValue;
	}

	@Column(name = "OPTION_VALUE")
	public String getOptionValue() {
		return this.optionValue;
	}

	public void setOptionValue(String optionValue) {
		this.optionValue = optionValue;
	}

}
