package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PolicyFundInstructionEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_FUND_INSTRUCTIONS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class PolicyFundInstructionEntity implements java.io.Serializable {

	private long pfiId;
	@JsonIgnore
	private PolicyEntity policy;
	@JsonIgnore
	private TransactionEntity transaction;
	private String policyId;
	private Integer holding;
	private Integer type;
	private String fund;
	private Integer unitType;
	private Integer movementType;
	private BigDecimal movementValue;
	private String movementCcy;
	private String toFund1;
	private BigDecimal toFund1Pcg;
	private String toFund2;
	private BigDecimal toFund2Pcg;
	private String toFund3;
	private BigDecimal toFund3Pcg;
	private String toFund4;
	private BigDecimal toFund4Pcg;
	private BigDecimal switchFee;
	private String switchFeeCcy;
	private Date instructionDate;
	private int status;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private Date createdSystemDate;
	private String modifyBy;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyProcess;
	private Date modifySystemDate;
	private Integer coverage;
	private Integer toFund1Hldg;
	private Integer toFund2Hldg;
	private Integer toFund3Hldg;
	private Integer toFund4Hldg;
	private String toFund5;
	private BigDecimal toFund5Pcg;
	private Integer toFund5Hldg;
	private String toFund6;
	private BigDecimal toFund6Pcg;
	private Integer toFund6Hldg;
	private String toFund7;
	private BigDecimal toFund7Pcg;
	private Integer toFund7Hldg;
	private String toFund8;
	private BigDecimal toFund8Pcg;
	private Integer toFund8Hldg;
	private String toFund9;
	private BigDecimal toFund9Pcg;
	private Integer toFund9Hldg;
	private String toFund10;
	private BigDecimal toFund10Pcg;
	private Integer toFund10Hldg;
	private String targetPolicy;
	private Boolean switchHeader;
	private Boolean switchBasis;
	private Integer overridePenaltyType;
	private Integer overrideNavPriceBasis;
	private Set<PolicyFundInstructionDetailEntity> policyFundInstructionDetails = new HashSet<PolicyFundInstructionDetailEntity>(0);
	private Set<FundTransactionEntity> fundTransactions = new HashSet<FundTransactionEntity>(0);

	@Id
	@Column(name = "PFI_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getPfiId() {
		return this.pfiId;
	}

	public void setPfiId(long pfiId) {
		this.pfiId = pfiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_TRANSACTIONSTRN_ID")
	public TransactionEntity getTransaction() {
		return this.transaction;
	}

	public void setTransaction(TransactionEntity transaction) {
		this.transaction = transaction;
	}

	@Column(name = "POLICY", length = 14)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Column(name = "HOLDING")
	public Integer getHolding() {
		return this.holding;
	}

	public void setHolding(Integer holding) {
		this.holding = holding;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "FUND", length = 8)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Column(name = "UNIT_TYPE")
	public Integer getUnitType() {
		return this.unitType;
	}

	public void setUnitType(Integer unitType) {
		this.unitType = unitType;
	}

	@Column(name = "MOVEMENT_TYPE")
	public Integer getMovementType() {
		return this.movementType;
	}

	public void setMovementType(Integer movementType) {
		this.movementType = movementType;
	}

	@Column(name = "MOVEMENT_VALUE", precision = 15, scale = 6)
	public BigDecimal getMovementValue() {
		return this.movementValue;
	}

	public void setMovementValue(BigDecimal movementValue) {
		this.movementValue = movementValue;
	}

	@Column(name = "MOVEMENT_CCY", length = 5)
	public String getMovementCcy() {
		return this.movementCcy;
	}

	public void setMovementCcy(String movementCcy) {
		this.movementCcy = movementCcy;
	}

	@Column(name = "TO_FUND_1", length = 8)
	public String getToFund1() {
		return this.toFund1;
	}

	public void setToFund1(String toFund1) {
		this.toFund1 = toFund1;
	}

	@Column(name = "TO_FUND_1_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund1Pcg() {
		return this.toFund1Pcg;
	}

	public void setToFund1Pcg(BigDecimal toFund1Pcg) {
		this.toFund1Pcg = toFund1Pcg;
	}

	@Column(name = "TO_FUND_2", length = 8)
	public String getToFund2() {
		return this.toFund2;
	}

	public void setToFund2(String toFund2) {
		this.toFund2 = toFund2;
	}

	@Column(name = "TO_FUND_2_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund2Pcg() {
		return this.toFund2Pcg;
	}

	public void setToFund2Pcg(BigDecimal toFund2Pcg) {
		this.toFund2Pcg = toFund2Pcg;
	}

	@Column(name = "TO_FUND_3", length = 8)
	public String getToFund3() {
		return this.toFund3;
	}

	public void setToFund3(String toFund3) {
		this.toFund3 = toFund3;
	}

	@Column(name = "TO_FUND_3_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund3Pcg() {
		return this.toFund3Pcg;
	}

	public void setToFund3Pcg(BigDecimal toFund3Pcg) {
		this.toFund3Pcg = toFund3Pcg;
	}

	@Column(name = "TO_FUND_4", length = 8)
	public String getToFund4() {
		return this.toFund4;
	}

	public void setToFund4(String toFund4) {
		this.toFund4 = toFund4;
	}

	@Column(name = "TO_FUND_4_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund4Pcg() {
		return this.toFund4Pcg;
	}

	public void setToFund4Pcg(BigDecimal toFund4Pcg) {
		this.toFund4Pcg = toFund4Pcg;
	}

	@Column(name = "SWITCH_FEE", precision = 12)
	public BigDecimal getSwitchFee() {
		return this.switchFee;
	}

	public void setSwitchFee(BigDecimal switchFee) {
		this.switchFee = switchFee;
	}

	@Column(name = "SWITCH_FEE_CCY", length = 5)
	public String getSwitchFeeCcy() {
		return this.switchFeeCcy;
	}

	public void setSwitchFeeCcy(String switchFeeCcy) {
		this.switchFeeCcy = switchFeeCcy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSTRUCTION_DATE", length = 23)
	public Date getInstructionDate() {
		return this.instructionDate;
	}

	public void setInstructionDate(Date instructionDate) {
		this.instructionDate = instructionDate;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", nullable = false, length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_SYSTEM_DATE", length = 23)
	public Date getModifySystemDate() {
		return this.modifySystemDate;
	}

	public void setModifySystemDate(Date modifySystemDate) {
		this.modifySystemDate = modifySystemDate;
	}

	@Column(name = "COVERAGE")
	public Integer getCoverage() {
		return this.coverage;
	}

	public void setCoverage(Integer coverage) {
		this.coverage = coverage;
	}

	@Column(name = "TO_FUND_1_HLDG")
	public Integer getToFund1Hldg() {
		return this.toFund1Hldg;
	}

	public void setToFund1Hldg(Integer toFund1Hldg) {
		this.toFund1Hldg = toFund1Hldg;
	}

	@Column(name = "TO_FUND_2_HLDG")
	public Integer getToFund2Hldg() {
		return this.toFund2Hldg;
	}

	public void setToFund2Hldg(Integer toFund2Hldg) {
		this.toFund2Hldg = toFund2Hldg;
	}

	@Column(name = "TO_FUND_3_HLDG")
	public Integer getToFund3Hldg() {
		return this.toFund3Hldg;
	}

	public void setToFund3Hldg(Integer toFund3Hldg) {
		this.toFund3Hldg = toFund3Hldg;
	}

	@Column(name = "TO_FUND_4_HLDG")
	public Integer getToFund4Hldg() {
		return this.toFund4Hldg;
	}

	public void setToFund4Hldg(Integer toFund4Hldg) {
		this.toFund4Hldg = toFund4Hldg;
	}

	@Column(name = "TO_FUND_5", length = 8)
	public String getToFund5() {
		return this.toFund5;
	}

	public void setToFund5(String toFund5) {
		this.toFund5 = toFund5;
	}

	@Column(name = "TO_FUND_5_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund5Pcg() {
		return this.toFund5Pcg;
	}

	public void setToFund5Pcg(BigDecimal toFund5Pcg) {
		this.toFund5Pcg = toFund5Pcg;
	}

	@Column(name = "TO_FUND_5_HLDG")
	public Integer getToFund5Hldg() {
		return this.toFund5Hldg;
	}

	public void setToFund5Hldg(Integer toFund5Hldg) {
		this.toFund5Hldg = toFund5Hldg;
	}

	@Column(name = "TO_FUND_6", length = 8)
	public String getToFund6() {
		return this.toFund6;
	}

	public void setToFund6(String toFund6) {
		this.toFund6 = toFund6;
	}

	@Column(name = "TO_FUND_6_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund6Pcg() {
		return this.toFund6Pcg;
	}

	public void setToFund6Pcg(BigDecimal toFund6Pcg) {
		this.toFund6Pcg = toFund6Pcg;
	}

	@Column(name = "TO_FUND_6_HLDG")
	public Integer getToFund6Hldg() {
		return this.toFund6Hldg;
	}

	public void setToFund6Hldg(Integer toFund6Hldg) {
		this.toFund6Hldg = toFund6Hldg;
	}

	@Column(name = "TO_FUND_7", length = 8)
	public String getToFund7() {
		return this.toFund7;
	}

	public void setToFund7(String toFund7) {
		this.toFund7 = toFund7;
	}

	@Column(name = "TO_FUND_7_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund7Pcg() {
		return this.toFund7Pcg;
	}

	public void setToFund7Pcg(BigDecimal toFund7Pcg) {
		this.toFund7Pcg = toFund7Pcg;
	}

	@Column(name = "TO_FUND_7_HLDG")
	public Integer getToFund7Hldg() {
		return this.toFund7Hldg;
	}

	public void setToFund7Hldg(Integer toFund7Hldg) {
		this.toFund7Hldg = toFund7Hldg;
	}

	@Column(name = "TO_FUND_8", length = 8)
	public String getToFund8() {
		return this.toFund8;
	}

	public void setToFund8(String toFund8) {
		this.toFund8 = toFund8;
	}

	@Column(name = "TO_FUND_8_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund8Pcg() {
		return this.toFund8Pcg;
	}

	public void setToFund8Pcg(BigDecimal toFund8Pcg) {
		this.toFund8Pcg = toFund8Pcg;
	}

	@Column(name = "TO_FUND_8_HLDG")
	public Integer getToFund8Hldg() {
		return this.toFund8Hldg;
	}

	public void setToFund8Hldg(Integer toFund8Hldg) {
		this.toFund8Hldg = toFund8Hldg;
	}

	@Column(name = "TO_FUND_9", length = 8)
	public String getToFund9() {
		return this.toFund9;
	}

	public void setToFund9(String toFund9) {
		this.toFund9 = toFund9;
	}

	@Column(name = "TO_FUND_9_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund9Pcg() {
		return this.toFund9Pcg;
	}

	public void setToFund9Pcg(BigDecimal toFund9Pcg) {
		this.toFund9Pcg = toFund9Pcg;
	}

	@Column(name = "TO_FUND_9_HLDG")
	public Integer getToFund9Hldg() {
		return this.toFund9Hldg;
	}

	public void setToFund9Hldg(Integer toFund9Hldg) {
		this.toFund9Hldg = toFund9Hldg;
	}

	@Column(name = "TO_FUND_10", length = 8)
	public String getToFund10() {
		return this.toFund10;
	}

	public void setToFund10(String toFund10) {
		this.toFund10 = toFund10;
	}

	@Column(name = "TO_FUND_10_PCG", precision = 10, scale = 6)
	public BigDecimal getToFund10Pcg() {
		return this.toFund10Pcg;
	}

	public void setToFund10Pcg(BigDecimal toFund10Pcg) {
		this.toFund10Pcg = toFund10Pcg;
	}

	@Column(name = "TO_FUND_10_HLDG")
	public Integer getToFund10Hldg() {
		return this.toFund10Hldg;
	}

	public void setToFund10Hldg(Integer toFund10Hldg) {
		this.toFund10Hldg = toFund10Hldg;
	}

	@Column(name = "TARGET_POLICY", length = 16)
	public String getTargetPolicy() {
		return this.targetPolicy;
	}

	public void setTargetPolicy(String targetPolicy) {
		this.targetPolicy = targetPolicy;
	}

	@Column(name = "SWITCH_HEADER", precision = 1, scale = 0)
	public Boolean getSwitchHeader() {
		return this.switchHeader;
	}

	public void setSwitchHeader(Boolean switchHeader) {
		this.switchHeader = switchHeader;
	}

	@Column(name = "SWITCH_BASIS", precision = 1, scale = 0)
	public Boolean getSwitchBasis() {
		return this.switchBasis;
	}

	public void setSwitchBasis(Boolean switchBasis) {
		this.switchBasis = switchBasis;
	}

	@Column(name = "OVERRIDE_PENALTY_TYPE")
	public Integer getOverridePenaltyType() {
		return this.overridePenaltyType;
	}

	public void setOverridePenaltyType(Integer overridePenaltyType) {
		this.overridePenaltyType = overridePenaltyType;
	}

	@Column(name = "OVERRIDE_NAV_PRICE_BASIS", precision = 3, scale = 0)
	public Integer getOverrideNavPriceBasis() {
		return this.overrideNavPriceBasis;
	}

	public void setOverrideNavPriceBasis(Integer overrideNavPriceBasis) {
		this.overrideNavPriceBasis = overrideNavPriceBasis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyFundInstruction")
	public Set<PolicyFundInstructionDetailEntity> getPolicyFundInstructionDetails() {
		return this.policyFundInstructionDetails;
	}

	public void setPolicyFundInstructionDetails(Set<PolicyFundInstructionDetailEntity> policyFundInstructionDetails) {
		this.policyFundInstructionDetails = policyFundInstructionDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyFundInstruction")
	public Set<FundTransactionEntity> getFundTransactions() {
		return this.fundTransactions;
	}

	public void setFundTransactions(Set<FundTransactionEntity> fundTransactions) {
		this.fundTransactions = fundTransactions;
	}

}
