package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PolicyCommissionScheduleEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_COMMISSION_SCHEDULES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class PolicyCommissionScheduleEntity implements java.io.Serializable {

	private String pcsId;
	@JsonIgnore
	private PolicyCommissionEntity policyCommission;
	private BigDecimal clawback;
	private BigDecimal s12;
	private BigDecimal s11;
	private BigDecimal s10;
	private BigDecimal s9;
	private BigDecimal s8;
	private BigDecimal s7;
	private BigDecimal s6;
	private BigDecimal s5;
	private BigDecimal s4;
	private BigDecimal s3;
	private BigDecimal s2;
	private BigDecimal s1;
	private String policy;
	private int coverage;
	private Integer year0;
	private int type;
	private int set0;
	private String agent;
	private BigDecimal p1;
	private BigDecimal p2;
	private BigDecimal p3;
	private BigDecimal p4;
	private BigDecimal p5;
	private BigDecimal p6;
	private BigDecimal p7;
	private BigDecimal p8;
	private BigDecimal p9;
	private BigDecimal p10;
	private BigDecimal p11;
	private BigDecimal p12;
	private BigDecimal e1;
	private BigDecimal e2;
	private BigDecimal e3;
	private BigDecimal e4;
	private BigDecimal e5;
	private BigDecimal e6;
	private BigDecimal e7;
	private BigDecimal e8;
	private BigDecimal e9;
	private BigDecimal e10;
	private BigDecimal e11;
	private BigDecimal e12;
	private Integer periodPaid;
	private String currency;
	private int status;
	private String createdProcess;
	private String modifyProcess;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;

	@Id
	@Column(name = "PCS_ID", unique = true, nullable = false, length = 30)
	public String getPcsId() {
		return this.pcsId;
	}

	public void setPcsId(String pcsId) {
		this.pcsId = pcsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICY_COMMIPCM_ID")
	public PolicyCommissionEntity getPolicyCommission() {
		return this.policyCommission;
	}

	public void setPolicyCommission(PolicyCommissionEntity policyCommission) {
		this.policyCommission = policyCommission;
	}

	@Column(name = "CLAWBACK", precision = 15)
	public BigDecimal getClawback() {
		return this.clawback;
	}

	public void setClawback(BigDecimal clawback) {
		this.clawback = clawback;
	}

	@Column(name = "S12", precision = 10)
	public BigDecimal getS12() {
		return this.s12;
	}

	public void setS12(BigDecimal s12) {
		this.s12 = s12;
	}

	@Column(name = "S11", precision = 10)
	public BigDecimal getS11() {
		return this.s11;
	}

	public void setS11(BigDecimal s11) {
		this.s11 = s11;
	}

	@Column(name = "S10", precision = 10)
	public BigDecimal getS10() {
		return this.s10;
	}

	public void setS10(BigDecimal s10) {
		this.s10 = s10;
	}

	@Column(name = "S9", precision = 10)
	public BigDecimal getS9() {
		return this.s9;
	}

	public void setS9(BigDecimal s9) {
		this.s9 = s9;
	}

	@Column(name = "S8", precision = 10)
	public BigDecimal getS8() {
		return this.s8;
	}

	public void setS8(BigDecimal s8) {
		this.s8 = s8;
	}

	@Column(name = "S7", precision = 10)
	public BigDecimal getS7() {
		return this.s7;
	}

	public void setS7(BigDecimal s7) {
		this.s7 = s7;
	}

	@Column(name = "S6", precision = 10)
	public BigDecimal getS6() {
		return this.s6;
	}

	public void setS6(BigDecimal s6) {
		this.s6 = s6;
	}

	@Column(name = "S5", precision = 10)
	public BigDecimal getS5() {
		return this.s5;
	}

	public void setS5(BigDecimal s5) {
		this.s5 = s5;
	}

	@Column(name = "S4", precision = 10)
	public BigDecimal getS4() {
		return this.s4;
	}

	public void setS4(BigDecimal s4) {
		this.s4 = s4;
	}

	@Column(name = "S3", precision = 10)
	public BigDecimal getS3() {
		return this.s3;
	}

	public void setS3(BigDecimal s3) {
		this.s3 = s3;
	}

	@Column(name = "S2", precision = 10)
	public BigDecimal getS2() {
		return this.s2;
	}

	public void setS2(BigDecimal s2) {
		this.s2 = s2;
	}

	@Column(name = "S1", precision = 10)
	public BigDecimal getS1() {
		return this.s1;
	}

	public void setS1(BigDecimal s1) {
		this.s1 = s1;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "YEAR0")
	public Integer getYear0() {
		return this.year0;
	}

	public void setYear0(Integer year0) {
		this.year0 = year0;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "SET0", nullable = false)
	public int getSet0() {
		return this.set0;
	}

	public void setSet0(int set0) {
		this.set0 = set0;
	}

	@Column(name = "AGENT", length = 8)
	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	@Column(name = "P1", precision = 12)
	public BigDecimal getP1() {
		return this.p1;
	}

	public void setP1(BigDecimal p1) {
		this.p1 = p1;
	}

	@Column(name = "P2", precision = 12)
	public BigDecimal getP2() {
		return this.p2;
	}

	public void setP2(BigDecimal p2) {
		this.p2 = p2;
	}

	@Column(name = "P3", precision = 12)
	public BigDecimal getP3() {
		return this.p3;
	}

	public void setP3(BigDecimal p3) {
		this.p3 = p3;
	}

	@Column(name = "P4", precision = 12)
	public BigDecimal getP4() {
		return this.p4;
	}

	public void setP4(BigDecimal p4) {
		this.p4 = p4;
	}

	@Column(name = "P5", precision = 12)
	public BigDecimal getP5() {
		return this.p5;
	}

	public void setP5(BigDecimal p5) {
		this.p5 = p5;
	}

	@Column(name = "P6", precision = 12)
	public BigDecimal getP6() {
		return this.p6;
	}

	public void setP6(BigDecimal p6) {
		this.p6 = p6;
	}

	@Column(name = "P7", precision = 12)
	public BigDecimal getP7() {
		return this.p7;
	}

	public void setP7(BigDecimal p7) {
		this.p7 = p7;
	}

	@Column(name = "P8", precision = 12)
	public BigDecimal getP8() {
		return this.p8;
	}

	public void setP8(BigDecimal p8) {
		this.p8 = p8;
	}

	@Column(name = "P9", precision = 12)
	public BigDecimal getP9() {
		return this.p9;
	}

	public void setP9(BigDecimal p9) {
		this.p9 = p9;
	}

	@Column(name = "P10", precision = 12)
	public BigDecimal getP10() {
		return this.p10;
	}

	public void setP10(BigDecimal p10) {
		this.p10 = p10;
	}

	@Column(name = "P11", precision = 12)
	public BigDecimal getP11() {
		return this.p11;
	}

	public void setP11(BigDecimal p11) {
		this.p11 = p11;
	}

	@Column(name = "P12", precision = 12)
	public BigDecimal getP12() {
		return this.p12;
	}

	public void setP12(BigDecimal p12) {
		this.p12 = p12;
	}

	@Column(name = "E1", precision = 12)
	public BigDecimal getE1() {
		return this.e1;
	}

	public void setE1(BigDecimal e1) {
		this.e1 = e1;
	}

	@Column(name = "E2", precision = 12)
	public BigDecimal getE2() {
		return this.e2;
	}

	public void setE2(BigDecimal e2) {
		this.e2 = e2;
	}

	@Column(name = "E3", precision = 12)
	public BigDecimal getE3() {
		return this.e3;
	}

	public void setE3(BigDecimal e3) {
		this.e3 = e3;
	}

	@Column(name = "E4", precision = 12)
	public BigDecimal getE4() {
		return this.e4;
	}

	public void setE4(BigDecimal e4) {
		this.e4 = e4;
	}

	@Column(name = "E5", precision = 12)
	public BigDecimal getE5() {
		return this.e5;
	}

	public void setE5(BigDecimal e5) {
		this.e5 = e5;
	}

	@Column(name = "E6", precision = 12)
	public BigDecimal getE6() {
		return this.e6;
	}

	public void setE6(BigDecimal e6) {
		this.e6 = e6;
	}

	@Column(name = "E7", precision = 12)
	public BigDecimal getE7() {
		return this.e7;
	}

	public void setE7(BigDecimal e7) {
		this.e7 = e7;
	}

	@Column(name = "E8", precision = 12)
	public BigDecimal getE8() {
		return this.e8;
	}

	public void setE8(BigDecimal e8) {
		this.e8 = e8;
	}

	@Column(name = "E9", precision = 12)
	public BigDecimal getE9() {
		return this.e9;
	}

	public void setE9(BigDecimal e9) {
		this.e9 = e9;
	}

	@Column(name = "E10", precision = 12)
	public BigDecimal getE10() {
		return this.e10;
	}

	public void setE10(BigDecimal e10) {
		this.e10 = e10;
	}

	@Column(name = "E11", precision = 12)
	public BigDecimal getE11() {
		return this.e11;
	}

	public void setE11(BigDecimal e11) {
		this.e11 = e11;
	}

	@Column(name = "E12", precision = 12)
	public BigDecimal getE12() {
		return this.e12;
	}

	public void setE12(BigDecimal e12) {
		this.e12 = e12;
	}

	@Column(name = "PERIOD_PAID")
	public Integer getPeriodPaid() {
		return this.periodPaid;
	}

	public void setPeriodPaid(Integer periodPaid) {
		this.periodPaid = periodPaid;
	}

	@Column(name = "CURRENCY", length = 4)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
