package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyRegularPaymentEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_REGULAR_PAYMENTS"

)
public class PolicyRegularPaymentEntity implements java.io.Serializable {

	private String prpId;
	private PolicyEntity policy;
	private String policyId;
	private int coverage;
	private String currency;
	private String createdBy;
	private String createdProcess;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Integer frequency;
	private Date dateOfFirstPayment;
	private Date dateOfLastPayment;
	private Date dateOfMostRecentPayment;
	private Integer status;
	private Integer basis;
	private BigDecimal amount;
	private Integer amountBasis;
	private Integer fundedCoverage;
	private String fundedPolicy;
	private Integer type;
	private Integer paymentType;

	@Id
	@Column(name = "PRP_ID", unique = true, nullable = false, length = 18)
	public String getPrpId() {
		return this.prpId;
	}

	public void setPrpId(String prpId) {
		this.prpId = prpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "CURRENCY", length = 5)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "FREQUENCY")
	public Integer getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_FIRST_PAYMENT", length = 23)
	public Date getDateOfFirstPayment() {
		return this.dateOfFirstPayment;
	}

	public void setDateOfFirstPayment(Date dateOfFirstPayment) {
		this.dateOfFirstPayment = dateOfFirstPayment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_LAST_PAYMENT", length = 23)
	public Date getDateOfLastPayment() {
		return this.dateOfLastPayment;
	}

	public void setDateOfLastPayment(Date dateOfLastPayment) {
		this.dateOfLastPayment = dateOfLastPayment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_MOST_RECENT_PAYMENT", length = 23)
	public Date getDateOfMostRecentPayment() {
		return this.dateOfMostRecentPayment;
	}

	public void setDateOfMostRecentPayment(Date dateOfMostRecentPayment) {
		this.dateOfMostRecentPayment = dateOfMostRecentPayment;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "BASIS")
	public Integer getBasis() {
		return this.basis;
	}

	public void setBasis(Integer basis) {
		this.basis = basis;
	}

	@Column(name = "AMOUNT", precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "AMOUNT_BASIS")
	public Integer getAmountBasis() {
		return this.amountBasis;
	}

	public void setAmountBasis(Integer amountBasis) {
		this.amountBasis = amountBasis;
	}

	@Column(name = "FUNDED_COVERAGE")
	public Integer getFundedCoverage() {
		return this.fundedCoverage;
	}

	public void setFundedCoverage(Integer fundedCoverage) {
		this.fundedCoverage = fundedCoverage;
	}

	@Column(name = "FUNDED_POLICY", length = 14)
	public String getFundedPolicy() {
		return this.fundedPolicy;
	}

	public void setFundedPolicy(String fundedPolicy) {
		this.fundedPolicy = fundedPolicy;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "PAYMENT_TYPE")
	public Integer getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(Integer paymentType) {
		this.paymentType = paymentType;
	}

}
