package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductEntity generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_SPECIFICITIES"

)
public class ProductSpecificitiesEntity implements java.io.Serializable {

	private static final long serialVersionUID = 7013899612624810913L;
	private String prdId;
	private String generalConditions;
	private Date startDate;
	private Date endDate;

	@Id
	@Column(name = "PRD_ID", unique = true, nullable = false, length = 12)
	public String getPrdId() {
		return this.prdId;
	}

	public void setPrdId(String prdId) {
		this.prdId = prdId;
	}

	@Column(name = "GENERAL_CONDITIONS")
	public String getGeneralConditions() {
		return generalConditions;
	}

	public void setGeneralConditions(String generalConditions) {
		this.generalConditions = generalConditions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DT")
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DT")
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
