package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QueuedTaskEntity generated by hbm2java
 */
@Entity
@Table(name = "QUEUED_TASKS"

)
public class QueuedTaskEntity implements java.io.Serializable {

	private long qtaId;
	private QueuedTaskDateEntity queuedTaskDate;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdSdate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifySdate;
	private Date modifyTime;
	private String modifyProcess;
	private Date runDate;
	private Date afterTime;
	private int jobBasis;
	private Date startDate;
	private Date startSdate;
	private Date startTime;
	private Date endDate;
	private Date endSdate;
	private Date endTime;
	private int job;
	private Long suppl1No;
	private String suppl1Text;
	private Date suppl1Date;
	private Long taskUpdates;
	private Set<BatchErrorEntity> batchErrors = new HashSet<BatchErrorEntity>(0);

	@Id
	@Column(name = "QTA_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getQtaId() {
		return this.qtaId;
	}

	public void setQtaId(long qtaId) {
		this.qtaId = qtaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_QUEUED_TASK_QTD_ID")
	public QueuedTaskDateEntity getQueuedTaskDate() {
		return this.queuedTaskDate;
	}

	public void setQueuedTaskDate(QueuedTaskDateEntity queuedTaskDate) {
		this.queuedTaskDate = queuedTaskDate;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SDATE", nullable = false, length = 23)
	public Date getCreatedSdate() {
		return this.createdSdate;
	}

	public void setCreatedSdate(Date createdSdate) {
		this.createdSdate = createdSdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_SDATE", length = 23)
	public Date getModifySdate() {
		return this.modifySdate;
	}

	public void setModifySdate(Date modifySdate) {
		this.modifySdate = modifySdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RUN_DATE", nullable = false, length = 23)
	public Date getRunDate() {
		return this.runDate;
	}

	public void setRunDate(Date runDate) {
		this.runDate = runDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AFTER_TIME", length = 23)
	public Date getAfterTime() {
		return this.afterTime;
	}

	public void setAfterTime(Date afterTime) {
		this.afterTime = afterTime;
	}

	@Column(name = "JOB_BASIS", nullable = false)
	public int getJobBasis() {
		return this.jobBasis;
	}

	public void setJobBasis(int jobBasis) {
		this.jobBasis = jobBasis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_SDATE", length = 23)
	public Date getStartSdate() {
		return this.startSdate;
	}

	public void setStartSdate(Date startSdate) {
		this.startSdate = startSdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_TIME", length = 23)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_SDATE", length = 23)
	public Date getEndSdate() {
		return this.endSdate;
	}

	public void setEndSdate(Date endSdate) {
		this.endSdate = endSdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME", length = 23)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "JOB", nullable = false)
	public int getJob() {
		return this.job;
	}

	public void setJob(int job) {
		this.job = job;
	}

	@Column(name = "SUPPL1_NO", precision = 10, scale = 0)
	public Long getSuppl1No() {
		return this.suppl1No;
	}

	public void setSuppl1No(Long suppl1No) {
		this.suppl1No = suppl1No;
	}

	@Column(name = "SUPPL1_TEXT", length = 20)
	public String getSuppl1Text() {
		return this.suppl1Text;
	}

	public void setSuppl1Text(String suppl1Text) {
		this.suppl1Text = suppl1Text;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUPPL1_DATE", length = 23)
	public Date getSuppl1Date() {
		return this.suppl1Date;
	}

	public void setSuppl1Date(Date suppl1Date) {
		this.suppl1Date = suppl1Date;
	}

	@Column(name = "TASK_UPDATES", precision = 10, scale = 0)
	public Long getTaskUpdates() {
		return this.taskUpdates;
	}

	public void setTaskUpdates(Long taskUpdates) {
		this.taskUpdates = taskUpdates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queuedTask")
	public Set<BatchErrorEntity> getBatchErrors() {
		return this.batchErrors;
	}

	public void setBatchErrors(Set<BatchErrorEntity> batchErrors) {
		this.batchErrors = batchErrors;
	}

}
