package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RateEntity generated by hbm2java
 */
@Entity
@Table(name = "RATES"

)
public class RateEntity implements java.io.Serializable {

	private long ratId;
	private RateDefinitionEntity rateDefinition;
	private Integer series;
	private String value1;
	private String value6;
	private String value8;
	private String value7;
	private String value2;
	private String value3;
	private String value4;
	private String value5;
	private String value9;
	private String value10;
	private String rateValueAlpha;
	private BigDecimal rateValueNumber;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Long rateDefinitionId;

	@Id
	@Column(name = "RAT_ID", unique = true, nullable = false, precision = 14, scale = 0)
	public long getRatId() {
		return this.ratId;
	}

	public void setRatId(long ratId) {
		this.ratId = ratId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_RATE_DEFINITRDF_ID")
	public RateDefinitionEntity getRateDefinition() {
		return this.rateDefinition;
	}

	public void setRateDefinition(RateDefinitionEntity rateDefinition) {
		this.rateDefinition = rateDefinition;
	}

	@Column(name = "SERIES")
	public Integer getSeries() {
		return this.series;
	}

	public void setSeries(Integer series) {
		this.series = series;
	}

	@Column(name = "VALUE_1", length = 20)
	public String getValue1() {
		return this.value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	@Column(name = "VALUE_6", length = 20)
	public String getValue6() {
		return this.value6;
	}

	public void setValue6(String value6) {
		this.value6 = value6;
	}

	@Column(name = "VALUE_8", length = 20)
	public String getValue8() {
		return this.value8;
	}

	public void setValue8(String value8) {
		this.value8 = value8;
	}

	@Column(name = "VALUE_7", length = 20)
	public String getValue7() {
		return this.value7;
	}

	public void setValue7(String value7) {
		this.value7 = value7;
	}

	@Column(name = "VALUE_2", length = 20)
	public String getValue2() {
		return this.value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	@Column(name = "VALUE_3", length = 20)
	public String getValue3() {
		return this.value3;
	}

	public void setValue3(String value3) {
		this.value3 = value3;
	}

	@Column(name = "VALUE_4", length = 20)
	public String getValue4() {
		return this.value4;
	}

	public void setValue4(String value4) {
		this.value4 = value4;
	}

	@Column(name = "VALUE_5", length = 20)
	public String getValue5() {
		return this.value5;
	}

	public void setValue5(String value5) {
		this.value5 = value5;
	}

	@Column(name = "VALUE_9", length = 20)
	public String getValue9() {
		return this.value9;
	}

	public void setValue9(String value9) {
		this.value9 = value9;
	}

	@Column(name = "VALUE_10", length = 20)
	public String getValue10() {
		return this.value10;
	}

	public void setValue10(String value10) {
		this.value10 = value10;
	}

	@Column(name = "RATE_VALUE_ALPHA", length = 100)
	public String getRateValueAlpha() {
		return this.rateValueAlpha;
	}

	public void setRateValueAlpha(String rateValueAlpha) {
		this.rateValueAlpha = rateValueAlpha;
	}

	@Column(name = "RATE_VALUE_NUMBER", precision = 15, scale = 8)
	public BigDecimal getRateValueNumber() {
		return this.rateValueNumber;
	}

	public void setRateValueNumber(BigDecimal rateValueNumber) {
		this.rateValueNumber = rateValueNumber;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "RATE_DEFINITION", precision = 12, scale = 0)
	public Long getRateDefinitionId() {
		return this.rateDefinitionId;
	}

	public void setRateDefinitionId(Long rateDefinitionId) {
		this.rateDefinitionId = rateDefinitionId;
	}

}
