package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RateAxiEntity generated by hbm2java
 */
@Entity
@Table(name = "RATE_AXIS"

)
public class RateAxiEntity implements java.io.Serializable {

	private long raxId;
	private Integer r1;
	private Integer r2;
	private Integer r3;
	private Integer r4;
	private Integer r5;
	private Integer r6;
	private Integer r7;
	private Integer r8;
	private Integer r9;
	private Integer r10;
	private Integer r11;
	private Integer r12;
	private Integer r13;
	private Integer r14;
	private Integer r15;
	private Integer r16;
	private Integer r17;
	private Integer r18;
	private Integer r19;
	private Integer r20;
	private String optionSet;
	private Integer decPlaces;
	private int fieldType;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private String details;
	private Integer banding;
	private Integer interpolation;

	@Id
	@Column(name = "RAX_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getRaxId() {
		return this.raxId;
	}

	public void setRaxId(long raxId) {
		this.raxId = raxId;
	}

	@Column(name = "R1")
	public Integer getR1() {
		return this.r1;
	}

	public void setR1(Integer r1) {
		this.r1 = r1;
	}

	@Column(name = "R2")
	public Integer getR2() {
		return this.r2;
	}

	public void setR2(Integer r2) {
		this.r2 = r2;
	}

	@Column(name = "R3")
	public Integer getR3() {
		return this.r3;
	}

	public void setR3(Integer r3) {
		this.r3 = r3;
	}

	@Column(name = "R4")
	public Integer getR4() {
		return this.r4;
	}

	public void setR4(Integer r4) {
		this.r4 = r4;
	}

	@Column(name = "R5")
	public Integer getR5() {
		return this.r5;
	}

	public void setR5(Integer r5) {
		this.r5 = r5;
	}

	@Column(name = "R6")
	public Integer getR6() {
		return this.r6;
	}

	public void setR6(Integer r6) {
		this.r6 = r6;
	}

	@Column(name = "R7")
	public Integer getR7() {
		return this.r7;
	}

	public void setR7(Integer r7) {
		this.r7 = r7;
	}

	@Column(name = "R8")
	public Integer getR8() {
		return this.r8;
	}

	public void setR8(Integer r8) {
		this.r8 = r8;
	}

	@Column(name = "R9")
	public Integer getR9() {
		return this.r9;
	}

	public void setR9(Integer r9) {
		this.r9 = r9;
	}

	@Column(name = "R10")
	public Integer getR10() {
		return this.r10;
	}

	public void setR10(Integer r10) {
		this.r10 = r10;
	}

	@Column(name = "R11")
	public Integer getR11() {
		return this.r11;
	}

	public void setR11(Integer r11) {
		this.r11 = r11;
	}

	@Column(name = "R12")
	public Integer getR12() {
		return this.r12;
	}

	public void setR12(Integer r12) {
		this.r12 = r12;
	}

	@Column(name = "R13")
	public Integer getR13() {
		return this.r13;
	}

	public void setR13(Integer r13) {
		this.r13 = r13;
	}

	@Column(name = "R14")
	public Integer getR14() {
		return this.r14;
	}

	public void setR14(Integer r14) {
		this.r14 = r14;
	}

	@Column(name = "R15")
	public Integer getR15() {
		return this.r15;
	}

	public void setR15(Integer r15) {
		this.r15 = r15;
	}

	@Column(name = "R16")
	public Integer getR16() {
		return this.r16;
	}

	public void setR16(Integer r16) {
		this.r16 = r16;
	}

	@Column(name = "R17")
	public Integer getR17() {
		return this.r17;
	}

	public void setR17(Integer r17) {
		this.r17 = r17;
	}

	@Column(name = "R18")
	public Integer getR18() {
		return this.r18;
	}

	public void setR18(Integer r18) {
		this.r18 = r18;
	}

	@Column(name = "R19")
	public Integer getR19() {
		return this.r19;
	}

	public void setR19(Integer r19) {
		this.r19 = r19;
	}

	@Column(name = "R20")
	public Integer getR20() {
		return this.r20;
	}

	public void setR20(Integer r20) {
		this.r20 = r20;
	}

	@Column(name = "OPTION_SET", length = 20)
	public String getOptionSet() {
		return this.optionSet;
	}

	public void setOptionSet(String optionSet) {
		this.optionSet = optionSet;
	}

	@Column(name = "DEC_PLACES")
	public Integer getDecPlaces() {
		return this.decPlaces;
	}

	public void setDecPlaces(Integer decPlaces) {
		this.decPlaces = decPlaces;
	}

	@Column(name = "FIELD_TYPE", nullable = false)
	public int getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(int fieldType) {
		this.fieldType = fieldType;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "DETAILS", nullable = false, length = 30)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "BANDING")
	public Integer getBanding() {
		return this.banding;
	}

	public void setBanding(Integer banding) {
		this.banding = banding;
	}

	@Column(name = "INTERPOLATION")
	public Integer getInterpolation() {
		return this.interpolation;
	}

	public void setInterpolation(Integer interpolation) {
		this.interpolation = interpolation;
	}

}
