package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RateDefinitionEntity generated by hbm2java
 */
@Entity
@Table(name = "RATE_DEFINITIONS"

)
public class RateDefinitionEntity implements java.io.Serializable {

	private long rdfId;
	private String optionSet;
	private Long previousId;
	private String mtype1;
	private String mtype2;
	private String mtype3;
	private String mtype4;
	private String mtype5;
	private String mtype6;
	private String mtype7;
	private String mtype8;
	private String mtype9;
	private String mtype10;
	private int rateValues;
	private Integer series;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String details;
	private int type;
	private String shortId;
	private Date dateValidFrom;
	private int rateFieldType;
	private Integer ptype1;
	private Integer ptype2;
	private Integer ptype3;
	private Integer ptype4;
	private Integer ptype5;
	private Integer ptype6;
	private Integer ptype7;
	private Integer ptype8;
	private Integer ptype9;
	private Integer ptype10;
	private Date dateValidTo;
	private Set<RateEntity> rates = new HashSet<RateEntity>(0);
	private Set<RateBandingEntity> rateBandings = new HashSet<RateBandingEntity>(0);

	@Id
	@Column(name = "RDF_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getRdfId() {
		return this.rdfId;
	}

	public void setRdfId(long rdfId) {
		this.rdfId = rdfId;
	}

	@Column(name = "OPTION_SET", length = 20)
	public String getOptionSet() {
		return this.optionSet;
	}

	public void setOptionSet(String optionSet) {
		this.optionSet = optionSet;
	}

	@Column(name = "PREVIOUS_ID", precision = 15, scale = 0)
	public Long getPreviousId() {
		return this.previousId;
	}

	public void setPreviousId(Long previousId) {
		this.previousId = previousId;
	}

	@Column(name = "MTYPE_1", length = 2)
	public String getMtype1() {
		return this.mtype1;
	}

	public void setMtype1(String mtype1) {
		this.mtype1 = mtype1;
	}

	@Column(name = "MTYPE_2", length = 2)
	public String getMtype2() {
		return this.mtype2;
	}

	public void setMtype2(String mtype2) {
		this.mtype2 = mtype2;
	}

	@Column(name = "MTYPE_3", length = 2)
	public String getMtype3() {
		return this.mtype3;
	}

	public void setMtype3(String mtype3) {
		this.mtype3 = mtype3;
	}

	@Column(name = "MTYPE_4", length = 2)
	public String getMtype4() {
		return this.mtype4;
	}

	public void setMtype4(String mtype4) {
		this.mtype4 = mtype4;
	}

	@Column(name = "MTYPE_5", length = 2)
	public String getMtype5() {
		return this.mtype5;
	}

	public void setMtype5(String mtype5) {
		this.mtype5 = mtype5;
	}

	@Column(name = "MTYPE_6", length = 2)
	public String getMtype6() {
		return this.mtype6;
	}

	public void setMtype6(String mtype6) {
		this.mtype6 = mtype6;
	}

	@Column(name = "MTYPE_7", length = 2)
	public String getMtype7() {
		return this.mtype7;
	}

	public void setMtype7(String mtype7) {
		this.mtype7 = mtype7;
	}

	@Column(name = "MTYPE_8", length = 2)
	public String getMtype8() {
		return this.mtype8;
	}

	public void setMtype8(String mtype8) {
		this.mtype8 = mtype8;
	}

	@Column(name = "MTYPE_9", length = 2)
	public String getMtype9() {
		return this.mtype9;
	}

	public void setMtype9(String mtype9) {
		this.mtype9 = mtype9;
	}

	@Column(name = "MTYPE_10", length = 2)
	public String getMtype10() {
		return this.mtype10;
	}

	public void setMtype10(String mtype10) {
		this.mtype10 = mtype10;
	}

	@Column(name = "RATE_VALUES", nullable = false)
	public int getRateValues() {
		return this.rateValues;
	}

	public void setRateValues(int rateValues) {
		this.rateValues = rateValues;
	}

	@Column(name = "SERIES")
	public Integer getSeries() {
		return this.series;
	}

	public void setSeries(Integer series) {
		this.series = series;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "DETAILS", nullable = false, length = 30)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "SHORT_ID", length = 12)
	public String getShortId() {
		return this.shortId;
	}

	public void setShortId(String shortId) {
		this.shortId = shortId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_VALID_FROM", length = 23)
	public Date getDateValidFrom() {
		return this.dateValidFrom;
	}

	public void setDateValidFrom(Date dateValidFrom) {
		this.dateValidFrom = dateValidFrom;
	}

	@Column(name = "RATE_FIELD_TYPE", nullable = false)
	public int getRateFieldType() {
		return this.rateFieldType;
	}

	public void setRateFieldType(int rateFieldType) {
		this.rateFieldType = rateFieldType;
	}

	@Column(name = "PTYPE_1")
	public Integer getPtype1() {
		return this.ptype1;
	}

	public void setPtype1(Integer ptype1) {
		this.ptype1 = ptype1;
	}

	@Column(name = "PTYPE_2")
	public Integer getPtype2() {
		return this.ptype2;
	}

	public void setPtype2(Integer ptype2) {
		this.ptype2 = ptype2;
	}

	@Column(name = "PTYPE_3")
	public Integer getPtype3() {
		return this.ptype3;
	}

	public void setPtype3(Integer ptype3) {
		this.ptype3 = ptype3;
	}

	@Column(name = "PTYPE_4")
	public Integer getPtype4() {
		return this.ptype4;
	}

	public void setPtype4(Integer ptype4) {
		this.ptype4 = ptype4;
	}

	@Column(name = "PTYPE_5")
	public Integer getPtype5() {
		return this.ptype5;
	}

	public void setPtype5(Integer ptype5) {
		this.ptype5 = ptype5;
	}

	@Column(name = "PTYPE_6")
	public Integer getPtype6() {
		return this.ptype6;
	}

	public void setPtype6(Integer ptype6) {
		this.ptype6 = ptype6;
	}

	@Column(name = "PTYPE_7")
	public Integer getPtype7() {
		return this.ptype7;
	}

	public void setPtype7(Integer ptype7) {
		this.ptype7 = ptype7;
	}

	@Column(name = "PTYPE_8")
	public Integer getPtype8() {
		return this.ptype8;
	}

	public void setPtype8(Integer ptype8) {
		this.ptype8 = ptype8;
	}

	@Column(name = "PTYPE_9")
	public Integer getPtype9() {
		return this.ptype9;
	}

	public void setPtype9(Integer ptype9) {
		this.ptype9 = ptype9;
	}

	@Column(name = "PTYPE_10")
	public Integer getPtype10() {
		return this.ptype10;
	}

	public void setPtype10(Integer ptype10) {
		this.ptype10 = ptype10;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_VALID_TO", length = 23)
	public Date getDateValidTo() {
		return this.dateValidTo;
	}

	public void setDateValidTo(Date dateValidTo) {
		this.dateValidTo = dateValidTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rateDefinition")
	public Set<RateEntity> getRates() {
		return this.rates;
	}

	public void setRates(Set<RateEntity> rates) {
		this.rates = rates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rateDefinition")
	public Set<RateBandingEntity> getRateBandings() {
		return this.rateBandings;
	}

	public void setRateBandings(Set<RateBandingEntity> rateBandings) {
		this.rateBandings = rateBandings;
	}

}
