package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReinsuranceTreatyEntity generated by hbm2java
 */
@Entity
@Table(name = "REINSURANCE_TREATIES"

)
public class ReinsuranceTreatyEntity implements java.io.Serializable {

	private String ritId;
	private String modifyProcess;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyBy;
	private String createdProcess;
	private Date createdTime;
	private Date createdDate;
	private String createdBy;
	private String benefitType;
	private String currency;
	private Integer reportingFrequency;
	private String type;
	private Date endDate;
	private Date startDate;
	private String treaty;
	private String reinsurer;
	private Integer status;
	private String description;
	private Integer layers;
	private Set<ReinsurerEntity> reinsurers = new HashSet<ReinsurerEntity>(0);
	private Set<ReinsuranceTreatyShareEntity> reinsuranceTreatyShares = new HashSet<ReinsuranceTreatyShareEntity>(0);

	@Id
	@Column(name = "RIT_ID", unique = true, nullable = false, length = 6)
	public String getRitId() {
		return this.ritId;
	}

	public void setRitId(String ritId) {
		this.ritId = ritId;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "BENEFIT_TYPE", length = 6)
	public String getBenefitType() {
		return this.benefitType;
	}

	public void setBenefitType(String benefitType) {
		this.benefitType = benefitType;
	}

	@Column(name = "CURRENCY", length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "REPORTING_FREQUENCY")
	public Integer getReportingFrequency() {
		return this.reportingFrequency;
	}

	public void setReportingFrequency(Integer reportingFrequency) {
		this.reportingFrequency = reportingFrequency;
	}

	@Column(name = "TYPE", length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "TREATY", length = 6)
	public String getTreaty() {
		return this.treaty;
	}

	public void setTreaty(String treaty) {
		this.treaty = treaty;
	}

	@Column(name = "REINSURER", length = 6)
	public String getReinsurer() {
		return this.reinsurer;
	}

	public void setReinsurer(String reinsurer) {
		this.reinsurer = reinsurer;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "DESCRIPTION", length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LAYERS")
	public Integer getLayers() {
		return this.layers;
	}

	public void setLayers(Integer layers) {
		this.layers = layers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "HAS0", joinColumns = {
			@JoinColumn(name = "FK_REINSURANCE_RIT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "FK_REINSURERSRIS_ID", nullable = false, updatable = false) })
	public Set<ReinsurerEntity> getReinsurers() {
		return this.reinsurers;
	}

	public void setReinsurers(Set<ReinsurerEntity> reinsurers) {
		this.reinsurers = reinsurers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reinsuranceTreaty")
	public Set<ReinsuranceTreatyShareEntity> getReinsuranceTreatyShares() {
		return this.reinsuranceTreatyShares;
	}

	public void setReinsuranceTreatyShares(Set<ReinsuranceTreatyShareEntity> reinsuranceTreatyShares) {
		this.reinsuranceTreatyShares = reinsuranceTreatyShares;
	}

}
