package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReinsuranceTreatyShareEntity generated by hbm2java
 */
@Entity
@Table(name = "REINSURANCE_TREATY_SHARES"

)
public class ReinsuranceTreatyShareEntity implements java.io.Serializable {

	private long rtsId;
	private ReinsuranceTreatyEntity reinsuranceTreaty;
	private String reinsurer;
	private Integer status;
	private String createdBy;
	private BigDecimal percentage;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private String treaty;
	private Integer layer;

	@Id
	@Column(name = "RTS_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getRtsId() {
		return this.rtsId;
	}

	public void setRtsId(long rtsId) {
		this.rtsId = rtsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_REINSURANCE_RIT_ID")
	public ReinsuranceTreatyEntity getReinsuranceTreaty() {
		return this.reinsuranceTreaty;
	}

	public void setReinsuranceTreaty(ReinsuranceTreatyEntity reinsuranceTreaty) {
		this.reinsuranceTreaty = reinsuranceTreaty;
	}

	@Column(name = "REINSURER", length = 6)
	public String getReinsurer() {
		return this.reinsurer;
	}

	public void setReinsurer(String reinsurer) {
		this.reinsurer = reinsurer;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "PERCENTAGE", precision = 12, scale = 6)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "TREATY", length = 6)
	public String getTreaty() {
		return this.treaty;
	}

	public void setTreaty(String treaty) {
		this.treaty = treaty;
	}

	@Column(name = "LAYER")
	public Integer getLayer() {
		return this.layer;
	}

	public void setLayer(Integer layer) {
		this.layer = layer;
	}

}
