package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskEntity generated by hbm2java
 */
@Entity
@Table(name = "TASKS"

)
public class TaskEntity implements java.io.Serializable {

	private int tskId;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private String name;
	private int jobType;
	private String group0;
	private Integer normalSequence;
	private Date normalRunTime;
	private String s1Text;
	private String s1No;
	private String s1Date;

	@Id
	@Column(name = "TSK_ID", unique = true, nullable = false)
	public int getTskId() {
		return this.tskId;
	}

	public void setTskId(int tskId) {
		this.tskId = tskId;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "NAME", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "JOB_TYPE", nullable = false)
	public int getJobType() {
		return this.jobType;
	}

	public void setJobType(int jobType) {
		this.jobType = jobType;
	}

	@Column(name = "GROUP0", length = 6)
	public String getGroup0() {
		return this.group0;
	}

	public void setGroup0(String group0) {
		this.group0 = group0;
	}

	@Column(name = "NORMAL_SEQUENCE")
	public Integer getNormalSequence() {
		return this.normalSequence;
	}

	public void setNormalSequence(Integer normalSequence) {
		this.normalSequence = normalSequence;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NORMAL_RUN_TIME", length = 23)
	public Date getNormalRunTime() {
		return this.normalRunTime;
	}

	public void setNormalRunTime(Date normalRunTime) {
		this.normalRunTime = normalRunTime;
	}

	@Column(name = "S1_TEXT", length = 10)
	public String getS1Text() {
		return this.s1Text;
	}

	public void setS1Text(String s1Text) {
		this.s1Text = s1Text;
	}

	@Column(name = "S1_NO", length = 10)
	public String getS1No() {
		return this.s1No;
	}

	public void setS1No(String s1No) {
		this.s1No = s1No;
	}

	@Column(name = "S1_DATE", length = 10)
	public String getS1Date() {
		return this.s1Date;
	}

	public void setS1Date(String s1Date) {
		this.s1Date = s1Date;
	}

}
