package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * XFundsJEntity generated by hbm2java
 */
@Entity
@Table(name = "X_FUNDS_J"

)
public class XFundsJEntity implements java.io.Serializable {

	private String xfjId;
	private Integer days;
	private Boolean entryFees;
	private Boolean exitFees;
	private Boolean lockedFund;

	@Id
	@Column(name = "xfj_id", unique = true, nullable = false, length = 8)
	public String getXfjId() {
		return this.xfjId;
	}

	public void setXfjId(String xfjId) {
		this.xfjId = xfjId;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Column(name = "entry_fees")
	public Boolean getEntryFees() {
		return this.entryFees;
	}

	public void setEntryFees(Boolean entryFees) {
		this.entryFees = entryFees;
	}

	@Column(name = "exit_fees")
	public Boolean getExitFees() {
		return this.exitFees;
	}

	public void setExitFees(Boolean exitFees) {
		this.exitFees = exitFees;
	}

	@Column(name = "locked_fund")
	public Boolean getLockedFund() {
		return this.lockedFund;
	}

	public void setLockedFund(Boolean lockedFund) {
		this.lockedFund = lockedFund;
	}

}
