INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','CONTRACT_NUMBER', 'Numéro du contrat');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','PRODUCT_TRADE_NAME', 'Nom commercial du produit');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','CONTRACT_EFFECTIVE_DATE', 'Date d''effet du contrat');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','ISIN_CODE', 'Code ISIN');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','FUND_LABEL', 'Libellé du fond');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','WEIGHTED_AVERAGE_PRICE', 'Prix moyen pondéré à l''achat');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','FUND_CURRENCY', 'Devise du fond');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','NAV_DATE', 'Date valeur');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','NAV', 'VNI');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','UNITY_NUMBER', 'Nombre d''unités');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','fr','CURRENCY_AMOUNT', 'Montant dans la devise du contrat');


INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','CONTRACT_NUMBER', 'Policy n°');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','PRODUCT_TRADE_NAME', 'Product Name');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','CONTRACT_EFFECTIVE_DATE', 'Date of effect');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','ISIN_CODE', 'ISIN code');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','FUND_LABEL', 'Fund');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','WEIGHTED_AVERAGE_PRICE', 'Weighted average price');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','FUND_CURRENCY', 'Fund currency');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','NAV_DATE', 'Value date');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','NAV', 'NAV');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','UNITY_NUMBER', 'Number of units');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_PORTFOLIO_COLUMN_HEADER','en','CURRENCY_AMOUNT', 'Amount in the investment fund currency');