GO
DELETE FROM [dbo].[TRANSCODIFICATION]
GO
SET IDENTITY_INSERT [dbo].[TRANSCODIFICATION] ON 

GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (158, N'PAYS', N'NLD', N'NL', N'code langue')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (1, N'PAYS', N'AE ', N'AE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (2, N'PAYS', N'AR ', N'AR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (3, N'PAYS', N'AT ', N'AT', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (4, N'PAYS', N'AUS', N'AU', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (5, N'PAYS', N'B  ', N'BE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (6, N'PAYS', N'BL ', N'BL', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (7, N'PAYS', N'BR ', N'BR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (8, N'PAYS', N'BS ', N'BS', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (9, N'PAYS', N'C  ', N'CM', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (10, N'PAYS', N'CAN', N'CA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (11, N'PAYS', N'CD ', N'CD', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (12, N'PAYS', N'CH ', N'CH', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (13, N'PAYS', N'CHL', N'CL', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (14, N'PAYS', N'CN ', N'CN', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (15, N'PAYS', N'CY ', N'CY', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (16, N'PAYS', N'CZ ', N'CZ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (17, N'PAYS', N'D  ', N'DE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (18, N'PAYS', N'DK ', N'DK', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (19, N'PAYS', N'DZ ', N'DZ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (20, N'PAYS', N'E  ', N'ES', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (21, N'PAYS', N'EC ', N'EC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (22, N'PAYS', N'EGY', N'EG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (23, N'PAYS', N'F  ', N'FR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (24, N'PAYS', N'FI ', N'FI', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (25, N'PAYS', N'GA ', N'GA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (26, N'PAYS', N'GB ', N'GB', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (27, N'PAYS', N'GH ', N'GH', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (28, N'PAYS', N'GI ', N'GI', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (29, N'PAYS', N'GN ', N'GN', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (30, N'PAYS', N'GP ', N'GP', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (31, N'PAYS', N'GR ', N'GR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (32, N'PAYS', N'HK ', N'HK', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (33, N'PAYS', N'HR ', N'HR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (34, N'PAYS', N'HU ', N'HU', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (35, N'PAYS', N'I  ', N'IT', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (36, N'PAYS', N'ID ', N'ID', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (37, N'PAYS', N'IE ', N'IE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (38, N'PAYS', N'IL ', N'IL', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (39, N'PAYS', N'IND', N'IN', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (40, N'PAYS', N'IS ', N'IS', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (41, N'PAYS', N'JE ', N'JE ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (42, N'PAYS', N'JO ', N'JO', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (43, N'PAYS', N'JP ', N'JP', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (44, N'PAYS', N'KE ', N'KE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (45, N'PAYS', N'KH ', N'KH', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (46, N'PAYS', N'KR ', N'KR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (47, N'PAYS', N'KZ ', N'KZ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (48, N'PAYS', N'L  ', N'LU', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (49, N'PAYS', N'LI ', N'LI ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (50, N'PAYS', N'LT ', N'LT', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (51, N'PAYS', N'LV ', N'LV', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (52, N'PAYS', N'MA ', N'MA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (53, N'PAYS', N'MC ', N'MC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (54, N'PAYS', N'MQ ', N'MQ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (55, N'PAYS', N'MT ', N'MT', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (56, N'PAYS', N'MU ', N'MU', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (57, N'PAYS', N'MX ', N'MX', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (58, N'PAYS', N'MY ', N'MY', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (59, N'PAYS', N'NAM', N'NA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (60, N'PAYS', N'NC ', N'NC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (61, N'PAYS', N'NG ', N'NG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (62, N'PAYS', N'NL ', N'NL', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (63, N'PAYS', N'NO ', N'NO', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (64, N'PAYS', N'NZL', N'NZ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (65, N'PAYS', N'P  ', N'PT', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (66, N'PAYS', N'PA ', N'PA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (67, N'PAYS', N'PE ', N'PE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (68, N'PAYS', N'PF ', N'PF', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (69, N'PAYS', N'PL ', N'PL', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (70, N'PAYS', N'RO ', N'RO', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (71, N'PAYS', N'RU ', N'RU', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (72, N'PAYS', N'SA ', N'SA ', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (73, N'PAYS', N'SE ', N'SE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (74, N'PAYS', N'SG ', N'SG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (75, N'PAYS', N'SK ', N'SK', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (76, N'PAYS', N'SL ', N'LK', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (77, N'PAYS', N'SLO', N'SI', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (78, N'PAYS', N'SN ', N'SN', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (79, N'PAYS', N'T  ', N'TR', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (80, N'PAYS', N'TH ', N'TH', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (81, N'PAYS', N'TN ', N'TN', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (82, N'PAYS', N'UA ', N'UA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (83, N'PAYS', N'USA', N'US', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (84, N'PAYS', N'UY ', N'UY', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (85, N'PAYS', N'VE ', N'VE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (86, N'PAYS', N'VG ', N'VG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (87, N'PAYS', N'VN ', N'VN', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (88, N'PAYS', N'Z  ', N'CD', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (89, N'PAYS', N'ZA ', N'ZA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (90, N'DESTINATION_COURRIER', N'OTH', N'AUTRE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (91, N'DESTINATION_COURRIER', N'BIL', N'BIL', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (92, N'DESTINATION_COURRIER', N'AGT', N'COURTIER', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (93, N'DESTINATION_COURRIER', N'HLC', N'CONSERVE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (94, N'DESTINATION_COURRIER', N'CLH', N'CLIENT', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (95, N'PERSONNALITE_JURIDIQUE', N'LEG', N'PM', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (96, N'PERSONNALITE_JURIDIQUE', N'PHY', N'PP', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (97, N'TYPE_SUPPORT', N'GR+PB', N'TG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (98, N'TYPE_SUPPORT', N'GR', N'TG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (99, N'TYPE_SUPPORT', N'FIC', N'UC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (100, N'TYPE_SUPPORT', N'UL', N'UC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (101, N'TYPE_SUPPORT', N'DED', N'UC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (102, N'CODE_EVENT', N'IADJU', N'VERG', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (103, N'CODE_EVENT', N'IPREA', N'VESU', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (104, N'CODE_EVENT', N'IPREM', N'SOUS', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (105, N'CODE_EVENT', N'MDIVI', N'DIVI', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (106, N'CODE_EVENT', N'MPROF', N'VEPB', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (107, N'CODE_EVENT', N'ODEAT', N'DASS', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (108, N'CODE_EVENT', N'OMATU', N'TPP', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (109, N'CODE_EVENT', N'OSURR', N'RATO', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (110, N'CODE_EVENT', N'OWITH', N'RAPA', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (111, N'CODE_EVENT', N'RNPOL', N'RENV', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (112, N'CODE_EVENT', N'SWITI', N'ARAC', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (113, N'CODE_EVENT', N'SWITO', N'ARVE', N'')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (157, N'PAYS', N'FRA', N'FR', NULL)
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (159, 'LANGUAGE','1','EN', 'English')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (160, 'LANGUAGE','2','UD', 'User.Def')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (161, 'LANGUAGE','3','FR', 'French')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (162, 'LANGUAGE','4','PL', 'Polish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (163, 'LANGUAGE','5','CZ', 'Czech' )
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (164, 'LANGUAGE','6','TR', 'Turkish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (165, 'LANGUAGE','7','NO', 'Norwegian')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (166, 'LANGUAGE','8','IT', 'Italian')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (167, 'LANGUAGE','9','DE', 'German')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (168, 'LANGUAGE','10','SE', 'Swedish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (169, 'LANGUAGE','11','NL', 'Flemish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (170, 'LANGUAGE','12','ES', 'Spanish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (171, 'LANGUAGE','13','PT', 'Portuguese')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (172, 'LANGUAGE','14','DK', 'Danish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (173, 'PAYS', 'BEL', 'BE', 'Belgium')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (174, 'PAYS', 'DEU', 'DE', 'Deutchland')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (175, 'PAYS', 'DNK', 'DK', 'Denmark')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (176, 'PAYS', 'ESP', 'ES', 'Spain')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (177, 'PAYS', 'FIN', 'FI', 'Finland')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (178, 'PAYS', 'GBR', 'EN', 'UK')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (179, 'PAYS', 'ITA', 'IT', 'Italy')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (180, 'PAYS', 'LUX', 'LU', 'Luxembourg')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (181, 'PAYS', 'NOR', 'NO', 'Norway')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (182, 'PAYS', 'PRT', 'PT', 'Portugal')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (183, 'PAYS', 'SWE', 'SE', 'Sweden')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (184, 'PAYS', 'XXX', 'EN', 'International')
  GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (185, 'TITLE', '2', 'MR', 'Code Lissia')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (186, 'TITLE', '1', 'MME', 'Code Lissia')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (187, 'LANGUAGE', 'PRT', 'PT', 'Portuguese')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (188, 'LANGUAGE', 'NOR', 'NO', 'Norwegian')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (189, 'LANGUAGE', 'FIN', 'FI', 'Finnish')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (190, 'LANGUAGE', 'FRA', 'FR', 'French')
GO
INSERT [dbo].[TRANSCODIFICATION] ([ID], [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES (191, 'LANGUAGE', 'ENG', 'EN', 'English')
GO
SET IDENTITY_INSERT [dbo].[TRANSCODIFICATION] OFF
GO
