INSERT INTO INTERNATIONALIZATION(TYPE,LANGUAGE,SOURCE,DESTINATION) VALUES ('CommissionType','fr','ENTRY', 'Commission sur frais d''entrée');
INSERT INTO INTERNATIONALIZATION(TYPE,LANGUAGE,SOURCE,DESTINATION) VALUES ('CommissionType','fr','PORTFOLIO', 'Commissions sur encours');
INSERT INTO INTERNATIONALIZATION(TYPE,LANGUAGE,SOURCE,DESTINATION) VALUES ('CommissionType','en','PORTFOLIO', 'Portfolio commissions');
INSERT INTO INTERNATIONALIZATION(TYPE,LANGUAGE,SOURCE,DESTINATION) VALUES ('CommissionType','en','ENTRY', 'Commissions on front-end load');
