package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ColumnTransformer;

/**
 * CurrencyEntity generated by hbm2java
 */
@Entity
@Table(name = "CURRENCIES"

)
public class CurrencyEntity implements java.io.Serializable {

	// private static final String WHITE_SPACE = " ";
	@ColumnTransformer(read = "rtrim(ccyId)")
	private String ccyId;
	private String name;
	private String nliCode;
	private String createdProcess;
	private String modifyProcess;
	private BigDecimal premiumTolerance;
	private String ccyCode;
	private int decimalPlaces;
	private String docnPreDesc;
	private String docnPostDesc;
	private int status;
	private String isoCode;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;

	@Id
	@Column(name = "CCY_ID", unique = true, nullable = false, length = 4)
	public String getCcyId() {
		return this.ccyId;
	}

	public void setCcyId(String ccyId) {
		this.ccyId = ccyId;
	}

	@Column(name = "NAME", nullable = false, length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NLI_CODE", length = 10)
	public String getNliCode() {
		return this.nliCode;
	}

	public void setNliCode(String nliCode) {
		this.nliCode = nliCode;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "PREMIUM_TOLERANCE", precision = 10)
	public BigDecimal getPremiumTolerance() {
		return this.premiumTolerance;
	}

	public void setPremiumTolerance(BigDecimal premiumTolerance) {
		this.premiumTolerance = premiumTolerance;
	}

	@Column(name = "CCY_CODE", nullable = false, length = 5)
	public String getCcyCode() {
		return this.ccyCode;
	}

	public void setCcyCode(String ccyCode) {
		this.ccyCode = ccyCode;
	}

	@Column(name = "DECIMAL_PLACES", nullable = false)
	public int getDecimalPlaces() {
		return this.decimalPlaces;
	}

	public void setDecimalPlaces(int decimalPlaces) {
		this.decimalPlaces = decimalPlaces;
	}

	@Column(name = "DOCN_PRE_DESC", length = 6)
	public String getDocnPreDesc() {
		return this.docnPreDesc;
	}

	public void setDocnPreDesc(String docnPreDesc) {
		this.docnPreDesc = docnPreDesc;
	}

	@Column(name = "DOCN_POST_DESC", length = 6)
	public String getDocnPostDesc() {
		return this.docnPostDesc;
	}

	public void setDocnPostDesc(String docnPostDesc) {
		this.docnPostDesc = docnPostDesc;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "ISO_CODE", length = 5)
	public String getIsoCode() {
		return this.isoCode;
	}

	public void setIsoCode(String isoCode) {
		this.isoCode = isoCode;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
