package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FundManagementHeaderEntity generated by hbm2java
 */
@Entity
@Table(name = "FUND_MANAGEMENT_HEADERS"

)
public class FundManagementHeaderEntity implements java.io.Serializable {

	private int fmhId;
	private int status;
	private Date refreshStartTime;
	private Date refreshEndTime;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Set<FundManagementDetailEntity> fundManagementDetails = new HashSet<FundManagementDetailEntity>(0);

	@Id
	@Column(name = "FMH_ID", unique = true, nullable = false)
	public int getFmhId() {
		return this.fmhId;
	}

	public void setFmhId(int fmhId) {
		this.fmhId = fmhId;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REFRESH_START_TIME", length = 23)
	public Date getRefreshStartTime() {
		return this.refreshStartTime;
	}

	public void setRefreshStartTime(Date refreshStartTime) {
		this.refreshStartTime = refreshStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REFRESH_END_TIME", length = 23)
	public Date getRefreshEndTime() {
		return this.refreshEndTime;
	}

	public void setRefreshEndTime(Date refreshEndTime) {
		this.refreshEndTime = refreshEndTime;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundManagementHeader")
	public Set<FundManagementDetailEntity> getFundManagementDetails() {
		return this.fundManagementDetails;
	}

	public void setFundManagementDetails(Set<FundManagementDetailEntity> fundManagementDetails) {
		this.fundManagementDetails = fundManagementDetails;
	}

}
