
  ALTER TABLE  CLIENTS
  ADD 
  DATE_OF_SELF_CERT		DATETIME	NULL,
  CRS_DATE_OF_LAST_DEC		DATETIME	NULL
  
  GO
  
    ALTER TABLE  CLIENT_ENDORSEMENTS
    ADD 
    DATE_OF_SELF_CERT		DATETIME	NULL,
    CRS_DATE_OF_LAST_DEC		DATETIME	NULL
    
  GO
  
  ALTER TABLE   CLIENT_CONTACT_DETAILS
  ADD
  DATE_OF_COUNTRY_CHANGE	DATETIME	NULL,
  PREVIOUS_COUNTRY		CHAR(30)	NULL
  
  GO
  
  ALTER TABLE   CLI_CONTACT_CHANGES
  ADD
  DATE_OF_COUNTRY_CHANGE	DATETIME	NULL,
  PREVIOUS_COUNTRY		CHAR(30)	NULL
  
  GO