/**
 * 
 */
package lu.wealins.liability.services.core.business.exceptions;

/**
 * @author xqv66
 *
 */
public enum FundPriceExceptionCode {
	ISIN_DOES_NOT_EXIST, DUPLICATE_FUND_PRICE, WRONG_PRICING_DAY, PRICE_VARIATION_TOO_HIGH, PRICE_DATE_VARIATION_TOO_HIGH, WRONG_PRICE_CURRENCY, PENDING_TRANSACTIONS_IN_WITH_INTPUT_FEES, PENDING_TRANSACTIONS_OUT_WITH_OUTPUT_FEES, BLOCKED_TRANSACTIONS, PRICE_INSURANCE_HOLIDAY, PRICE_EQUALS_TO_ZERO
}
