package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyPremiumChangeEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_PREMIUM_CHANGES"

)
public class PolicyPremiumChangeEntity implements java.io.Serializable {

	private String ppcId;
	private PolicyPremiumEntity policyPremium;
	private int changeNum;
	private Date dateDue;
	private int periodDue;
	private int type;
	private int source;
	private int changeType;
	private BigDecimal changeIndex;
	private BigDecimal changeValue;
	private Integer amountSet;
	private BigDecimal amountBefore;
	private BigDecimal amountAfter;
	private Integer assuredSet;
	private BigDecimal assuredBefore;
	private BigDecimal assuredAfter;
	private int status;
	private Integer escCoverage;
	private Integer ppcType;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private String modifyBy;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyProcess;
	private BigDecimal requestedIndex;
	private BigDecimal requestedValue;
	private BigDecimal requestedType;

	@Id
	@Column(name = "PPC_ID", unique = true, nullable = false, length = 22)
	public String getPpcId() {
		return this.ppcId;
	}

	public void setPpcId(String ppcId) {
		this.ppcId = ppcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICY_PREMIPCP_ID")
	public PolicyPremiumEntity getPolicyPremium() {
		return this.policyPremium;
	}

	public void setPolicyPremium(PolicyPremiumEntity policyPremium) {
		this.policyPremium = policyPremium;
	}

	@Column(name = "CHANGE_NUM", nullable = false)
	public int getChangeNum() {
		return this.changeNum;
	}

	public void setChangeNum(int changeNum) {
		this.changeNum = changeNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_DUE", nullable = false, length = 23)
	public Date getDateDue() {
		return this.dateDue;
	}

	public void setDateDue(Date dateDue) {
		this.dateDue = dateDue;
	}

	@Column(name = "PERIOD_DUE", nullable = false)
	public int getPeriodDue() {
		return this.periodDue;
	}

	public void setPeriodDue(int periodDue) {
		this.periodDue = periodDue;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "SOURCE", nullable = false)
	public int getSource() {
		return this.source;
	}

	public void setSource(int source) {
		this.source = source;
	}

	@Column(name = "CHANGE_TYPE", nullable = false)
	public int getChangeType() {
		return this.changeType;
	}

	public void setChangeType(int changeType) {
		this.changeType = changeType;
	}

	@Column(name = "CHANGE_INDEX", precision = 15, scale = 10)
	public BigDecimal getChangeIndex() {
		return this.changeIndex;
	}

	public void setChangeIndex(BigDecimal changeIndex) {
		this.changeIndex = changeIndex;
	}

	@Column(name = "CHANGE_VALUE", precision = 15)
	public BigDecimal getChangeValue() {
		return this.changeValue;
	}

	public void setChangeValue(BigDecimal changeValue) {
		this.changeValue = changeValue;
	}

	@Column(name = "AMOUNT_SET")
	public Integer getAmountSet() {
		return this.amountSet;
	}

	public void setAmountSet(Integer amountSet) {
		this.amountSet = amountSet;
	}

	@Column(name = "AMOUNT_BEFORE", precision = 15)
	public BigDecimal getAmountBefore() {
		return this.amountBefore;
	}

	public void setAmountBefore(BigDecimal amountBefore) {
		this.amountBefore = amountBefore;
	}

	@Column(name = "AMOUNT_AFTER", precision = 15)
	public BigDecimal getAmountAfter() {
		return this.amountAfter;
	}

	public void setAmountAfter(BigDecimal amountAfter) {
		this.amountAfter = amountAfter;
	}

	@Column(name = "ASSURED_SET")
	public Integer getAssuredSet() {
		return this.assuredSet;
	}

	public void setAssuredSet(Integer assuredSet) {
		this.assuredSet = assuredSet;
	}

	@Column(name = "ASSURED_BEFORE", precision = 15)
	public BigDecimal getAssuredBefore() {
		return this.assuredBefore;
	}

	public void setAssuredBefore(BigDecimal assuredBefore) {
		this.assuredBefore = assuredBefore;
	}

	@Column(name = "ASSURED_AFTER", precision = 15)
	public BigDecimal getAssuredAfter() {
		return this.assuredAfter;
	}

	public void setAssuredAfter(BigDecimal assuredAfter) {
		this.assuredAfter = assuredAfter;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "ESC_COVERAGE")
	public Integer getEscCoverage() {
		return this.escCoverage;
	}

	public void setEscCoverage(Integer escCoverage) {
		this.escCoverage = escCoverage;
	}

	@Column(name = "PPC_TYPE")
	public Integer getPpcType() {
		return this.ppcType;
	}

	public void setPpcType(Integer ppcType) {
		this.ppcType = ppcType;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "REQUESTED_INDEX", precision = 15, scale = 8)
	public BigDecimal getRequestedIndex() {
		return this.requestedIndex;
	}

	public void setRequestedIndex(BigDecimal requestedIndex) {
		this.requestedIndex = requestedIndex;
	}

	@Column(name = "REQUESTED_VALUE", precision = 15, scale = 8)
	public BigDecimal getRequestedValue() {
		return this.requestedValue;
	}

	public void setRequestedValue(BigDecimal requestedValue) {
		this.requestedValue = requestedValue;
	}

	@Column(name = "REQUESTED_TYPE", precision = 15, scale = 8)
	public BigDecimal getRequestedType() {
		return this.requestedType;
	}

	public void setRequestedType(BigDecimal requestedType) {
		this.requestedType = requestedType;
	}

}
