SET IDENTITY_INSERT CHECK_WORKFLOW ON;

INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
		    VALUES (126, 'Comment',NULL,'Text',NULL,NULL,NULL);

INSERT INTO CHECK_STEP VALUES (126,4,1,0,10,0, 24,NULL,NULL);

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;




