

 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('COMMISSI','COMMISSI','Contact of commission payment',1,62,0,'duo',GETDATE(), GETDATE(), 'WEBIA', 62,'',0);
 
