package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionLinkEntity generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_LINKS"

)
public class TransactionLinkEntity implements java.io.Serializable {

	private long trlId;
	private Set<TransactionEntity> transactions = new HashSet<TransactionEntity>(0);

	@Id
	@Column(name = "TRL_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getTrlId() {
		return this.trlId;
	}

	public void setTrlId(long trlId) {
		this.trlId = trlId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionLinked")
	public Set<TransactionEntity> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<TransactionEntity> transactions) {
		this.transactions = transactions;
	}

}
