package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QueuedTaskDateEntity generated by hbm2java
 */
@Entity
@Table(name = "QUEUED_TASK_DATES"

)
public class QueuedTaskDateEntity implements java.io.Serializable {

	private Date qtdId;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdSdate;
	private Date createdTime;
	private String createdProcess;
	private Set<BatchErrorEntity> batchErrors = new HashSet<BatchErrorEntity>(0);
	private Set<QueuedTaskEntity> queuedTasks = new HashSet<QueuedTaskEntity>(0);

	@Id
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QTD_ID", unique = true, nullable = false, length = 23)
	public Date getQtdId() {
		return this.qtdId;
	}

	public void setQtdId(Date qtdId) {
		this.qtdId = qtdId;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SDATE", nullable = false, length = 23)
	public Date getCreatedSdate() {
		return this.createdSdate;
	}

	public void setCreatedSdate(Date createdSdate) {
		this.createdSdate = createdSdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queuedTaskDate")
	public Set<BatchErrorEntity> getBatchErrors() {
		return this.batchErrors;
	}

	public void setBatchErrors(Set<BatchErrorEntity> batchErrors) {
		this.batchErrors = batchErrors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queuedTaskDate")
	public Set<QueuedTaskEntity> getQueuedTasks() {
		return this.queuedTasks;
	}

	public void setQueuedTasks(Set<QueuedTaskEntity> queuedTasks) {
		this.queuedTasks = queuedTasks;
	}

}
