package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PolicyCvgLiveEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_CVG_LIVES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class PolicyCvgLiveEntity implements java.io.Serializable {

	private String pclId;
	@JsonIgnore
	private PolicyCoverageEntity policyCoverage;
	private Long client;
	private Integer lifeNumber;
	private Integer smoker;
	private Integer sex;
	private BigDecimal issueAge;
	private Integer ageRating;
	private int coverage;
	private String policy;
	private BigDecimal addnFactor;
	private BigDecimal addnRpm;
	private String ratingReason;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Integer ratingTerm;

	@Id
	@Column(name = "PCL_ID", unique = true, nullable = false, length = 18)
	public String getPclId() {
		return this.pclId;
	}

	public void setPclId(String pclId) {
		this.pclId = pclId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICY_COVERPOC_ID")
	public PolicyCoverageEntity getPolicyCoverage() {
		return this.policyCoverage;
	}

	public void setPolicyCoverage(PolicyCoverageEntity policyCoverage) {
		this.policyCoverage = policyCoverage;
	}

	@Column(name = "CLIENT", precision = 10, scale = 0)
	public Long getClient() {
		return this.client;
	}

	public void setClient(Long client) {
		this.client = client;
	}

	@Column(name = "LIFE_NUMBER")
	public Integer getLifeNumber() {
		return this.lifeNumber;
	}

	public void setLifeNumber(Integer lifeNumber) {
		this.lifeNumber = lifeNumber;
	}

	@Column(name = "SMOKER")
	public Integer getSmoker() {
		return this.smoker;
	}

	public void setSmoker(Integer smoker) {
		this.smoker = smoker;
	}

	@Column(name = "SEX")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "ISSUE_AGE", precision = 5)
	public BigDecimal getIssueAge() {
		return this.issueAge;
	}

	public void setIssueAge(BigDecimal issueAge) {
		this.issueAge = issueAge;
	}

	@Column(name = "AGE_RATING")
	public Integer getAgeRating() {
		return this.ageRating;
	}

	public void setAgeRating(Integer ageRating) {
		this.ageRating = ageRating;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "ADDN_FACTOR", precision = 8, scale = 4)
	public BigDecimal getAddnFactor() {
		return this.addnFactor;
	}

	public void setAddnFactor(BigDecimal addnFactor) {
		this.addnFactor = addnFactor;
	}

	@Column(name = "ADDN_RPM", precision = 8, scale = 4)
	public BigDecimal getAddnRpm() {
		return this.addnRpm;
	}

	public void setAddnRpm(BigDecimal addnRpm) {
		this.addnRpm = addnRpm;
	}

	@Column(name = "RATING_REASON", length = 8)
	public String getRatingReason() {
		return this.ratingReason;
	}

	public void setRatingReason(String ratingReason) {
		this.ratingReason = ratingReason;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "RATING_TERM")
	public Integer getRatingTerm() {
		return this.ratingTerm;
	}

	public void setRatingTerm(Integer ratingTerm) {
		this.ratingTerm = ratingTerm;
	}

}
