SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
DROP TABLE IF EXISTS [dbo].[STATEMENTLANGUAGEDEFAULT]
CREATE TABLE [dbo].[STATEMENTLANGUAGEDEFAULT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LANGUAGE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_STATEMENTLANGUAGEDEAFULT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
SET IDENTITY_INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ON 
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (1, N'FR')
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (2, N'IT')
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (3, N'NL')
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (4, N'EN')
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (5, N'DE')
SET IDENTITY_INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] OFF