

delete from [dbo].[PARAMETRAGEPRODUIT]

SET IDENTITY_INSERT [dbo].[PARAMETRAGEPRODUIT] ON 

GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (136, N'4BC', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (137, N'4D1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (138, N'4D2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (139, N'4F1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (140, N'4F2', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (141, N'4F3', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (142, N'4F4', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (143, N'4F5', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (144, N'4F6', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (145, N'4F7', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (146, N'4F8', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (147, N'4IC', N'AIO', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (148, N'AGE', N'AIO', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (149, N'AL2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (150, N'ALI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (151, N'ASS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (152, N'B01', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (153, N'B02', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (154, N'B03', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (155, N'B04', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (156, N'B05', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (157, N'B06', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (158, N'B07', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (159, N'B08', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (160, N'B09', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (161, N'B10', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (162, N'B11', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (163, N'B12', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (164, N'BDLL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (165, N'BEI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (166, N'BLL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (167, N'BLS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (168, N'BLSG', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (169, N'BV', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (170, N'BVI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (171, N'CAPL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (172, N'CAPOFI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (173, N'CAPREPLUS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (174, N'CBL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (175, N'CI1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (176, N'CL2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (177, N'CLL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (178, N'D41', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (179, N'D42', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (180, N'D43', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (181, N'D44', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (182, N'D45', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (183, N'D46', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (184, N'D47', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (185, N'D48', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (186, N'D49', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (187, N'D50', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (188, N'D51', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (189, N'D52', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (190, N'D53', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (191, N'D54', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (192, N'D55', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (193, N'D56', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (194, N'DBL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (195, N'DC1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (196, N'DC2', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (197, N'DC4', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (198, N'DC5', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (199, N'DCP', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (200, N'DD', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (201, N'DD2', N'AIO', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (202, N'DDY', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (203, N'DF12', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (204, N'DG', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (205, N'DG1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (206, N'DG2', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (207, N'DG3', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (208, N'DG4', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (209, N'DG5', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (210, N'DG6', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (211, N'DG7', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (212, N'DG8', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (213, N'DG9', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (214, N'DGA', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (215, N'DGB', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (216, N'DGC', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (217, N'DGE', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (218, N'DGF', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (219, N'DIF', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (220, N'DLE', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (221, N'DLP', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (222, N'DLPA', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (223, N'DLS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (224, N'DLV', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (225, N'DLZ', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (226, N'DO2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (227, N'DO3', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (228, N'DO4', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (229, N'DO5', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (230, N'DO6', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (231, N'DO7', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (232, N'DO8', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (233, N'DP0', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (234, N'DP1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (235, N'DP2', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (236, N'DP3', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (237, N'DP4', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (238, N'DP5', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (239, N'DP6', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (240, N'DP7', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (241, N'DP8', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (242, N'DP9', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (243, N'DPI', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (244, N'DPO', N'UC', N'AsFIDTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (245, N'DPS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (246, N'DS1', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (247, N'DS2', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (248, N'DS3', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (249, N'DSE', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (250, N'DSP', N'TG', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (251, N'DV1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (252, N'DX1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (253, N'DX2', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (254, N'DX3', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (255, N'DX4', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (256, N'ETL', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (257, N'FDI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (258, N'FF', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (259, N'FIE', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (260, N'FLX', N'TG', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (261, N'FMF', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (262, N'FX1', N'TG', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (263, N'FX2', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (264, N'IF1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (265, N'IF2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (266, N'IL1', N'TG', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (267, N'IL2', N'TG', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (268, N'IL3', N'TG', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (269, N'IMMO', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (270, N'LC1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (271, N'LL1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (272, N'LL2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (273, N'LL3', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (274, N'LL4', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (275, N'LL5', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (276, N'LL6', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (277, N'LRI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (278, N'LSC0915', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (279, N'LSL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (280, N'LSLBE', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (281, N'LSP0815', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (282, N'LUSEPO', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (283, N'LUSESP', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (284, N'LUXG', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (285, N'LUXS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (286, N'LUXSEL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (287, N'LUXSELCAP', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (288, N'LUXSELFR', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (289, N'LV', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (290, N'LXSF0815', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (291, N'LXSF1015', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (292, N'MLL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (293, N'MU1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (294, N'MU2', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (295, N'MUI', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (296, N'NLL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (297, N'null', N'AIO', N'NONE')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (298, N'OGFD', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (299, N'OGRP', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (300, N'OLS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (301, N'OLSD', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (302, N'OLUX', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (303, N'OMF', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (304, N'OMF0409', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (305, N'OMPB', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (306, N'OP1', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (307, N'OP2', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (308, N'OPL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (309, N'OPORT', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (310, N'OPPG', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (311, N'OPPG0409', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (312, N'OPPL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (313, N'OPPS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (314, N'ORL', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (315, N'ORLF', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (316, N'PLI', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (317, N'PPF', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (318, N'PPF1015', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (319, N'PPN', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (320, N'PPN0216', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (321, N'PPS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (322, N'PR1', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (323, N'PR2', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (324, N'PRK', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (325, N'PRO', N'TG', N'AsTGTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (326, N'PRSEBE', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (327, N'PRSEIN', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (328, N'PRSELUX', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (329, N'PSB0816', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (330, N'PVASS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (331, N'PVI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (332, N'REG', N'AIO', N'AsAIOTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (333, N'SPPB', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (334, N'TPLUS', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (335, N'TPLUSA', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (343, N'WEALLU', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (336, N'WEACFR', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (337, N'WEACLU', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (338, N'WEALBE', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (339, N'WEALFI', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (340, N'WEALFR', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (341, N'WEALPT', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (342, N'WEALSE', N'UC', N'AsUCTP')
GO
INSERT [dbo].[PARAMETRAGEPRODUIT] ([ID], [CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (344, N'4UK', N'UC', N'AsUCTP')
GO
SET IDENTITY_INSERT [dbo].[PARAMETRAGEPRODUIT] OFF
GO
