INSERT [dbo].[PARAMETRAGEPRODUIT] ([CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (N'WEAKFI', N'UC', N'AsUCTP')
INSERT [dbo].[PARAMETRAGEPRODUIT] ([CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (N'WEALES', N'UC', N'AsUCTP')
INSERT [dbo].[PARAMETRAGEPRODUIT] ([CODEPRODUIT], [BRANCH], [MODELESITUATION]) VALUES (N'WEALNO', N'UC', N'AsUCTP')