INSERT [dbo].[AGENT_CATEGORIES] ([ACA_ID], [NAME], [MODIFY_PROCESS], [STATUS], [CREATED_BY], [CREATED_DATE], [CREATED_TIME], [MODIFY_BY], [MODIFY_DATE], [MODIFY_TIME], [CREATED_PROCESS], [REGISTRATION_TYPE], [REPORT_CATEGORY]) 
VALUES (N'PSI  ', N'PSI', NULL, 1, N'RVN  ', CAST(N'2018-02-06T00:00:00.000' AS DateTime), CAST(N'1970-01-01T18:30:46.000' AS DateTime), NULL, NULL, NULL, N'ACLACA01_A1 ', 1, N'      ')
GO

UPDATE AGENT_CATEGORIES set ACA_ID = 'IFI', Name = 'IFI' Where ACA_ID = 'FA';



