package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountryEntity generated by hbm2java
 */
@Entity
@Table(name = "COUNTRIES"

)
public class CountryEntity implements java.io.Serializable {

	private String ctyId;
	private Integer isoNumber;
	private String nationality;
	private String name;
	private String riskCategory;
	private Integer nationalIdFormat;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private String carPlateCode;
	private String isoCode2Pos;
	private String ptCode;
	private String isoNameFrench;
	private String isoNameEnglish;

	@Id
	@Column(name = "CTY_ID", unique = true, nullable = false, length = 4)
	public String getCtyId() {
		return this.ctyId;
	}

	public void setCtyId(String ctyId) {
		this.ctyId = ctyId;
	}

	@Column(name = "ISO_NUMBER")
	public Integer getIsoNumber() {
		return this.isoNumber;
	}

	public void setIsoNumber(Integer isoNumber) {
		this.isoNumber = isoNumber;
	}

	@Column(name = "NATIONALITY", length = 24)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "NAME", nullable = false, length = 27)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "RISK_CATEGORY", length = 8)
	public String getRiskCategory() {
		return this.riskCategory;
	}

	public void setRiskCategory(String riskCategory) {
		this.riskCategory = riskCategory;
	}

	@Column(name = "NATIONAL_ID_FORMAT")
	public Integer getNationalIdFormat() {
		return this.nationalIdFormat;
	}

	public void setNationalIdFormat(Integer nationalIdFormat) {
		this.nationalIdFormat = nationalIdFormat;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "CAR_PLATE_CODE", length = 6)
	public String getCarPlateCode() {
		return this.carPlateCode;
	}

	public void setCarPlateCode(String carPlateCode) {
		this.carPlateCode = carPlateCode;
	}

	@Column(name = "ISO_CODE_2_POS", length = 4)
	public String getIsoCode2Pos() {
		return this.isoCode2Pos;
	}

	public void setIsoCode2Pos(String isoCode2Pos) {
		this.isoCode2Pos = isoCode2Pos;
	}

	@Column(name = "PT_CODE", length = 4)
	public String getPtCode() {
		return this.ptCode;
	}

	public void setPtCode(String ptCode) {
		this.ptCode = ptCode;
	}

	@Column(name = "ISO_NAME_FRENCH", length = 45)
	public String getIsoNameFrench() {
		return this.isoNameFrench;
	}

	public void setIsoNameFrench(String isoNameFrench) {
		this.isoNameFrench = isoNameFrench;
	}

	@Column(name = "ISO_NAME_ENGLISH", length = 45)
	public String getIsoNameEnglish() {
		return this.isoNameEnglish;
	}

	public void setIsoNameEnglish(String isoNameEnglish) {
		this.isoNameEnglish = isoNameEnglish;
	}

}
