package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentDefinitionsCopyEntity generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT_DEFINITIONS_COPY"

)
public class DocumentDefinitionsCopyEntity implements java.io.Serializable {

	private String ddfId;
	private String messageText;
	private Integer action0;
	private String product;
	private Integer whoTo;
	private int type;
	private String name;
	private String pathname;
	private String fieldsUsed;
	private Integer dataSet;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Integer classification;
	private Integer additionalFormat;
	private String printer;

	@Id
	@Column(name = "DDF_ID", unique = true, nullable = false, length = 15)
	public String getDdfId() {
		return this.ddfId;
	}

	public void setDdfId(String ddfId) {
		this.ddfId = ddfId;
	}

	@Column(name = "MESSAGE_TEXT", length = 120)
	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	@Column(name = "ACTION0")
	public Integer getAction0() {
		return this.action0;
	}

	public void setAction0(Integer action0) {
		this.action0 = action0;
	}

	@Column(name = "PRODUCT", length = 12)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "WHO_TO")
	public Integer getWhoTo() {
		return this.whoTo;
	}

	public void setWhoTo(Integer whoTo) {
		this.whoTo = whoTo;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PATHNAME", length = 100)
	public String getPathname() {
		return this.pathname;
	}

	public void setPathname(String pathname) {
		this.pathname = pathname;
	}

	@Column(name = "FIELDS_USED", length = 200)
	public String getFieldsUsed() {
		return this.fieldsUsed;
	}

	public void setFieldsUsed(String fieldsUsed) {
		this.fieldsUsed = fieldsUsed;
	}

	@Column(name = "DATA_SET")
	public Integer getDataSet() {
		return this.dataSet;
	}

	public void setDataSet(Integer dataSet) {
		this.dataSet = dataSet;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "CLASSIFICATION")
	public Integer getClassification() {
		return this.classification;
	}

	public void setClassification(Integer classification) {
		this.classification = classification;
	}

	@Column(name = "ADDITIONAL_FORMAT")
	public Integer getAdditionalFormat() {
		return this.additionalFormat;
	}

	public void setAdditionalFormat(Integer additionalFormat) {
		this.additionalFormat = additionalFormat;
	}

	@Column(name = "PRINTER", length = 8)
	public String getPrinter() {
		return this.printer;
	}

	public void setPrinter(String printer) {
		this.printer = printer;
	}

}
