
CREATE TABLE [dbo].[SAS_ISIN](
	[SAS_ISIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ISIN] [varchar](50) NOT NULL,
	[CURRENCY] [varchar](3) NOT NULL,
	[STATUS_CD] [varchar](10) NULL,
	[CREATED_DT] [date] NOT NULL,
 CONSTRAINT [PK_SAS_ISIN] PRIMARY KEY CLUSTERED 
(
	[SAS_ISIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


