SET IDENTITY_INSERT STEP ON;

INSERT INTO STEP (STEP_ID, STEP_WORKFLOW) VALUES (28, 'Follow-up');

SET IDENTITY_INSERT STEP OFF;

SET IDENTITY_INSERT CHECK_WORKFLOW ON;

INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF]) VALUES (127, 'Comment', NULL, 'Text',NULL,NULL,NULL);

INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
		   VALUES (128, 'The documents have been returned and signed',NULL,'YesNo',NULL,NULL,NULL);

--127 et 128 - step 28 - label 13

INSERT INTO CHECK_STEP VALUES (128,28,1,1,10,0,13,NULL,NULL);

INSERT INTO CHECK_STEP VALUES (127,28,1,0,20,0,13,NULL,NULL);

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;
