/****** Object:  Table [dbo].[REJECT_DATA]    Script Date: 30/11/2017 5:49:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REJECT_DATA](
	[REJECT_DATA_ID] [int] IDENTITY(1,1) NOT NULL,
	[WORKFLOW_ITEM_ID] [int] NOT NULL,
	[STEP_ID] [int] NOT NULL,
	[REJECT_COMMENT] [varchar](1000) NOT NULL,
	[CREATION_USER] [varchar](5) NOT NULL,
	[CREATION_DT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REJECT_DATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
