alter table [dbo].[TRANSACTION_TAX_DETAILS] alter column [SPLIT_PERCENT] decimal(11,8)
GO

CREATE NONCLUSTERED INDEX [I_TTD_TRN_ID] ON [dbo].[TRANSACTION_TAX_DETAILS]
(
	[TRN_TAX_ID] ASC
)
GO

CREATE NONCLUSTERED INDEX [I_TT_POL_ID] ON [dbo].[TRANSACTION_TAX]
(
	[POLICY] ASC
)
GO

CREATE NONCLUSTERED INDEX [I_TT_ORI_ID] ON [dbo].[TRANSACTION_TAX]
(
	[ORIGIN_ID] ASC
)
GO
