INSERT INTO CODE_LABEL VALUES ('AM_STR','PROFIL','Risk Profile'); 
INSERT INTO CODE_LABEL VALUES('AM_STR','CURRENCY','Risk Currency'); 
INSERT INTO CODE_LABEL VALUES('AM_STR','INVEST_CAT','Invest Cat'); 
INSERT INTO CODE_LABEL VALUES('AM_STR','ALTER_FUND','Alternative Fund'); 
