-- Rachat total
-- Questions
-- Step New 99
SET IDENTITY_INSERT CHECK_WORKFLOW ON;

insert into CHECK_WORKFLOW (CHECK_ID, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE,DEFAULTVALUE,CHECKCODE,COMMENTIF)
 values (195,'Securities Transfer',NULL,'YesNo',NULL,'SEC_TRANSFER',NULL);

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;

 -- SECURITIES_TRANSFER
 Insert into CHECK_STEP VALUES (195, 99, 1,1,10, 1,13,NULL,'SECURITIES_TRANSFER');
