

CREATE TABLE [dbo].[ENCASHMENT_FUND_FORM](
	[CASH_FUND_FORM_ID] [int] IDENTITY(1,1) NOT NULL,
	[FORM_ID] [int] NOT NULL,
	[FUND_ID] [varchar](8) NOT NULL,
	[CASH_AMT] [money] NOT NULL,
	[CASH_DT] [date] NOT NULL,
	[CASH_CURRENCY] [char](3) NOT NULL,
	[CASH_STATUS] [varchar](10) NOT NULL,
	[CREATION_USER] [varchar](5) NULL,
	[CREATION_DT] [datetime] NULL,
	[UPDATE_USER] [varchar](10) NULL,
	[UPDATE_DT] [datetime] NULL,
 CONSTRAINT [PK_ENCASHMENT_FUND_FORM] PRIMARY KEY CLUSTERED 
(
	[CASH_FUND_FORM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

