-- Rachat partiel
-- Questions
-- Step New 82
SET IDENTITY_INSERT CHECK_WORKFLOW ON;

insert into CHECK_WORKFLOW (CHECK_ID, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE,DEFAULTVALUE,CHECKCODE,COMMENTIF)
 values (184,'Securities Transfer',NULL,'YesNoNa',NULL,'SEC_TRANSFER',NULL);

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;

 -- SECURITIES_TRANSFER
 Insert into CHECK_STEP VALUES (184, 82, 1,1,10, 1,13,NULL,'SECURITIES_TRANSFER');
