CREATE TABLE [dbo].[STEP_COMMENT](
	[STEP_COMMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[WORKFLOW_ITEM_ID] [int] NOT NULL,
	[STEP_ID] [int] NOT NULL,
	[COMMENT] [varchar](1000) NOT NULL,
	[DUE_DT] [datetime] NULL,
	[CREATION_USER] [varchar](5) NULL,
	[CREATION_DT] [datetime] NULL,
	[UPDATE_USER] [varchar](5) NULL,
	[UPDATE_DT] [datetime] NULL,
 CONSTRAINT [PK_CHECK_COMMENT] PRIMARY KEY CLUSTERED 
(
	[STEP_COMMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

