ALTER TABLE APP_FORM ADD POLICY_TRANSFER smallint null;

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[POLICY_TRANSFER_FORM](
	[POLICY_TRANSFER_FORM_ID] [int] IDENTITY(1,1) NOT NULL,
	[FORM_ID] [int] NOT NULL,
	[FROM_POLICY] [varchar](14) NOT NULL,
	[FROM_POLICY_EFFECT_DT] [datetime] NOT NULL,
	[CREATION_USER] [varchar](5) NULL,
	[CREATION_DT] [datetime] NULL,
	[UPDATE_USER] [varchar](10) NULL,
	[UPDATE_DT] [datetime] NULL,
CONSTRAINT [PK_POLICY_TRANSFER_FORM] PRIMARY KEY CLUSTERED 
(
	[POLICY_TRANSFER_FORM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

