  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_DEST nvarchar(20);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_TITLE nvarchar(20);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_FIRST_NAME nvarchar(40);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_LAST_NAME nvarchar(40);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_ADDR_LINE_1 nvarchar(50);
  
  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_ADDR_LINE_2 nvarchar(50);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_ADDR_LINE_3 nvarchar(50);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_ADDR_LINE_4 nvarchar(50);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_POSTCODE nvarchar(12);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_TOWN nvarchar(30);

  ALTER TABLE [dbo].[TRANSACTION_TAX_SENDING]
  ALTER COLUMN SND_COUNTRY nvarchar(30);