  Insert into step values ('New',15,0,0,1,0)
  Insert into step values ('Analysis',15,0,0,1,0)
  Insert into step values ('Validate Analysis',15,1,0,0,0)
  Insert into step values ('Acceptance',15,1,0,0,1)
  Insert into step values ('Request to Client/Partner',15,1,0,1,0)
  Insert into step values ('Acceptance Bis',15,1,0,0,1)
  Insert into step values ('Awaiting Cash/Transfer/Fees',15,0,0,1,0)
  Insert into step values ('Complete Analysis',15,0,0,1,0)
  Insert into step values ('Validate Input',15,1,0,0,0)
  Insert into step values ('Awaiting Cash Wealins Account/NAV and date',15,1,0,1,0)
  Insert into step values ('Awaiting Valuation',15,0,1,1,0)
  Insert into step values ('Review Documentation',15,0,0,0,1)
  Insert into step values ('Generate Documentation',15,0,1,0,0)
  Insert into step values ('Check Documentation and Payment',15,0,0,1,1)
  Insert into step values ('Validate Documentation',15,1,0,0,0)
  Insert into step values ('Sending',15,1,0,0,0)
