update CHECK_WORKFLOW set CHECK_DESC = 'MOV 1. The surrender occurs within two years of the subscription' where CHECK_DESC like 'MOV 1 - The surrender occurs within two years of the subscription';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 12. The client practices a sensitive profession/activity' where CHECK_DESC like 'MOV 12- The client practices a sensitive profession/activity';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 13. The contract was declared to the public prosecutor' where CHECK_DESC like 'MOV 13 - The contract was declared to the public prosecutor';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 14. The requested operation is atypical (cash payment via third party account etc.)' where CHECK_DESC like 'MOV 14 - The requested operation is atypical (cash payment via third party account etc.)';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 15. The terrorism / PEP check on the policyholder / insured person / beneficiary has indicated a positive alert' where CHECK_DESC like 'MOV 15 - The terrorism / PEP check on the policyholder / insured person / beneficiary has indicated a positive alert';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 2. The surrender leads to economically disproportionate penalties' where CHECK_DESC like 'MOV 2 -The surrender leads to economically disproportionate penalties';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 4. The beneficiary clause is in favour of a legal person (trading company or charitable organization or heritage structure (Trust, BVI, etc.))' where CHECK_DESC like 'MOV 4 - The beneficiary clause is in favour of a legal person (trading company or charitable organization or heritage structure (Trust, BVI, etc.))';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 5. The beneficiary clause is in favour of a natural person if the contract was subscribed by a legal person' where CHECK_DESC like 'MOV 5 - The beneficiary clause is in favour of a natural person if the contract was subscribed by a legal person';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 6. The beneficiary clause is in favour of a third party whose family ties are not established' where CHECK_DESC like 'MOV 6 -The beneficiary clause is in favour of a third party whose family ties are not established';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 7. The contract was pledged after subscription' where CHECK_DESC like 'MOV 7 - The contract was pledged after subscription';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 10. The additional premium brings the contract value to 100,000.00 EUR or more' where CHECK_DESC like 'MOV-10 The additional premium brings the contract value to 100,000.00 EUR or more';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 11. - LPS 9. The file presents another atypical element relating to the premium payment' where CHECK_DESC like 'MOV-11 - LPS 9. The file presents another atypical element relating to the premium payment';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 11. The premium is paid in cash, by cheque or physical remittance of securities' where CHECK_DESC like 'MOV-11 - The premium is paid in cash, by cheque or physical remittance of securities';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 11. The premium is paid via the account of a third party' where CHECK_DESC like 'MOV-11 - The premium is paid via the account of a third party';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 11. The premium payment has one of the criteria : LPS-6, LPS-7, LPS-9' where CHECK_DESC like 'MOV-11 The premium payment has one of the criteria : LPS-6, LPS-7, LPS-9';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 17. The contract shows frequent and unexplained movements of funds from different banking institutions or from different countries' where CHECK_DESC like 'MOV-17 The contract shows frequent and unexplained movements of funds from different banking institutions or from different countries';
update CHECK_WORKFLOW set CHECK_DESC = 'MOV 9. The annual premium or guarantie is doubled' where CHECK_DESC like 'MOV-9 The annual premium or guarantie is doubled';

