-- Rachat total
-- Questions
SET IDENTITY_INSERT CHECK_WORKFLOW ON;

insert into CHECK_WORKFLOW (CHECK_ID, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE,DEFAULTVALUE,CHECKCODE,COMMENTIF)
 values (318,'Securities transfer before debit of financial fees',NULL,'YesNo',NULL,'SEC_TFT_BEFORE_FF',NULL);
insert into CHECK_WORKFLOW (CHECK_ID, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE,DEFAULTVALUE,CHECKCODE,COMMENTIF)
 values (324,'financial fees directly debited by AM (without invoice)',NULL,'YesNo',NULL,'FIN_FEES_DEBITED_AM',NULL);

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;

 -- FINANCIAL_FEES_DEBITED_BY_AM_WITHOUT_INVOICE
 Insert into CHECK_STEP VALUES (318, 100, 1,1,80, 0,28,NULL,NULL);
 Insert into CHECK_STEP VALUES (324, 100, 1,1,100, 0,28,NULL,NULL);