CREATE TABLE [dbo].[SAS_ORDER_AGG](
	[SAS_ORDRE_AGG_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORIGIN] [varchar](10) NOT NULL,
	[LINE_ID] [varchar](60) NOT NULL,
	[GRP_ID] [varchar](60) NOT NULL,
	[CANCEL_ID] [varchar](60) NULL,
	[EVENT_TYPE] [varchar](10) NOT NULL,
	[TRANSACTION_TYPE] [varchar](8) NOT NULL,
	[NATURE_ID] [varchar](8) NOT NULL,
	[SECURITY_ID] [varchar](50) NOT NULL,
	[CONTRACT_ID] [varchar](60) NULL,
	[POLICY_ID] [varchar](30) NULL,
	[PORTFOLIO_CD] [varchar](30) NULL,
	[SCT_CD] [varchar](30) NULL,
	[ENTRY_DT] [date] NOT NULL,
	[VALUATION_DT] [date] NOT NULL,
	[QUANTITY] [numeric](18, 10) NULL,
	[AMOUNT] [numeric](18, 5) NULL,
	[AMOUNT_CURRENCY] [varchar](3) NULL,
	[NAV] [numeric](18, 10) NULL,
	[NAV_DT] [date] NULL,
	[INVESTMENT_FLG] [char](1) NOT NULL,
	[CONVERSION_FLG] [char](1) NOT NULL,
	[TECH_CANCEL_FLG] [char](1) NOT NULL,
	[CANCEL_FLG] [char](1) NOT NULL,
	[ESTIM_FLG] [char](1) NOT NULL,
	[QTE_FLG] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SAS_ORDRE_AGG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]