update STEP SET STEP_ABORTABLE=0 where STEP_WORKFLOW='New' and WORKFLOW_ITEM_TYPE_ID=12
update STEP SET STEP_ABORTABLE=0 where STEP_WORKFLOW='Registration' and WORKFLOW_ITEM_TYPE_ID=12
update STEP SET STEP_ABORTABLE=0 where STEP_WORKFLOW='Review Documentation' and WORKFLOW_ITEM_TYPE_ID=12