update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Registration';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Waiting Dispatch';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'New';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Unblocked Analysis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Unblocked Validate Analysis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Unblocked Acceptance';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Unblocked Request to Client/Partner';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Analysis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Scanning';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Check Registration';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Validate Analysis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Medical Acceptance';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Check Portfolio';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Acceptance';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Acceptance Bis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Request to Client/Partner';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Account Opening Request';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Awaiting Account Opening';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Premium Transfer Request';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Validate Input';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Awaiting Premium';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Generate Mandat de Gestion';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Acceptation Premium';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Premium Input and NAV';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Validate Premium and NAV';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Awaiting Valuation';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Generate Documentation';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Check Documentation';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Update Input';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Regularisation Conditional approval';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Validate Documentation';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Sending';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 7 and STEP_WORKFLOW = 'Follow-up';

update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Analysis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Validate Analysis and Input';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Acceptance';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Request to Client/Partner';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Acceptance Bis';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Awaiting Activation';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Generate Documentation';
update STEP set STEP_ABORTABLE = 'true' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Check Documentation';
update STEP set STEP_ABORTABLE = 'false' where WORKFLOW_ITEM_TYPE_ID = 11 and STEP_WORKFLOW = 'Sending';

ALTER TABLE STEP ALTER COLUMN STEP_ABORTABLE BIT NOT NULL;