USE [BATCH_UAT]
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION](
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[VERSION] [bigint] NULL,
	[JOB_INSTANCE_ID] [bigint] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[STATUS] [varchar](10) NULL,
	[EXIT_CODE] [varchar](2500) NULL,
	[EXIT_MESSAGE] [varchar](2500) NULL,
	[LAST_UPDATED] [datetime] NULL,
	[JOB_CONFIGURATION_LOCATION] [varchar](2500) NULL,
PRIMARY KEY CLUSTERED 
(
	[JOB_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION_CONTEXT]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION_CONTEXT](
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[SHORT_CONTEXT] [varchar](2500) NOT NULL,
	[SERIALIZED_CONTEXT] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[JOB_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION_PARAMS]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS](
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[TYPE_CD] [varchar](6) NOT NULL,
	[KEY_NAME] [varchar](100) NOT NULL,
	[STRING_VAL] [varchar](250) NULL,
	[DATE_VAL] [datetime] NULL,
	[LONG_VAL] [bigint] NULL,
	[DOUBLE_VAL] [float] NULL,
	[IDENTIFYING] [char](1) NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION_SEQ]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION_SEQ](
	[ID] [bigint] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BATCH_JOB_INSTANCE]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_JOB_INSTANCE](
	[JOB_INSTANCE_ID] [bigint] NOT NULL,
	[VERSION] [bigint] NULL,
	[JOB_NAME] [varchar](100) NOT NULL,
	[JOB_KEY] [varchar](32) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[JOB_INSTANCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [JOB_INST_UN] UNIQUE NONCLUSTERED 
(
	[JOB_NAME] ASC,
	[JOB_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCH_JOB_SEQ]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_JOB_SEQ](
	[ID] [bigint] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BATCH_STEP_EXECUTION]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_STEP_EXECUTION](
	[STEP_EXECUTION_ID] [bigint] NOT NULL,
	[VERSION] [bigint] NOT NULL,
	[STEP_NAME] [varchar](100) NOT NULL,
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NULL,
	[STATUS] [varchar](10) NULL,
	[COMMIT_COUNT] [bigint] NULL,
	[READ_COUNT] [bigint] NULL,
	[FILTER_COUNT] [bigint] NULL,
	[WRITE_COUNT] [bigint] NULL,
	[READ_SKIP_COUNT] [bigint] NULL,
	[WRITE_SKIP_COUNT] [bigint] NULL,
	[PROCESS_SKIP_COUNT] [bigint] NULL,
	[ROLLBACK_COUNT] [bigint] NULL,
	[EXIT_CODE] [varchar](2500) NULL,
	[EXIT_MESSAGE] [varchar](2500) NULL,
	[LAST_UPDATED] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[STEP_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCH_STEP_EXECUTION_CONTEXT]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_STEP_EXECUTION_CONTEXT](
	[STEP_EXECUTION_ID] [bigint] NOT NULL,
	[SHORT_CONTEXT] [varchar](2500) NOT NULL,
	[SERIALIZED_CONTEXT] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[STEP_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BATCH_STEP_EXECUTION_SEQ]    Script Date: 23/08/2017 16:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_STEP_EXECUTION_SEQ](
	[ID] [bigint] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION] ADD  DEFAULT (NULL) FOR [START_TIME]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION] ADD  DEFAULT (NULL) FOR [END_TIME]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS] ADD  DEFAULT (NULL) FOR [DATE_VAL]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION] ADD  DEFAULT (NULL) FOR [END_TIME]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION]  WITH CHECK ADD  CONSTRAINT [JOB_INST_EXEC_FK] FOREIGN KEY([JOB_INSTANCE_ID])
REFERENCES [dbo].[BATCH_JOB_INSTANCE] ([JOB_INSTANCE_ID])
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION] CHECK CONSTRAINT [JOB_INST_EXEC_FK]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_CONTEXT]  WITH CHECK ADD  CONSTRAINT [JOB_EXEC_CTX_FK] FOREIGN KEY([JOB_EXECUTION_ID])
REFERENCES [dbo].[BATCH_JOB_EXECUTION] ([JOB_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_CONTEXT] CHECK CONSTRAINT [JOB_EXEC_CTX_FK]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS]  WITH CHECK ADD  CONSTRAINT [JOB_EXEC_PARAMS_FK] FOREIGN KEY([JOB_EXECUTION_ID])
REFERENCES [dbo].[BATCH_JOB_EXECUTION] ([JOB_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS] CHECK CONSTRAINT [JOB_EXEC_PARAMS_FK]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION]  WITH CHECK ADD  CONSTRAINT [JOB_EXEC_STEP_FK] FOREIGN KEY([JOB_EXECUTION_ID])
REFERENCES [dbo].[BATCH_JOB_EXECUTION] ([JOB_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION] CHECK CONSTRAINT [JOB_EXEC_STEP_FK]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION_CONTEXT]  WITH CHECK ADD  CONSTRAINT [STEP_EXEC_CTX_FK] FOREIGN KEY([STEP_EXECUTION_ID])
REFERENCES [dbo].[BATCH_STEP_EXECUTION] ([STEP_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION_CONTEXT] CHECK CONSTRAINT [STEP_EXEC_CTX_FK]
GO
