UPDATE SAP SET SAP.status = COMMISSION_TO_PAY.status
from SAP_OPEN_BALANCE SAP
INNER JOIN COMMISSION_TO_PAY ON left(origin_id,8) = REFERENCE
where COMMISSION_TO_PAY.STATUS='Done';

UPDATE SAP SET SAP.status = COMMISSION_TO_PAY.status
from SAP_OPEN_BALANCE SAP
INNER JOIN COMMISSION_TO_PAY ON left(origin_id,8) = REFERENCE
where COMMISSION_TO_PAY.STATUS='Validated';