package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Where;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ProductLineEntity generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_LINES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class ProductLineEntity implements java.io.Serializable {

	private static final long serialVersionUID = -5079799328147492821L;

	private String prlId;
	private ProductEntity product;
	private String name;
	private Integer type;
	private Integer allowTermination;
	private String classification;
	private Integer allowWaiverPmt;
	private Integer allowTpd;
	private Integer allowSurrender;
	private Integer allowPaidUp;
	private Integer allowRip;
	private Integer allowMaturity;
	private Integer allowSwitching;
	private Integer allowExpiry;
	private Integer allowPremiumHoliday;
	private Integer allowBenefits;
	private Integer allowLoans;
	private Integer value0;
	private String centre;
	private Integer inclSaDisplay;
	private Integer primaryCoverage;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Integer allowWithdrawals;
	private Integer processingBasis;
	private String linkedProductLine;
	private Integer allowRevBonus;
	private Integer coverType;
	private Integer allowEndorsements;
	private Integer intTerm;
	private Integer processingType;
	private Integer allowCi;
	private Integer allowRi;
	private String treaty;
	private Set<ProductValueEntity> productValues = new HashSet<>(0);

	@Id
	@Column(name = "PRL_ID", unique = true, nullable = false, length = 12)
	public String getPrlId() {
		return this.prlId;
	}

	public void setPrlId(String prlId) {
		this.prlId = prlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PRODUCTSPRD_ID")
	public ProductEntity getProduct() {
		return this.product;
	}

	public void setProduct(ProductEntity product) {
		this.product = product;
	}

	@Column(name = "NAME", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "ALLOW_TERMINATION")
	public Integer getAllowTermination() {
		return this.allowTermination;
	}

	public void setAllowTermination(Integer allowTermination) {
		this.allowTermination = allowTermination;
	}

	@Column(name = "CLASSIFICATION", length = 3)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "ALLOW_WAIVER_PMT")
	public Integer getAllowWaiverPmt() {
		return this.allowWaiverPmt;
	}

	public void setAllowWaiverPmt(Integer allowWaiverPmt) {
		this.allowWaiverPmt = allowWaiverPmt;
	}

	@Column(name = "ALLOW_TPD")
	public Integer getAllowTpd() {
		return this.allowTpd;
	}

	public void setAllowTpd(Integer allowTpd) {
		this.allowTpd = allowTpd;
	}

	@Column(name = "ALLOW_SURRENDER")
	public Integer getAllowSurrender() {
		return this.allowSurrender;
	}

	public void setAllowSurrender(Integer allowSurrender) {
		this.allowSurrender = allowSurrender;
	}

	@Column(name = "ALLOW_PAID_UP")
	public Integer getAllowPaidUp() {
		return this.allowPaidUp;
	}

	public void setAllowPaidUp(Integer allowPaidUp) {
		this.allowPaidUp = allowPaidUp;
	}

	@Column(name = "ALLOW_RIP")
	public Integer getAllowRip() {
		return this.allowRip;
	}

	public void setAllowRip(Integer allowRip) {
		this.allowRip = allowRip;
	}

	@Column(name = "ALLOW_MATURITY")
	public Integer getAllowMaturity() {
		return this.allowMaturity;
	}

	public void setAllowMaturity(Integer allowMaturity) {
		this.allowMaturity = allowMaturity;
	}

	@Column(name = "ALLOW_SWITCHING")
	public Integer getAllowSwitching() {
		return this.allowSwitching;
	}

	public void setAllowSwitching(Integer allowSwitching) {
		this.allowSwitching = allowSwitching;
	}

	@Column(name = "ALLOW_EXPIRY")
	public Integer getAllowExpiry() {
		return this.allowExpiry;
	}

	public void setAllowExpiry(Integer allowExpiry) {
		this.allowExpiry = allowExpiry;
	}

	@Column(name = "ALLOW_PREMIUM_HOLIDAY")
	public Integer getAllowPremiumHoliday() {
		return this.allowPremiumHoliday;
	}

	public void setAllowPremiumHoliday(Integer allowPremiumHoliday) {
		this.allowPremiumHoliday = allowPremiumHoliday;
	}

	@Column(name = "ALLOW_BENEFITS")
	public Integer getAllowBenefits() {
		return this.allowBenefits;
	}

	public void setAllowBenefits(Integer allowBenefits) {
		this.allowBenefits = allowBenefits;
	}

	@Column(name = "ALLOW_LOANS")
	public Integer getAllowLoans() {
		return this.allowLoans;
	}

	public void setAllowLoans(Integer allowLoans) {
		this.allowLoans = allowLoans;
	}

	@Column(name = "VALUE0")
	public Integer getValue0() {
		return this.value0;
	}

	public void setValue0(Integer value0) {
		this.value0 = value0;
	}

	@Column(name = "CENTRE", length = 10)
	public String getCentre() {
		return this.centre;
	}

	public void setCentre(String centre) {
		this.centre = centre;
	}

	@Column(name = "INCL_SA_DISPLAY")
	public Integer getInclSaDisplay() {
		return this.inclSaDisplay;
	}

	public void setInclSaDisplay(Integer inclSaDisplay) {
		this.inclSaDisplay = inclSaDisplay;
	}

	@Column(name = "PRIMARY_COVERAGE")
	public Integer getPrimaryCoverage() {
		return this.primaryCoverage;
	}

	public void setPrimaryCoverage(Integer primaryCoverage) {
		this.primaryCoverage = primaryCoverage;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "ALLOW_WITHDRAWALS")
	public Integer getAllowWithdrawals() {
		return this.allowWithdrawals;
	}

	public void setAllowWithdrawals(Integer allowWithdrawals) {
		this.allowWithdrawals = allowWithdrawals;
	}

	@Column(name = "PROCESSING_BASIS")
	public Integer getProcessingBasis() {
		return this.processingBasis;
	}

	public void setProcessingBasis(Integer processingBasis) {
		this.processingBasis = processingBasis;
	}

	@Column(name = "LINKED_PRODUCT_LINE", length = 12)
	public String getLinkedProductLine() {
		return this.linkedProductLine;
	}

	public void setLinkedProductLine(String linkedProductLine) {
		this.linkedProductLine = linkedProductLine;
	}

	@Column(name = "ALLOW_REV_BONUS")
	public Integer getAllowRevBonus() {
		return this.allowRevBonus;
	}

	public void setAllowRevBonus(Integer allowRevBonus) {
		this.allowRevBonus = allowRevBonus;
	}

	@Column(name = "COVER_TYPE")
	public Integer getCoverType() {
		return this.coverType;
	}

	public void setCoverType(Integer coverType) {
		this.coverType = coverType;
	}

	@Column(name = "ALLOW_ENDORSEMENTS")
	public Integer getAllowEndorsements() {
		return this.allowEndorsements;
	}

	public void setAllowEndorsements(Integer allowEndorsements) {
		this.allowEndorsements = allowEndorsements;
	}

	@Column(name = "SHORT_TERM")
	public Integer getIntegerTerm() {
		return this.intTerm;
	}

	public void setIntegerTerm(Integer intTerm) {
		this.intTerm = intTerm;
	}

	@Column(name = "PROCESSING_TYPE")
	public Integer getProcessingType() {
		return this.processingType;
	}

	public void setProcessingType(Integer processingType) {
		this.processingType = processingType;
	}

	@Column(name = "ALLOW_CI")
	public Integer getAllowCi() {
		return this.allowCi;
	}

	public void setAllowCi(Integer allowCi) {
		this.allowCi = allowCi;
	}

	@Column(name = "ALLOW_RI")
	public Integer getAllowRi() {
		return this.allowRi;
	}

	public void setAllowRi(Integer allowRi) {
		this.allowRi = allowRi;
	}

	@Column(name = "TREATY", length = 8)
	public String getTreaty() {
		return this.treaty;
	}

	public void setTreaty(String treaty) {
		this.treaty = treaty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productLine")
	@Where(clause = "VALUE_FROM > 1")
	public Set<ProductValueEntity> getProductValues() {
		return this.productValues;
	}

	public void setProductValues(Set<ProductValueEntity> productValues) {
		this.productValues = productValues;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prlId == null) ? 0 : prlId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductLineEntity other = (ProductLineEntity) obj;
		if (prlId == null) {
			if (other.prlId != null)
				return false;
		} else if (!prlId.equals(other.prlId))
			return false;
		return true;
	}

}
