package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * CliContactChangeEntity generated by hbm2java
 */
@Entity
@Table(name = "CLI_CONTACT_CHANGES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class CliContactChangeEntity implements java.io.Serializable {

	private long cccId;
	private ClientContactDetailEntity clientContactDetail;
	private String contactType;
	private String salutation;
	private String createdProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private Long clientId;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String town;
	private String county;
	private String country;
	private String postcode;
	private String fax;
	private String homePhone;
	private String email;
	private Date dateOfCountryChange;
	private String previousCountry;

	@Id
	@Column(name = "CCC_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getCccId() {
		return this.cccId;
	}

	public void setCccId(long cccId) {
		this.cccId = cccId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLIENT_CONTACLC_ID")
	@NotFound(action = NotFoundAction.IGNORE)
	public ClientContactDetailEntity getClientContactDetail() {
		return this.clientContactDetail;
	}

	public void setClientContactDetail(ClientContactDetailEntity clientContactDetail) {
		this.clientContactDetail = clientContactDetail;
	}

	@Column(name = "CONTACT_TYPE", length = 10)
	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	@Column(name = "SALUTATION", length = 40)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CLIENT_ID", precision = 10, scale = 0)
	public Long getClientId() {
		return this.clientId;
	}

	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	@Column(name = "ADDRESS_LINE_1", length = 40)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE_2", length = 40)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "ADDRESS_LINE_3", length = 40)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "ADDRESS_LINE_4", length = 40)
	public String getAddressLine4() {
		return this.addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Column(name = "TOWN", length = 30)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Column(name = "COUNTY", length = 30)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "COUNTRY", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "POSTCODE", length = 12)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "HOME_PHONE", length = 20)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "EMAIL", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_COUNTRY_CHANGE")
	public Date getDateOfCountryChange() {
		return dateOfCountryChange;
	}

	public void setDateOfCountryChange(Date dateOfCountryChange) {
		this.dateOfCountryChange = dateOfCountryChange;
	}
	
	@Column(name = "PREVIOUS_COUNTRY", length=30, nullable=false)
	public String getPreviousCountry() {
		return previousCountry;
	}

	public void setPreviousCountry(String previousCountry) {
		this.previousCountry = previousCountry;
	}

}
