package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UoptDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "UOPT_DETAILS")
public class UoptDetailEntity implements java.io.Serializable {

	private String uddId;
	private UoptDefinitionEntity uoptDefinition;
	private String groupId;
	private String keyValue;
	private String description;
	private Integer status;
	private Integer definition;
	private Integer default0;
	private Integer type;
	private Character system;
	private Integer action0;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;

	@Id
	@Column(name = "UDD_ID", unique = true, nullable = false, length = 24)
	public String getUddId() {
		return this.uddId;
	}

	public void setUddId(String uddId) {
		this.uddId = uddId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_UOPT_DEFINITUDF_ID")
	public UoptDefinitionEntity getUoptDefinition() {
		return this.uoptDefinition;
	}

	public void setUoptDefinition(UoptDefinitionEntity uoptDefinition) {
		this.uoptDefinition = uoptDefinition;
	}

	@Column(name = "GROUP_ID", length = 15)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "KEY_VALUE", length = 8)
	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 35)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "DEFINITION")
	public Integer getDefinition() {
		return this.definition;
	}

	public void setDefinition(Integer definition) {
		this.definition = definition;
	}

	@Column(name = "DEFAULT0")
	public Integer getDefault0() {
		return this.default0;
	}

	public void setDefault0(Integer default0) {
		this.default0 = default0;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "SYSTEM", length = 1)
	public Character getSystem() {
		return this.system;
	}

	public void setSystem(Character system) {
		this.system = system;
	}

	@Column(name = "ACTION0")
	public Integer getAction0() {
		return this.action0;
	}

	public void setAction0(Integer action0) {
		this.action0 = action0;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

}
