package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "EVENT_DETAILS"

)
public class EventDetailEntity implements java.io.Serializable {

	private String evdId;
	private Integer type;
	private Integer noDocumentation;
	private String name;
	private Integer pcon1;
	private Integer ncon1;
	private String polac11;
	private String comac11;
	private String unacc11;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;

	@Id
	@Column(name = "EVD_ID", unique = true, nullable = false, length = 15)
	public String getEvdId() {
		return this.evdId;
	}

	public void setEvdId(String evdId) {
		this.evdId = evdId;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "NO_DOCUMENTATION")
	public Integer getNoDocumentation() {
		return this.noDocumentation;
	}

	public void setNoDocumentation(Integer noDocumentation) {
		this.noDocumentation = noDocumentation;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PCON_1")
	public Integer getPcon1() {
		return this.pcon1;
	}

	public void setPcon1(Integer pcon1) {
		this.pcon1 = pcon1;
	}

	@Column(name = "NCON_1")
	public Integer getNcon1() {
		return this.ncon1;
	}

	public void setNcon1(Integer ncon1) {
		this.ncon1 = ncon1;
	}

	@Column(name = "POLAC1_1", length = 4)
	public String getPolac11() {
		return this.polac11;
	}

	public void setPolac11(String polac11) {
		this.polac11 = polac11;
	}

	@Column(name = "COMAC1_1", length = 4)
	public String getComac11() {
		return this.comac11;
	}

	public void setComac11(String comac11) {
		this.comac11 = comac11;
	}

	@Column(name = "UNACC1_1", length = 4)
	public String getUnacc11() {
		return this.unacc11;
	}

	public void setUnacc11(String unacc11) {
		this.unacc11 = unacc11;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
