
-- Steps automatiques 
Update STEP set STEP_AUTOMATIC = 1 Where STEP_ID =67;


-- Awaiting Premium - Commentaire
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 63, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, VISIBLEIF, METADATA
from CHECK_STEP where STEP_ID in (17);

-- Premium Input and NAV - Commentaire--64
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 64, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where CHECK_ID in (165,166,167,168,169,170) and STEP_ID = 56;

Update CHECK_STEP set label_id = 13 WHERE STEP_ID = 64 and LABEL_ID = 18;
Update CHECK_STEP set CHECK_ORDER = 4 WHERE STEP_ID = 64 and CHECK_ID = 170;
Update CHECK_STEP set CHECK_ORDER = 3 WHERE STEP_ID = 64 and CHECK_ID = 169;


-- Validate additional premium 65
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 65, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 21;

-- Sending
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 71, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 34;

Delete from CHECK_STEP where STEP_ID = 71 and CHECK_ID = 46;

Update CHECK_STEP set CHECK_ID = 169, CHECK_ORDER = 10 where STEP_ID = 71 and CHECK_ID = 145;
Update CHECK_STEP set CHECK_ID = 170, CHECK_ORDER = 20 where STEP_ID = 71 and CHECK_ID = 146;
Update CHECK_STEP set CHECK_ID = 165, CHECK_ORDER = 30 where STEP_ID = 71 and CHECK_ID = 147;
Update CHECK_STEP set CHECK_ID = 166, CHECK_ORDER = 31 where STEP_ID = 71 and CHECK_ID = 148;
Update CHECK_STEP set CHECK_ID = 167, CHECK_ORDER = 32 where STEP_ID = 71 and CHECK_ID = 151;
Update CHECK_STEP set CHECK_ID = 168, CHECK_ORDER = 33 where STEP_ID = 71 and CHECK_ID = 149;
Update CHECK_STEP set CHECK_ID = 151, CHECK_ORDER = 40 where STEP_ID = 71 and CHECK_ID = 150;
Update CHECK_STEP set CHECK_ID = 149, CHECK_ORDER = 50 where STEP_ID = 71 and CHECK_ID = 152;

Insert into CHECK_STEP values (150,71,0,0,60,0,8,NULL,NULL);
Insert into CHECK_STEP values (152,71,0,0,70,0,8,NULL,NULL);
Insert into CHECK_STEP values (171,71,0,0,80,0,8,NULL,NULL);

-- Check Documentation
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 69, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 33;

update CHECK_STEP set check_id = 169 where STEP_ID = 69 and CHECK_ID = 145; 
update CHECK_STEP set check_id = 170 where STEP_ID = 69 and CHECK_ID = 146; 
update CHECK_STEP set check_id = 165 where STEP_ID = 69 and CHECK_ID = 147; 
update CHECK_STEP set check_id = 166 where STEP_ID = 69 and CHECK_ID = 148; 
update CHECK_STEP set check_id = 167 where STEP_ID = 69 and CHECK_ID = 151;
update CHECK_STEP set check_id = 168 where STEP_ID = 69 and CHECK_ID = 149; 
update CHECK_STEP set check_id = 151 where STEP_ID = 69 and CHECK_ID = 150;
update CHECK_STEP set check_id = 149 where STEP_ID = 69 and CHECK_ID = 152;

insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
VALUES (150,69,0,0,90,0,8,NULL,NULL);


insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
VALUES (152,69,0,0,100,0,8,NULL,NULL);


insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
VALUES (171,69,0,0,110,0,8,NULL,NULL);
 
Delete from CHECK_STEP where STEP_ID = 69 and CHECK_ID = 46;
 
-- Request to Client/Partner
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 57, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 12;

-- Acceptance BIS
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 58, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 11;

-- Account Opening Request
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 59, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 13;

delete from CHECK_STEP where STEP_ID = 59 and LABEL_ID = 8;

insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 59, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 61 and LABEL_ID = 8;

update CHECK_STEP set VISIBLEIF = 'ISNOTNULL' where STEP_ID = 59 and LABEL_ID = 25;

update CHECK_STEP set VISIBLEIF = 'ISNOTNULL' where STEP_ID = 59 and LABEL_ID = 22;

update CHECK_WORKFLOW set checkcode = 'LIGHT' where CHECK_ID = 159;

-- Awaiting Account Opening
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 60, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 59;

update CHECK_STEP set VISIBLEIF = 'ISNOTNULL' where STEP_ID = 60 and LABEL_ID = 25;

update CHECK_STEP set VISIBLEIF = 'ISNOTNULL' where STEP_ID = 60 and LABEL_ID = 22;

update CHECK_STEP set CHECK_ID = 114 where STEP_ID = 60 and CHECK_ID = 113;

update CHECK_STEP set CHECK_ID = 130 where STEP_ID = 60 and CHECK_ID = 129;

-- Acceptance 56
update CHECK_STEP set VISIBLEIF = NULL where VISIBLEIF = 'YES' and STEP_ID = 56;
update CHECK_STEP set CHECK_ORDER = 10 where STEP_ID = 56 and CHECK_ID = 169;
update CHECK_STEP set CHECK_ORDER = 20 where STEP_ID = 56 and CHECK_ID = 170;
update CHECK_STEP set CHECK_ORDER = 30 where STEP_ID = 56 and CHECK_ID = 165;
update CHECK_STEP set CHECK_ORDER = 31 where STEP_ID = 56 and CHECK_ID = 166;
update CHECK_STEP set CHECK_ORDER = 32 where STEP_ID = 56 and CHECK_ID = 167;
update CHECK_STEP set CHECK_ORDER = 33 where STEP_ID = 56 and CHECK_ID = 168;
Insert into CHECK_STEP values (151,56,0,0,40,0,18,NULL,NULL);
update CHECK_STEP set CHECK_ORDER = 50 where STEP_ID = 56 and CHECK_ID = 149;
update CHECK_STEP set CHECK_ORDER = 60 where STEP_ID = 56 and CHECK_ID = 150;
Insert into CHECK_STEP values (152,56,0,0,70,0,18,NULL,NULL);
update CHECK_STEP set CHECK_ORDER = 80 where STEP_ID = 56 and CHECK_ID = 171;

update CHECK_STEP set LABEL_ID = 13 where STEP_ID = 56 and CHECK_ID = 45;

update CHECK_STEP set CHECK_ORDER = 900 where STEP_ID = 56 and CHECK_ID = 112;

-- Premium Transfer Request
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 61, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 15 and LABEL_ID in (13,22);

insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 61, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, 8, NULL, METADATA
from CHECK_STEP where STEP_ID = 56 and LABEL_ID in (18);

Update CHECK_STEP set VISIBLEIF = 'ISNOTNULL' Where STEP_ID = 61 and label_id = 22;

-- Generate Management Mandate
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 62, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 18;


-- Tri Questions MOV sur Analysis


-- Ajout Missing documents 
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 54, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, 11, NULL, METADATA
from CHECK_STEP where STEP_ID = 53 and LABEL_ID = 4;

Update CHECK_STEP set VISIBLEIF = 'NO' where  STEP_ID = 54 and LABEL_ID = 11;

Update CHECK_STEP set CHECK_ORDER = 5 where step_id = 54 and CHECK_ID = 169;
Update CHECK_STEP set CHECK_ORDER = 6 where step_id = 54 and CHECK_ID = 170;
Update CHECK_STEP set CHECK_ORDER = 7 where step_id = 54 and CHECK_ID = 165;
Update CHECK_STEP set CHECK_ORDER = 8 where step_id = 54 and CHECK_ID = 166;
Update CHECK_STEP set CHECK_ORDER = 9 where step_id = 54 and CHECK_ID = 167;
Update CHECK_STEP set CHECK_ORDER = 10 where step_id = 54 and CHECK_ID = 168;
Update CHECK_STEP set CHECK_ORDER = 11 where step_id = 54 and CHECK_ID = 151;
Update CHECK_STEP set CHECK_ORDER = 12 where step_id = 54 and CHECK_ID = 149;
Update CHECK_STEP set CHECK_ORDER = 13 where step_id = 54 and CHECK_ID = 150;
Update CHECK_STEP set CHECK_ORDER = 14 where step_id = 54 and CHECK_ID = 152;
Update CHECK_STEP set CHECK_ORDER = 15 where step_id = 54 and CHECK_ID = 171;

-- 
Update CHECK_STEP set CHECK_ID = 175, VISIBLEIF = 'YES' where CHECK_ID = 157 and STEP_ID = 69;

-- Validate documentation 
insert into CHECK_STEP (CHECK_ID,STEP_ID,IS_UPDATABLE,IS_MANDATORY,CHECK_ORDER,IS_METADATA,LABEL_ID,VISIBLEIF,METADATA)
select check_id, 70, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, NULL, METADATA
from CHECK_STEP where STEP_ID = 26;

