ALTER TABLE TRANSFERS 
ALTER COLUMN POLICY_ID varchar(14);

ALTER TABLE TRANSFERS 
ALTER COLUMN FDS_ID varchar(8);

ALTER TABLE TRANSFERS 
ADD TRF_COMM_POL varchar(50);

ALTER TABLE TRANSFERS
ALTER COLUMN BROKER_ID varchar(8);