INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '1', 'EN', 'English')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '2', 'UD', 'User.Def')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '3', 'FR', 'French')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '4', 'PL', 'Polish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '5', 'CZ', 'Czech' )
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '6', 'TR', 'Turkish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '7', 'EN_NO', 'Norwegian')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '8', 'IT', 'Italian')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '9', 'DE', 'German')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '10', 'EN', 'Swedish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '11', 'NL', 'Flemish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '12', 'EN_ES', 'Spanish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '13', 'EN_PT', 'Portuguese')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', '14', 'DK', 'Danish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'NED', 'NL', 'Dutch')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'PRT', 'EN_PT', 'Portuguese')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'NOR', 'EN_NO', 'Norwegian')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'FIN', 'EN', 'Finnish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'FRA', 'FR', 'French')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'ENG', 'EN', 'English')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'LUX', 'FR', 'Luxembourguish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'DEU', 'DE', 'German')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'ESP', 'EN_ES', 'Spanish')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'GBR', 'EN', 'English')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'ITA', 'IT', 'Italian')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('DOCUMENT_LANGUAGE', 'SWE', 'EN', 'Swedish')
GO