
-- Appendix N/A
Update CHECK_WORKFLOW set CHECKCODE = NULL where CHECK_ID in (32,33);

-- GDPR
SET IDENTITY_INSERT CHECK_WORKFLOW ON;

insert into CHECK_WORKFLOW (CHECK_ID, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE,DEFAULTVALUE,CHECKCODE,COMMENTIF)
 values (186,'GDPR consent is signed by the insured person(s)',NULL,'YesNoNa',NULL,NULL,'NO');

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;

-- Ajout question GDPR sur Policy Check
INSERT INTO CHECK_STEP VALUES (186,54,1,1,3,0,27,'G|LIGHT==NO',NULL);





