INSERT INTO UOPT_DEFINITIONS (UDF_ID, NAME, STATUS, USEAGE, CREATED_BY, CREATED_DATE, CREATED_TIME,CREATED_PROCESS)
VALUES (66,'CRS Status', 1, 1, 'rvn', GETDATE(), GETDATE(),'WEBIA');

 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('AFINDCL','AFINDCL','Reporting Financial Institution',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);

 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('BFINNDCL','BFINNDCL','Non-Reporting Financial Institution ',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);


   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('CFINHCRS','CFINHCRS','Investment entity except CRS',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);


   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('DNFINAC','DNFINAC','Active non-financial entity',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);


   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('ENFINPAS','ENFINPAS','Passive non-financial entity',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('FFIDU','FFIDU','Fiduciary ',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);


   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('GTRUST','GTRUST','Trust',1,66,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 66,'',0);


 