package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PolicyCoverageEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_COVERAGES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class PolicyCoverageEntity implements java.io.Serializable {

	private String pocId;
	@JsonIgnore
	private PolicyEntity policy;
	private String policyId;
	private int coverage;
	private String productLine;
	private String currency;
	private BigDecimal initialSumAssured;
	private BigDecimal sumAssured;
	private Date dateSaSet;
	private Date dateOfValuation;
	private Integer majorCoverage;
	private Integer soldBasis;
	private BigDecimal multiplier;
	private String coverLevel;
	private Integer livesType;
	private Integer holdingNo;
	private BigDecimal term;
	private Integer retirementAge;
	private Integer termAge;
	private Date dateOfTermination;
	private Date dateOfApplication;
	private Date dateOfReqCommencement;
	private Date dateCommenced;
	private Integer localValues;
	private int status;
	private Integer subStatus;
	private Integer prevMajorStatus;
	private Integer prevMajorSubStatus;
	private Integer previousStatus;
	private Date statusChangeEffDate;
	private Integer statusChangeNo;
	private String createdBy;
	private String createdProcess;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Integer pptAge;
	private BigDecimal interestRate;
	private Integer coolOffDays;
	private BigDecimal valuation;
	private Integer pttYrs;
	private Date datePremiumTerm;
	private BigDecimal netInvestment;
	private Integer independence;
	private Integer dataCaptureCompleted;
	private Date actFundingTermDate;
	private Date dateNextSaChange;
	private Integer statusBasis;
	private Integer stream;
	private Integer processingType;
	private Long allocationRate;
	private Integer insuranceType;
	@JsonIgnore
	private Set<PolicyCvgLiveEntity> policyCvgLives = new HashSet<PolicyCvgLiveEntity>(0);
	@JsonIgnore
	private Set<ProductValueEntity> productValues = new HashSet<ProductValueEntity>(0);
	@JsonIgnore
	private Set<AccountTransactionEntity> accountTransactions = new HashSet<AccountTransactionEntity>(0);

	@Id
	@Column(name = "POC_ID", unique = true, nullable = false, length = 18)
	public String getPocId() {
		return this.pocId;
	}

	public void setPocId(String pocId) {
		this.pocId = pocId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "PRODUCT_LINE", nullable = false, length = 12)
	public String getProductLine() {
		return this.productLine;
	}

	public void setProductLine(String productLine) {
		this.productLine = productLine;
	}

	@Column(name = "CURRENCY", length = 5)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "INITIAL_SUM_ASSURED", precision = 15)
	public BigDecimal getInitialSumAssured() {
		return this.initialSumAssured;
	}

	public void setInitialSumAssured(BigDecimal initialSumAssured) {
		this.initialSumAssured = initialSumAssured;
	}

	@Column(name = "SUM_ASSURED", precision = 15)
	public BigDecimal getSumAssured() {
		return this.sumAssured;
	}

	public void setSumAssured(BigDecimal sumAssured) {
		this.sumAssured = sumAssured;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_SA_SET", length = 23)
	public Date getDateSaSet() {
		return this.dateSaSet;
	}

	public void setDateSaSet(Date dateSaSet) {
		this.dateSaSet = dateSaSet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_VALUATION", length = 23)
	public Date getDateOfValuation() {
		return this.dateOfValuation;
	}

	public void setDateOfValuation(Date dateOfValuation) {
		this.dateOfValuation = dateOfValuation;
	}

	@Column(name = "MAJOR_COVERAGE")
	public Integer getMajorCoverage() {
		return this.majorCoverage;
	}

	public void setMajorCoverage(Integer majorCoverage) {
		this.majorCoverage = majorCoverage;
	}

	@Column(name = "SOLD_BASIS")
	public Integer getSoldBasis() {
		return this.soldBasis;
	}

	public void setSoldBasis(Integer soldBasis) {
		this.soldBasis = soldBasis;
	}

	@Column(name = "MULTIPLIER", precision = 12, scale = 8)
	public BigDecimal getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(BigDecimal multiplier) {
		this.multiplier = multiplier;
	}

	@Column(name = "COVER_LEVEL", length = 3)
	public String getCoverLevel() {
		return this.coverLevel;
	}

	public void setCoverLevel(String coverLevel) {
		this.coverLevel = coverLevel;
	}

	@Column(name = "LIVES_TYPE")
	public Integer getLivesType() {
		return livesType;
	}

	public void setLivesType(Integer livesType) {
		this.livesType = livesType;
	}

	@Column(name = "HOLDING_NO")
	public Integer getHoldingNo() {
		return this.holdingNo;
	}

	public void setHoldingNo(Integer holdingNo) {
		this.holdingNo = holdingNo;
	}

	@Column(name = "TERM", precision = 7, scale = 4)
	public BigDecimal getTerm() {
		return this.term;
	}

	public void setTerm(BigDecimal term) {
		this.term = term;
	}

	@Column(name = "RETIREMENT_AGE")
	public Integer getRetirementAge() {
		return this.retirementAge;
	}

	public void setRetirementAge(Integer retirementAge) {
		this.retirementAge = retirementAge;
	}

	@Column(name = "TERM_AGE")
	public Integer getTermAge() {
		return this.termAge;
	}

	public void setTermAge(Integer termAge) {
		this.termAge = termAge;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_TERMINATION", length = 23)
	public Date getDateOfTermination() {
		return this.dateOfTermination;
	}

	public void setDateOfTermination(Date dateOfTermination) {
		this.dateOfTermination = dateOfTermination;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_APPLICATION", length = 23)
	public Date getDateOfApplication() {
		return this.dateOfApplication;
	}

	public void setDateOfApplication(Date dateOfApplication) {
		this.dateOfApplication = dateOfApplication;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_REQ_COMMENCEMENT", length = 23)
	public Date getDateOfReqCommencement() {
		return this.dateOfReqCommencement;
	}

	public void setDateOfReqCommencement(Date dateOfReqCommencement) {
		this.dateOfReqCommencement = dateOfReqCommencement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_COMMENCED", length = 23)
	public Date getDateCommenced() {
		return this.dateCommenced;
	}

	public void setDateCommenced(Date dateCommenced) {
		this.dateCommenced = dateCommenced;
	}

	@Column(name = "LOCAL_VALUES")
	public Integer getLocalValues() {
		return this.localValues;
	}

	public void setLocalValues(Integer localValues) {
		this.localValues = localValues;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "SUB_STATUS")
	public Integer getSubStatus() {
		return this.subStatus;
	}

	public void setSubStatus(Integer subStatus) {
		this.subStatus = subStatus;
	}

	@Column(name = "PREV_MAJOR_STATUS")
	public Integer getPrevMajorStatus() {
		return this.prevMajorStatus;
	}

	public void setPrevMajorStatus(Integer prevMajorStatus) {
		this.prevMajorStatus = prevMajorStatus;
	}

	@Column(name = "PREV_MAJOR_SUB_STATUS")
	public Integer getPrevMajorSubStatus() {
		return this.prevMajorSubStatus;
	}

	public void setPrevMajorSubStatus(Integer prevMajorSubStatus) {
		this.prevMajorSubStatus = prevMajorSubStatus;
	}

	@Column(name = "PREVIOUS_STATUS")
	public Integer getPreviousStatus() {
		return this.previousStatus;
	}

	public void setPreviousStatus(Integer previousStatus) {
		this.previousStatus = previousStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STATUS_CHANGE_EFF_DATE", length = 23)
	public Date getStatusChangeEffDate() {
		return this.statusChangeEffDate;
	}

	public void setStatusChangeEffDate(Date statusChangeEffDate) {
		this.statusChangeEffDate = statusChangeEffDate;
	}

	@Column(name = "STATUS_CHANGE_NO")
	public Integer getStatusChangeNo() {
		return this.statusChangeNo;
	}

	public void setStatusChangeNo(Integer statusChangeNo) {
		this.statusChangeNo = statusChangeNo;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "PPT_AGE")
	public Integer getPptAge() {
		return this.pptAge;
	}

	public void setPptAge(Integer pptAge) {
		this.pptAge = pptAge;
	}

	@Column(name = "INTEREST_RATE", precision = 9, scale = 4)
	public BigDecimal getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(BigDecimal interestRate) {
		this.interestRate = interestRate;
	}

	@Column(name = "COOL_OFF_DAYS")
	public Integer getCoolOffDays() {
		return this.coolOffDays;
	}

	public void setCoolOffDays(Integer coolOffDays) {
		this.coolOffDays = coolOffDays;
	}

	@Column(name = "VALUATION", precision = 15)
	public BigDecimal getValuation() {
		return this.valuation;
	}

	public void setValuation(BigDecimal valuation) {
		this.valuation = valuation;
	}

	@Column(name = "PTT_YRS")
	public Integer getPttYrs() {
		return this.pttYrs;
	}

	public void setPttYrs(Integer pttYrs) {
		this.pttYrs = pttYrs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PREMIUM_TERM", length = 23)
	public Date getDatePremiumTerm() {
		return this.datePremiumTerm;
	}

	public void setDatePremiumTerm(Date datePremiumTerm) {
		this.datePremiumTerm = datePremiumTerm;
	}

	@Column(name = "NET_INVESTMENT", precision = 15)
	public BigDecimal getNetInvestment() {
		return this.netInvestment;
	}

	public void setNetInvestment(BigDecimal netInvestment) {
		this.netInvestment = netInvestment;
	}

	@Column(name = "INDEPENDENCE")
	public Integer getIndependence() {
		return this.independence;
	}

	public void setIndependence(Integer independence) {
		this.independence = independence;
	}

	@Column(name = "DATA_CAPTURE_COMPLETED")
	public Integer getDataCaptureCompleted() {
		return this.dataCaptureCompleted;
	}

	public void setDataCaptureCompleted(Integer dataCaptureCompleted) {
		this.dataCaptureCompleted = dataCaptureCompleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACT_FUNDING_TERM_DATE", length = 23)
	public Date getActFundingTermDate() {
		return this.actFundingTermDate;
	}

	public void setActFundingTermDate(Date actFundingTermDate) {
		this.actFundingTermDate = actFundingTermDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_NEXT_SA_CHANGE", length = 23)
	public Date getDateNextSaChange() {
		return this.dateNextSaChange;
	}

	public void setDateNextSaChange(Date dateNextSaChange) {
		this.dateNextSaChange = dateNextSaChange;
	}

	@Column(name = "STATUS_BASIS")
	public Integer getStatusBasis() {
		return this.statusBasis;
	}

	public void setStatusBasis(Integer statusBasis) {
		this.statusBasis = statusBasis;
	}

	@Column(name = "STREAM")
	public Integer getStream() {
		return this.stream;
	}

	public void setStream(Integer stream) {
		this.stream = stream;
	}

	@Column(name = "PROCESSING_TYPE")
	public Integer getProcessingType() {
		return this.processingType;
	}

	public void setProcessingType(Integer processingType) {
		this.processingType = processingType;
	}

	@Column(name = "ALLOCATION_RATE", precision = 12, scale = 0)
	public Long getAllocationRate() {
		return this.allocationRate;
	}

	public void setAllocationRate(Long allocationRate) {
		this.allocationRate = allocationRate;
	}

	@Column(name = "INSURANCE_TYPE")
	public Integer getInsuranceType() {
		return this.insuranceType;
	}

	public void setInsuranceType(Integer insuranceType) {
		this.insuranceType = insuranceType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyCoverage")
	public Set<PolicyCvgLiveEntity> getPolicyCvgLives() {
		return this.policyCvgLives;
	}

	public void setPolicyCvgLives(Set<PolicyCvgLiveEntity> policyCvgLives) {
		this.policyCvgLives = policyCvgLives;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyCoverage")
	public Set<ProductValueEntity> getProductValues() {
		return this.productValues;
	}

	public void setProductValues(Set<ProductValueEntity> productValues) {
		this.productValues = productValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyCoverage")
	public Set<AccountTransactionEntity> getAccountTransactions() {
		return this.accountTransactions;
	}

	public void setAccountTransactions(Set<AccountTransactionEntity> accountTransactions) {
		this.accountTransactions = accountTransactions;
	}

}
