package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TransactionEntity generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTIONS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class TransactionEntity implements java.io.Serializable {

	private long trnId;
	private OrderEntity order;
	@JsonIgnore
	private PolicyEntity policy; // polId is in field "policy"
	@JsonIgnore
	private Long transactionLinked;
	private String policyId;
	private Date dueDate;
	private BigDecimal policyValue;
	private Integer statusUnitTrans;
	private Integer fdmLines;
	private int atrLines;
	private Integer subType;
	private int acctTransSets;
	private Date effectiveDate;
	private String currency;
	private int eventType;
	private String reference;
	private BigDecimal value0;
	private Long triggerTrnId;
	private Integer reversalReason;
	private Integer coverage;
	private int atrStatus;
	private Integer status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private Date createdSystemDate;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Date modifySystemDate;
	private Long fkPolicyEventpevId;
	private BigDecimal originatingValue;
	private String originatingValueCcy;
	private BigDecimal afPrecedingValue;
	private String requiredPaymentCcy;
	private BigDecimal saChange;
	private String premiumSource;
	private Integer category;
	private Date fromDate;
	private Date baseDate;
	private Integer insuranceType;
	private Integer transactionTaxProcessed;
	private Integer transactionTaxCancelProcessed;
	private Boolean priceNotificationSent;

	private Set<TransactionDetailEntity> transactionDetails = new HashSet<TransactionDetailEntity>(0);
	private Set<PolicyFundInstructionEntity> policyFundInstructions = new HashSet<PolicyFundInstructionEntity>(0);
	@JsonIgnore
	private Set<AccountTransactionEntity> accountTransactions = new HashSet<AccountTransactionEntity>(0);
	@JsonIgnore
	private Set<DocumentRequestEntity> documentRequests = new HashSet<DocumentRequestEntity>(0);
	private Set<FundTransactionEntity> fundTransactions = new HashSet<FundTransactionEntity>(0);

	@Id
	@Column(name = "TRN_ID", unique = true, nullable = false, precision = 14, scale = 0)
	public long getTrnId() {
		return this.trnId;
	}

	public void setTrnId(long trnId) {
		this.trnId = trnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_ORDERSORD_ID")
	public OrderEntity getOrder() {
		return this.order;
	}

	public void setOrder(OrderEntity order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@Column(name = "FK_TRANSACTION_TRL_ID")
	public Long getTransactionLinked() {
		return this.transactionLinked;
	}

	public void setTransactionLinked(Long transactionLinked) {
		this.transactionLinked = transactionLinked;
	}

	@Column(name = "POLICY", length = 16)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DUE_DATE", length = 23)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "POLICY_VALUE", precision = 15)
	public BigDecimal getPolicyValue() {
		return this.policyValue;
	}

	public void setPolicyValue(BigDecimal policyValue) {
		this.policyValue = policyValue;
	}

	@Column(name = "STATUS_UNIT_TRANS")
	public Integer getStatusUnitTrans() {
		return this.statusUnitTrans;
	}

	public void setStatusUnitTrans(Integer statusUnitTrans) {
		this.statusUnitTrans = statusUnitTrans;
	}

	@Column(name = "FDM_LINES")
	public Integer getFdmLines() {
		return this.fdmLines;
	}

	public void setFdmLines(Integer fdmLines) {
		this.fdmLines = fdmLines;
	}

	@Column(name = "ATR_LINES", nullable = false)
	public int getAtrLines() {
		return this.atrLines;
	}

	public void setAtrLines(int atrLines) {
		this.atrLines = atrLines;
	}

	@Column(name = "SUB_TYPE")
	public Integer getSubType() {
		return this.subType;
	}

	public void setSubType(Integer subType) {
		this.subType = subType;
	}

	@Column(name = "ACCT_TRANS_SETS", nullable = false)
	public int getAcctTransSets() {
		return this.acctTransSets;
	}

	public void setAcctTransSets(int acctTransSets) {
		this.acctTransSets = acctTransSets;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_DATE", nullable = false, length = 23)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "CURRENCY", nullable = false, length = 4)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "EVENT_TYPE", nullable = false)
	public int getEventType() {
		return this.eventType;
	}

	public void setEventType(int eventType) {
		this.eventType = eventType;
	}

	@Column(name = "REFERENCE", length = 12)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "VALUE0", precision = 15)
	public BigDecimal getValue0() {
		return this.value0;
	}

	public void setValue0(BigDecimal value0) {
		this.value0 = value0;
	}

	@Column(name = "TRIGGER_TRN_ID", precision = 12, scale = 0)
	public Long getTriggerTrnId() {
		return this.triggerTrnId;
	}

	public void setTriggerTrnId(Long triggerTrnId) {
		this.triggerTrnId = triggerTrnId;
	}

	@Column(name = "REVERSAL_REASON")
	public Integer getReversalReason() {
		return this.reversalReason;
	}

	public void setReversalReason(Integer reversalReason) {
		this.reversalReason = reversalReason;
	}

	@Column(name = "COVERAGE")
	public Integer getCoverage() {
		return this.coverage;
	}

	public void setCoverage(Integer coverage) {
		this.coverage = coverage;
	}

	@Column(name = "ATR_STATUS", nullable = false)
	public int getAtrStatus() {
		return this.atrStatus;
	}

	public void setAtrStatus(int atrStatus) {
		this.atrStatus = atrStatus;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_SYSTEM_DATE", length = 23)
	public Date getModifySystemDate() {
		return this.modifySystemDate;
	}

	public void setModifySystemDate(Date modifySystemDate) {
		this.modifySystemDate = modifySystemDate;
	}

	@Column(name = "FK_POLICY_EVENTPEV_ID", precision = 15, scale = 0)
	public Long getFkPolicyEventpevId() {
		return this.fkPolicyEventpevId;
	}

	public void setFkPolicyEventpevId(Long fkPolicyEventpevId) {
		this.fkPolicyEventpevId = fkPolicyEventpevId;
	}

	@Column(name = "ORIGINATING_VALUE", precision = 15)
	public BigDecimal getOriginatingValue() {
		return this.originatingValue;
	}

	public void setOriginatingValue(BigDecimal originatingValue) {
		this.originatingValue = originatingValue;
	}

	@Column(name = "ORIGINATING_VALUE_CCY", length = 4)
	public String getOriginatingValueCcy() {
		return this.originatingValueCcy;
	}

	public void setOriginatingValueCcy(String originatingValueCcy) {
		this.originatingValueCcy = originatingValueCcy;
	}

	@Column(name = "AF_PRECEDING_VALUE", precision = 11, scale = 8)
	public BigDecimal getAfPrecedingValue() {
		return this.afPrecedingValue;
	}

	public void setAfPrecedingValue(BigDecimal afPrecedingValue) {
		this.afPrecedingValue = afPrecedingValue;
	}

	@Column(name = "REQUIRED_PAYMENT_CCY", length = 4)
	public String getRequiredPaymentCcy() {
		return this.requiredPaymentCcy;
	}

	public void setRequiredPaymentCcy(String requiredPaymentCcy) {
		this.requiredPaymentCcy = requiredPaymentCcy;
	}

	@Column(name = "SA_CHANGE", precision = 15)
	public BigDecimal getSaChange() {
		return this.saChange;
	}

	public void setSaChange(BigDecimal saChange) {
		this.saChange = saChange;
	}

	@Column(name = "PREMIUM_SOURCE", length = 8)
	public String getPremiumSource() {
		return this.premiumSource;
	}

	public void setPremiumSource(String premiumSource) {
		this.premiumSource = premiumSource;
	}

	@Column(name = "CATEGORY")
	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_DATE", length = 23)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BASE_DATE", length = 23)
	public Date getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(Date baseDate) {
		this.baseDate = baseDate;
	}

	@Column(name = "INSURANCE_TYPE")
	public Integer getInsuranceType() {
		return this.insuranceType;
	}

	public void setInsuranceType(Integer insuranceType) {
		this.insuranceType = insuranceType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<TransactionDetailEntity> getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(Set<TransactionDetailEntity> transactionDetails) {
		this.transactionDetails = transactionDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<PolicyFundInstructionEntity> getPolicyFundInstructions() {
		return this.policyFundInstructions;
	}

	public void setPolicyFundInstructions(Set<PolicyFundInstructionEntity> policyFundInstructions) {
		this.policyFundInstructions = policyFundInstructions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<AccountTransactionEntity> getAccountTransactions() {
		return this.accountTransactions;
	}

	public void setAccountTransactions(Set<AccountTransactionEntity> accountTransactions) {
		this.accountTransactions = accountTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<DocumentRequestEntity> getDocumentRequests() {
		return this.documentRequests;
	}

	public void setDocumentRequests(Set<DocumentRequestEntity> documentRequests) {
		this.documentRequests = documentRequests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<FundTransactionEntity> getFundTransactions() {
		return this.fundTransactions;
	}

	public void setFundTransactions(Set<FundTransactionEntity> fundTransactions) {
		this.fundTransactions = fundTransactions;
	}

	/**
	 * @return the transactionTaxProcessed
	 */
	@Column(name = "EX_IND_TAX_PROCESSED")
	public Integer getTransactionTaxProcessed() {
		return transactionTaxProcessed;
	}

	/**
	 * @param transactionTaxProcessed the transactionTaxProcessed to set
	 */
	public void setTransactionTaxProcessed(Integer transactionTaxProcessed) {
		this.transactionTaxProcessed = transactionTaxProcessed;
	}

	/**
	 * @return the transactionTaxCancelProcessed
	 */
	@Column(name = "EX_IND_TAX_CANCEL_PROCESSED")
	public Integer getTransactionTaxCancelProcessed() {
		return transactionTaxCancelProcessed;
	}

	/**
	 * @param transactionTaxCancelProcessed the transactionTaxCancelProcessed to set
	 */
	public void setTransactionTaxCancelProcessed(Integer transactionTaxCancelProcessed) {
		this.transactionTaxCancelProcessed = transactionTaxCancelProcessed;
	}

	/**
	 * @return the priceNotificationSent
	 */
	@Column(name = "PRICE_NOTIF_SENT")
	public Boolean getPriceNotificationSent() {
		return priceNotificationSent;
	}

	/**
	 * @param priceNotificationSent the priceNotificationSent to set
	 */
	public void setPriceNotificationSent(Boolean priceNotificationSent) {
		this.priceNotificationSent = priceNotificationSent;
	}

}
