package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FundsHistoryEntity generated by hbm2java
 */
@Entity
@Table(name = "FUNDS_History"

)
public class FundsHistoryEntity implements java.io.Serializable {

	private FundsHistoryEntityId id;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "histId", column = @Column(name = "HIST_ID", nullable = false, length = 60)),
			@AttributeOverride(name = "action0", column = @Column(name = "Action0", length = 20)),
			@AttributeOverride(name = "actionBy", column = @Column(name = "Action_by", length = 100)),
			@AttributeOverride(name = "actionDatetime", column = @Column(name = "Action_datetime", length = 23)),
			@AttributeOverride(name = "fdsId", column = @Column(name = "FDS_ID", nullable = false, length = 8)),
			@AttributeOverride(name = "currency", column = @Column(name = "CURRENCY", nullable = false, length = 5)),
			@AttributeOverride(name = "fundType", column = @Column(name = "FUND_TYPE", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", nullable = false, length = 35)),
			@AttributeOverride(name = "pricingFrequency", column = @Column(name = "PRICING_FREQUENCY", nullable = false)),
			@AttributeOverride(name = "pricingDay", column = @Column(name = "PRICING_DAY")),
			@AttributeOverride(name = "pricingDayOfMonth", column = @Column(name = "PRICING_DAY_OF_MONTH")),
			@AttributeOverride(name = "priceBasis", column = @Column(name = "PRICE_BASIS", nullable = false)),
			@AttributeOverride(name = "bidOfferSpread", column = @Column(name = "BID_OFFER_SPREAD", precision = 8, scale = 4)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", nullable = false)),
			@AttributeOverride(name = "unitTypes", column = @Column(name = "UNIT_TYPES", nullable = false)),
			@AttributeOverride(name = "fwdPriceReportDays", column = @Column(name = "FWD_PRICE_REPORT_DAYS")),
			@AttributeOverride(name = "groupingCode", column = @Column(name = "GROUPING_CODE", length = 10)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", nullable = false, length = 5)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE", nullable = false, length = 23)),
			@AttributeOverride(name = "createdTime", column = @Column(name = "CREATED_TIME", nullable = false, length = 23)),
			@AttributeOverride(name = "createdProcess", column = @Column(name = "CREATED_PROCESS", length = 12)),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "MODIFY_BY", length = 5)),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "MODIFY_DATE", length = 23)),
			@AttributeOverride(name = "modifyTime", column = @Column(name = "MODIFY_TIME", length = 23)),
			@AttributeOverride(name = "modifyProcess", column = @Column(name = "MODIFY_PROCESS", length = 12)),
			@AttributeOverride(name = "pricingTime", column = @Column(name = "PRICING_TIME", length = 23)),
			@AttributeOverride(name = "accountingStream", column = @Column(name = "ACCOUNTING_STREAM")),
			@AttributeOverride(name = "documentationName", column = @Column(name = "DOCUMENTATION_NAME", length = 100)),
			@AttributeOverride(name = "isinCode", column = @Column(name = "ISIN_CODE", length = 12)),
			@AttributeOverride(name = "nlProduct", column = @Column(name = "NL_PRODUCT", length = 3)),
			@AttributeOverride(name = "cutOffTime", column = @Column(name = "CUT_OFF_TIME", length = 23)),
			@AttributeOverride(name = "ulFundType", column = @Column(name = "UL_FUND_TYPE", length = 8)),
			@AttributeOverride(name = "maxAllocationPercent", column = @Column(name = "MAX_ALLOCATION_PERCENT", precision = 8, scale = 4)),
			@AttributeOverride(name = "assetManager", column = @Column(name = "ASSET_MANAGER", length = 8)),
			@AttributeOverride(name = "depositBank", column = @Column(name = "DEPOSIT_BANK", length = 8)),
			@AttributeOverride(name = "country", column = @Column(name = "COUNTRY", length = 27)),
			@AttributeOverride(name = "navEntryFee", column = @Column(name = "NAV_ENTRY_FEE", precision = 15, scale = 6)),
			@AttributeOverride(name = "navExitFee", column = @Column(name = "NAV_EXIT_FEE", precision = 15, scale = 6)),
			@AttributeOverride(name = "riskProfile", column = @Column(name = "RISK_PROFILE", length = 8)),
			@AttributeOverride(name = "riskCurrency", column = @Column(name = "RISK_CURRENCY", length = 8)),
			@AttributeOverride(name = "investCat", column = @Column(name = "INVEST_CAT", length = 8)),
			@AttributeOverride(name = "investObjective", column = @Column(name = "INVEST_OBJECTIVE", length = 8)),
			@AttributeOverride(name = "alternativeFunds", column = @Column(name = "ALTERNATIVE_FUNDS", length = 8)),
			@AttributeOverride(name = "riskProfileDate", column = @Column(name = "RISK_PROFILE_DATE", length = 23)),
			@AttributeOverride(name = "notes", column = @Column(name = "NOTES", length = 100)),
			@AttributeOverride(name = "pricingDelay", column = @Column(name = "PRICING_DELAY")),
			@AttributeOverride(name = "iban", column = @Column(name = "IBAN", length = 35)),
			@AttributeOverride(name = "salesRep", column = @Column(name = "SALES_REP", length = 8)),
			@AttributeOverride(name = "investCashLimit", column = @Column(name = "INVEST_CASH_LIMIT", precision = 15)),
			@AttributeOverride(name = "poa", column = @Column(name = "POA")),
			@AttributeOverride(name = "poaType", column = @Column(name = "POA_TYPE", length = 12)),
			@AttributeOverride(name = "mandateHolder", column = @Column(name = "MANDATE_HOLDER", length = 8)),
			@AttributeOverride(name = "poaDate", column = @Column(name = "POA_DATE", length = 23)) })
	public FundsHistoryEntityId getId() {
		return this.id;
	}

	public void setId(FundsHistoryEntityId id) {
		this.id = id;
	}

}
