ALTER TABLE CLIENT_ENDORSEMENTS
ADD		CLASSIFICATION_DETAILS 		   char(50)             NULL,
		POLITICALLY_EXPOSED_PERSON	   char(15)		NULL,
		PEP_FUNCTION			   char(50)		NULL,
		INSIDER_TRADING			   char(15)		NULL,
		INSIDER_TRADING_DETAIL		   char(50)		NULL,
		DAP				   smallint		NULL
		
GO