DELETE [UOPT_DETAILS] WHERE FK_UOPT_DEFINITUDF_ID = 53;

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR01','1','Activité portuaire',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR02','2','Antiquité, brocante ou œuvres d’art',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR03','3','Armement',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR04','4','Avocat',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);
  
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR05','5','Commerce de bijoux ou pierres préc.',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR06','6','Casino',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR07','7','Cabaret ou discothèque',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR08','8','Commerce du luxe',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR09','9','Commerce véhicules neufs ou occas.',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR10','10','Etablissement de change',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR11','11','Expertise comptable',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR12','12','Import-Export',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR13','13','Lobbying',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR14','14','Commerce de matières premières',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR15','15','Notaire',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR16','16','Promotion immoblilière',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR17','17','Jeux en ligne',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  
    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR18','18','Sport professionnel',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR19','19','Tabac',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  
   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR20','20','Travaux publics',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);