
  INSERT INTO UOPT_DEFINITIONS (UDF_ID, NAME, STATUS, USEAGE, CREATED_BY, CREATED_DATE, CREATED_TIME,CREATED_PROCESS)
VALUES (64,'Type of Entity', 1, 1, 'rvn', GETDATE(), GETDATE(),'WEBIA');

 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SA','SA','S.A.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);
 
 
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SARL','SARL','S.A.R.L.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('EURL','EURL','E.U.R.L.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('ASBL','ASBL','A.S.B.L.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('ONG','ONG','O.N.G.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SCS','S.C.S.','S.C.S.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SCIV','SCIV','S.Civ.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SCOOP','SCOOP','S.Coop.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);


   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SPRL','SPRL','S.P.R.L.',1,64,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 64,'',0);


