

DELETE [UOPT_DETAILS] WHERE FK_UOPT_DEFINITUDF_ID = 29;

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C95/3','C95/3','Circular C95/3',0,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);

      INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C01/8','C01/8','Circular C01/8',0,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C04/8','C04/8','Circular C04/8',0,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C05/5','C05/5','Circular C05/5',0,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C06/8','C06/8','Circular C06/8',0,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C08/1','C08/1','Circular C08/1',1,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C15/3','C15/3','Circular C15/3',1,29,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 29,'',0);