

INSERT INTO UOPT_DEFINITIONS (UDF_ID, NAME, STATUS, USEAGE, CREATED_BY, CREATED_DATE, CREATED_TIME,CREATED_PROCESS)
VALUES (62,'Function of Contact ', 1, 1, 'rvn', GETDATE(), GETDATE(),'WEBIA');

 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('BACKOFF','BACKOFF','Back Office',1,62,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 62,'',0);
 
   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('COMPTA','COMPTA','Comptabilité/Finance',1,62,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 62,'',0);
 
 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('DIRECT','DIRECT','Direction/Mngt',1,62,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 62,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('LEGAL','LEGAL','Legal',1,62,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 62,'',0);


   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('SALES','SALES','Sales',1,62,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 62,'',0);