DELETE [UOPT_DETAILS] WHERE FK_UOPT_DEFINITUDF_ID = 58;

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('FT01','FT01','Administrateur',1,58,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 58,'',0);

  
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('FT02','FT02','Dirigeant',1,58,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 58,'',0);


  
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('FT03','FT03','Gérant',1,58,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 58,'',0);


  
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('FT04','FT04','Directeur',1,58,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 58,'',0);