INSERT INTO UOPT_DEFINITIONS (UDF_ID, NAME, STATUS, USEAGE, CREATED_BY, CREATED_DATE, CREATED_TIME,CREATED_PROCESS)
VALUES (61,'Type of controlling person', 1, 1, 'rvn', GETDATE(), GETDATE(),'WEBIA');

 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('A_SET','A_SET','Settlor',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);

  
 INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('B_TRUST','B_TRUST','Trustee',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);
 
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('C_PROT','C_PROT','Protector',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);
  
   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('D_BENEF','D_BENEF','Beneficiary',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);  

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('E_ACTION','E_ACTION','Shareholder/Economic beneficiary',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('F_ADMIN','F_ADMIN','Director',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('G_DIRECT','G_DIRECT','Senior Management',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('Z_AUTRE','Z_AUTRE','Other',1,61,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 61,'',0);

  