  Update clients set ACTIVITY_RISK_CAT = '4' Where ACTIVITY_RISK_CAT = '15';
  
  update UOPT_DETAILS set DESCRIPTION = 'Armement (fabrication, vente,...)' where UDD_ID = 'PR03';

  update UOPT_DETAILS set DESCRIPTION = 'Juridique(avocat,notaire,huissier)' where UDD_ID = 'PR04';

  update UOPT_DETAILS set DESCRIPTION = 'Casino/Jeux de hasard, en ligne' where UDD_ID = 'PR06';

  update UOPT_DETAILS set DESCRIPTION = 'Cons.fiscal/Exp.comptable/Réviseur' where UDD_ID = 'PR11';

  update UOPT_DETAILS set DESCRIPTION = 'Construction/Bât./Travaux publics' where UDD_ID = 'PR20';

  update UOPT_DETAILS set DESCRIPTION = 'Industrie du tabac' where UDD_ID = 'PR19';

  update UOPT_DETAILS set DESCRIPTION = 'Recyclage/Traitement des déchets' where UDD_ID = 'PR15';


     INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR21','21','Diplomatie',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);
    
     INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR23','23','Transport de marchandises',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

     INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR22','22','Hôtellerie/Restauration',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  -- non sensibles

   INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR101','101','Aéronautique',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

     INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR102','102','Agriculture/Pêche/Chass',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

     INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR103','103','Agro-alimentaire',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

       INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR104','104','Architecture / Urbanisme',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

         INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR105','105','Artisanat',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

           INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR106','106','Assistance sociale',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR107','107','Associatif',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR108','108','Finance (Assurance, Banque)',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR109','109','Audit/Consultance/Conseil',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);
    
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR110','110','Commerce de détail',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  
  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR111','111','Commerce de gros',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);


    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR112','112','Comm./Télécom./Marketing/Pub',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR113','113','Contionnement/Emballage',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

  
    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR114','114','Culture/Art/Spectacle',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

      INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR115','115','Prod/Distrib d"énergie',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

        INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR116','116','E-commerce ',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

          INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR117','117','Enseignement/Formation',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

            INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR118','118','Grande distribution',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

              INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR119','119','Imprimerie/Edition',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

                INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR120','120','Industrie automobile',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

                  INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR121','121','Industrie manufacturière',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

                    INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
  VALUES ('PR122','122','Industrie chimique/pharmaceutique',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR123','123','Industrie textile/Habillement',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR124','124','Information/Presse ',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR125','125','Informatique ',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR126','126','Juridique (autre) ',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR127','127','Logistique',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR128','128','Mecanique',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR129','129','Metallurgie',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR130','130','Recherche/Sciences',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR131','131','Sécurité',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR132','132','Services à la personne',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR133','133','Services administratifs ',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR134','134','Services de secours',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR135','135','Services publics ',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR136','136','Soins de santé',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR137','137','Soins esthétique',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR138','138','Tourisme',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR139','139','Transport de personnes',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR140','140','Sans activité professionnelle',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);

INSERT INTO [UOPT_DETAILS] (UDD_ID, KEY_VALUE, DESCRIPTION, STATUS, DEFINITION, TYPE, CREATED_BY, CREATED_DATE, CREATED_TIME, CREATED_PROCESS, FK_UOPT_DEFINITUDF_ID, GROUP_ID, DEFAULT0)
VALUES ('PR141','141','Autre',1,53,0,'rvn',GETDATE(), GETDATE(), 'WEBIA', 53,'',0);