SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[POLICY_TRANSFER](
	[POLICY_TRANSFER_ID] [int] IDENTITY(1,1) NOT NULL,
	[POLICY] [varchar] (14) NOT NULL,
	[COVERAGE] [char] (1) NOT NULL,
	[FROM_POLICY] [varchar](14) NOT NULL,
	[FROM_POLICY_EFFECT_DT] [datetime] NOT NULL,
	[TRANSFER_TYPE] [varchar] (50) NOT NULL,
	[FK_POLICIESPOL_ID] [varchar] (14) NOT NULL,

	[CREATED_PROCESS] varchar(15) NOT NULL,
	[MODIFY_PROCESS] varchar(15),
	[CREATED_BY] varchar(5),
	[CREATED_DATE] datetime NOT NULL,
	[CREATED_TIME] datetime NOT NULL,
	[MODIFY_BY] varchar(5),
	[MODIFY_DATE] datetime,
	[MODIFY_TIME] datetime,

	CONSTRAINT [PK_POLICY_TRANSFER] PRIMARY KEY CLUSTERED 
(
	[POLICY_TRANSFER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE INDEX [IND_POLICY_TRANSER_POL] ON [dbo].[POLICY_TRANSFER]
(
	[FK_POLICIESPOL_ID] ASC
)
GO







