 IF COL_LENGTH('TRANSACTIONS','EX_IND_TAX_PROCESSED') IS NULL
 BEGIN
 ALTER TABLE TRANSACTIONS add EX_IND_TAX_PROCESSED int NOT NULL DEFAULT ((0));
 END

  IF COL_LENGTH('TRANSACTIONS','EX_IND_TAX_CANCEL_PROCESSED') IS NULL
 BEGIN
 ALTER TABLE TRANSACTIONS add EX_IND_TAX_CANCEL_PROCESSED int NOT NULL DEFAULT ((0));
 END


