INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
     (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (1,'CATEGORY','Asset Manager','AM',1);  

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
    (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (2,'CATEGORY','Broker','BK',1);  

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
       (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (3,'CATEGORY','Buisness Introducer','IN',1);  
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
       (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (4,'CATEGORY','Custody Bank','DB',1); 

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (5,'COUNTRY','AFGHANISTAN','AFG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (6,'COUNTRY','ALBANIA','ALB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (7,'COUNTRY','ALGERIA','DZA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (8,'COUNTRY','AMERICAN SAMOA','ASM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (9,'COUNTRY','ANDORRA','AND',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (10,'COUNTRY','ANGOLA','AGO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (11,'COUNTRY','ANGUILLA','AIA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (12,'COUNTRY','ANTIGUA AND BARBUDA','ATG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (13,'COUNTRY','ARGENTINA','ARG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (14,'COUNTRY','ARMENIA','ARM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (15,'COUNTRY','ARUBA','ABW',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (16,'COUNTRY','AUSTRALIA','AUS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (17,'COUNTRY','AUSTRIA','AUT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (18,'COUNTRY','AZERBAIJAN','AZE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (19,'COUNTRY','BAHAMAS','BHS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (20,'COUNTRY','BAHRAIN','BHR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (21,'COUNTRY','BANGLADESH','BGD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (22,'COUNTRY','BARBADOS','BRB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (23,'COUNTRY','BELARUS','BLR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (24,'COUNTRY','BELGIUM','BEL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (25,'COUNTRY','BELIZE','BLZ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (26,'COUNTRY','BENIN','BEN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (27,'COUNTRY','BERMUDA','BMU',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (28,'COUNTRY','BHUTAN','BTN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (29,'COUNTRY','BOLIVIA','BOL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (30,'COUNTRY','BOSNIA AND HERZEGOWINA','BIH',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (31,'COUNTRY','BOTSWANA','BWA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (32,'COUNTRY','BOUVET ISLAND','BVT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (33,'COUNTRY','BRAZIL','BRA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (34,'COUNTRY','BRITISH INDIAN OCEAN TERRITORY','IOT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (35,'COUNTRY','BRUNEI DARUSSALAM','BRN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (36,'COUNTRY','BULGARIA','BGR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (37,'COUNTRY','BURKINA FASO','BFA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (38,'COUNTRY','BURUNDI','BDI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (39,'COUNTRY','CAMBODIA','KHM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (40,'COUNTRY','CAMEROON','CMR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (41,'COUNTRY','CANADA','CAN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (42,'COUNTRY','CAPE VERDE','CPV',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (43,'COUNTRY','CAYMAN ISLANDS','CYM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (44,'COUNTRY','CENTRAL AFRICAN REPUBLIC','CAF',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (45,'COUNTRY','CHAD','TCD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (46,'COUNTRY','CHILE','CHL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (47,'COUNTRY','CHINA','CHN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (48,'COUNTRY','CHRISTMAS ISLAND','CXR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (49,'COUNTRY','COCOS (KEELING) ISLANDS','CCK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (50,'COUNTRY','COLOMBIA','COL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (51,'COUNTRY','COMOROS','COM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (52,'COUNTRY','CONGO','COG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (53,'COUNTRY','CONGO, THE DEMOCRATIC REPUBLIC OF THE','COD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (54,'COUNTRY','COOK ISLANDS','COK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (55,'COUNTRY','COSTA RICA','CRI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (56,'COUNTRY','CROATIA','HRV',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (57,'COUNTRY','CUBA','CUB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (58,'COUNTRY','CYPRUS','CYP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (59,'COUNTRY','CZECH REPUBLIC','CZE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (60,'COUNTRY','DENMARK','DNK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (61,'COUNTRY','DJIBOUTI','DJI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (62,'COUNTRY','DOMINICA','DMA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (63,'COUNTRY','DOMINICAN REPUBLIC','DOM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (64,'COUNTRY','NULL','TMP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (65,'COUNTRY','ECUADOR','ECU',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (66,'COUNTRY','EGYPT','EGY',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (67,'COUNTRY','EL SALVADOR','SLV',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (68,'COUNTRY','EQUATORIAL GUINEA','GNQ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (69,'COUNTRY','ERITREA','ERI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (70,'COUNTRY','ESTONIA','EST',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (71,'COUNTRY','ETHIOPIA','ETH',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (72,'COUNTRY','FALKLAND ISLANDS (MALVINAS)','FLK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (73,'COUNTRY','FAROE ISLANDS','FRO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (74,'COUNTRY','FIJI','FJI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (75,'COUNTRY','FINLAND','FIN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (76,'COUNTRY','FRANCE','FRA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (77,'COUNTRY','FRENCH GUIANA','GUF',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (78,'COUNTRY','FRENCH POLYNESIA','PYF',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (79,'COUNTRY','FRENCH SOUTHERN TERRITORIES','ATF',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (80,'COUNTRY','GABON','GAB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (81,'COUNTRY','GAMBIA','GMB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (82,'COUNTRY','GEORGIA','GEO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (83,'COUNTRY','GERMANY','DEU',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (84,'COUNTRY','GHANA','GHA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (85,'COUNTRY','GIBRALTAR','GIB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (86,'COUNTRY','GREECE','GRC',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (87,'COUNTRY','GREENLAND','GRL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (88,'COUNTRY','GRENADA','GRD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (89,'COUNTRY','UNITED KINGDOM','GBR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (90,'COUNTRY','GUADELOUPE','GLP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (91,'COUNTRY','GUAM','GUM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (92,'COUNTRY','GUATEMALA','GTM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (93,'COUNTRY','GUINEA','GIN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (94,'COUNTRY','GUINEA-BISSAU','GNB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (95,'COUNTRY','GUYANA','GUY',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (96,'COUNTRY','HAITI','HTI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (97,'COUNTRY','HEARD AND MC DONALD ISLANDS','HMD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (98,'COUNTRY','HONDURAS','HND',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (99,'COUNTRY','HONG KONG','HKG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (100,'COUNTRY','HUNGARY','HUN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (101,'COUNTRY','ICELAND','ISL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (102,'COUNTRY','INDIA','IND',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (103,'COUNTRY','INDONESIA','IDN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (104,'COUNTRY','IRAN (ISLAMIC REPUBLIC OF)','IRN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (105,'COUNTRY','IRAQ','IRQ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (106,'COUNTRY','IRELAND','IRL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (107,'COUNTRY','ISRAEL','ISR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (108,'COUNTRY','ITALY','ITA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (109,'COUNTRY','COTE D''IVOIRE','CIV',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (110,'COUNTRY','JAMAICA','JAM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (111,'COUNTRY','JAPAN','JPN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (112,'COUNTRY','JORDAN','JOR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (113,'COUNTRY','KAZAKHSTAN','KAZ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (114,'COUNTRY','KENYA','KEN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (115,'COUNTRY','KIRIBATI','KIR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (116,'COUNTRY','KUWAIT','KWT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (117,'COUNTRY','KYRGYZSTAN','KGZ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (118,'COUNTRY','LAO PEOPLE''S DEMOCRATIC REPUBLIC','LAO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (119,'COUNTRY','LATVIA','LVA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (120,'COUNTRY','LEBANON','LBN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (121,'COUNTRY','LESOTHO','LSO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (122,'COUNTRY','LIBERIA','LBR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (123,'COUNTRY','LIBYAN ARAB JAMAHIRIYA','LBY',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (124,'COUNTRY','LIECHTENSTEIN','LIE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (125,'COUNTRY','LITHUANIA','LTU',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (126,'COUNTRY','LUXEMBOURG','LUX',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (127,'COUNTRY','MACAU','MAC',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (128,'COUNTRY','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MKD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (129,'COUNTRY','MADAGASCAR','MDG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (130,'COUNTRY','MALAWI','MWI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (131,'COUNTRY','MALAYSIA','MYS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (132,'COUNTRY','MALDIVES','MDV',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (133,'COUNTRY','MALI','MLI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (134,'COUNTRY','MALTA','MLT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (135,'COUNTRY','MARSHALL ISLANDS','MHL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (136,'COUNTRY','MARTINIQUE','MTQ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (137,'COUNTRY','MAURITANIA','MRT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (138,'COUNTRY','MAURITIUS','MUS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (139,'COUNTRY','MAYOTTE','MYT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (140,'COUNTRY','MEXICO','MEX',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (141,'COUNTRY','MICRONESIA, FEDERATED STATES OF','FSM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (142,'COUNTRY','MOLDOVA, REPUBLIC OF','MDA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (143,'COUNTRY','MONACO','MCO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (144,'COUNTRY','MONGOLIA','MNG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (145,'COUNTRY','MONTSERRAT','MSR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (146,'COUNTRY','MOROCCO','MAR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (147,'COUNTRY','MOZAMBIQUE','MOZ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (148,'COUNTRY','MYANMAR','MMR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (149,'COUNTRY','NAURU','NRU',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (150,'COUNTRY','NAMIBIA','NAM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (151,'COUNTRY','NEPAL','NPL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (152,'COUNTRY','NETHERLANDS','NLD',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (153,'COUNTRY','NETHERLANDS ANTILLES','ANT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (154,'COUNTRY','NEW CALEDONIA','NCL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (155,'COUNTRY','NEW ZEALAND','NZL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (156,'COUNTRY','NICARAGUA','NIC',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (157,'COUNTRY','NIGER','NER',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (158,'COUNTRY','NIGERIA','NGA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (159,'COUNTRY','NORFOLK ISLAND','NFK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (160,'COUNTRY','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','PRK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (161,'COUNTRY','NORTHERN MARIANA ISLANDS','MNP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (162,'COUNTRY','NORWAY','NOR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (163,'COUNTRY','OMAN','OMN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (164,'COUNTRY','PAKISTAN','PAK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (165,'COUNTRY','PALAU','PLW',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (166,'COUNTRY','PANAMA','PAN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (167,'COUNTRY','PAPUA NEW GUINEA','PNG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (168,'COUNTRY','PARAGUAY','PRY',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (169,'COUNTRY','PERU','PER',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (170,'COUNTRY','PHILIPPINES','PHL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (171,'COUNTRY','PITCAIRN','PCN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (172,'COUNTRY','POLAND','POL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (173,'COUNTRY','PORTUGAL','PRT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (174,'COUNTRY','PUERTO RICO','PRI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (175,'COUNTRY','QATAR','QAT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (176,'COUNTRY','ROMANIA','ROM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (177,'COUNTRY','RUSSIAN FEDERATION','RUS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (178,'COUNTRY','RWANDA','RWA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (179,'COUNTRY','SAN MARINO','SMR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (180,'COUNTRY','SAO TOME AND PRINCIPE','STP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (181,'COUNTRY','SAUDI ARABIA','SAU',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (182,'COUNTRY','SENEGAL','SEN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (183,'COUNTRY','SEYCHELLES','SYC',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (184,'COUNTRY','SIERRA LEONE','SLE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (185,'COUNTRY','SINGAPORE','SGP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (186,'COUNTRY','SLOVAKIA (Slovak Republic)','SVK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (187,'COUNTRY','SLOVENIA','SVN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (188,'COUNTRY','SOLOMON ISLANDS','SLB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (189,'COUNTRY','SOMALIA','SOM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (190,'COUNTRY','SOUTH AFRICA','ZAF',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (191,'COUNTRY','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','SGS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (192,'COUNTRY','KOREA, REPUBLIC OF','KOR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (193,'COUNTRY','SPAIN','ESP',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (194,'COUNTRY','SRI LANKA','LKA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (195,'COUNTRY','SAINT KITTS AND NEVIS','KNA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (196,'COUNTRY','SAINT LUCIA','LCA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (197,'COUNTRY','SAINT VINCENT AND THE GRENADINES','VCT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (198,'COUNTRY','ST. HELENA','SHN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (199,'COUNTRY','ST. PIERRE AND MIQUELON','SPM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (200,'COUNTRY','SUDAN','SDN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (201,'COUNTRY','SURINAME','SUR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (202,'COUNTRY','SVALBARD AND JAN MAYEN ISLANDS','SJM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (203,'COUNTRY','SWAZILAND','SWZ',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (204,'COUNTRY','SWEDEN','SWE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (205,'COUNTRY','SWITZERLAND','CHE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (206,'COUNTRY','SYRIAN ARAB REPUBLIC','SYR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (207,'COUNTRY','TAIWAN, PROVINCE OF CHINA','TWN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (208,'COUNTRY','THAILAND','THA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (209,'COUNTRY','TOGO','TGO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (210,'COUNTRY','TAJIKISTAN','TJK',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (211,'COUNTRY','TANZANIA, UNITED REPUBLIC OF','TZA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (212,'COUNTRY','TOKELAU','TKL',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (213,'COUNTRY','TONGA','TON',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (214,'COUNTRY','TRINIDAD AND TOBAGO','TTO',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (215,'COUNTRY','TUNISIA','TUN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (216,'COUNTRY','TURKEY','TUR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (217,'COUNTRY','TURKMENISTAN','TKM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (218,'COUNTRY','TURKS AND CAICOS ISLANDS','TCA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (219,'COUNTRY','TUVALU','TUV',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (220,'COUNTRY','UGANDA','UGA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (221,'COUNTRY','UKRAINE','UKR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (222,'COUNTRY','UNITED ARAB EMIRATES','ARE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (223,'COUNTRY','UNITED STATES','USA',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (224,'COUNTRY','UNITED STATES MINOR OUTLYING ISLANDS','UMI',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (225,'COUNTRY','URUGUAY','URY',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (226,'COUNTRY','UZBEKISTAN','UZB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (227,'COUNTRY','VANUATU','VUT',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (228,'COUNTRY','VENEZUELA','VEN',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (229,'COUNTRY','VIET NAM','VNM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (230,'COUNTRY','VIRGIN ISLANDS (BRITISH)','VGB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (231,'COUNTRY','VIRGIN ISLANDS (U.S.)','VIR',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (232,'COUNTRY','WALLIS AND FUTUNA ISLANDS','WLF',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (233,'COUNTRY','WESTERN SAHARA','ESH',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (234,'COUNTRY','SAMOA','WSM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (235,'COUNTRY','YEMEN','YEM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (236,'COUNTRY','NULL','YUG',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (237,'COUNTRY','ZAMBIA','ZMB',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (238,'COUNTRY','ZIMBABWE','ZWE',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (239,'COUNTRY','SERBIA','RS',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (240,'COUNTRY','SAINT-BARTHÉLEMY','BLM',1);
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]  (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)  VALUES (241,'COUNTRY','RÉUNION','REU',1);


INSERT INTO [dbo].[DRM_LISSIA_MAPPING] 
       (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (242,'PAYMENT_COMMISSION','No','0',1);  

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
        (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (243,'PAYMENT_COMMISSION','Yes','1',1);     

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
       (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (244,'PAYMENT_METHOD','Multiline','3',1);  

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
       (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (245,'PAYMENT_METHOD','Fax','2',1);  
  
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (246,'DOCUMENTATION LANGUAGE','FR','3',1); 
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (247,'DOCUMENTATION LANGUAGE','DE','9',1);  
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (248,'DOCUMENTATION LANGUAGE','EN','1',1); 
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (249,'DOCUMENTATION LANGUAGE','IT','8',1); 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (250,'DOCUMENTATION LANGUAGE','NL','11',1);  
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (251,'DOCUMENTATION LANGUAGE','SV','10',1);
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (252,'DOCUMENTATION LANGUAGE','NO','7',1); 
 
INSERT INTO [dbo].[DRM_LISSIA_MAPPING]   
      (DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
 VALUES (253,'DOCUMENTATION LANGUAGE','PT','13',1);   
