  ALTER TABLE  FUNDS  
  ALTER COLUMN
       DEPOSIT_ACCOUNT		      VARCHAR(35)          NULL 
  GO
  

  ALTER TABLE  FUNDS_HISTORY_DETAILS    
  ALTER COLUMN
       DEPOSIT_ACCOUNT		      VARCHAR(35)          NULL 
  GO