SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PATTERN_ACCOUNT_ROOT](
	[PATTERN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCOUNT_BIC] [varchar](35) NOT NULL,
	[EXEMPLE] [varchar](50) NULL,
	[PATTERN] [varchar](250) NULL,
 CONSTRAINT [PK_PATTERN] PRIMARY KEY CLUSTERED
(
	[PATTERN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
