package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RateBandingEntity generated by hbm2java
 */
@Entity
@Table(name = "RATE_BANDINGS"

)
public class RateBandingEntity implements java.io.Serializable {

	private String rbaId;
	private RateDefinitionEntity rateDefinition;
	private Long rateDefinitionId;
	private int series;
	private int axisNo;
	private Integer noOfValues;
	private String highestValue;
	private String v1;
	private String v2;
	private String v3;
	private String v4;
	private String v5;
	private String v6;
	private String v7;
	private String v8;
	private String v9;
	private String v10;
	private String v11;
	private String v12;
	private String v13;
	private String v14;
	private String v15;
	private String v16;
	private String v17;
	private String v18;
	private String v19;
	private String v20;
	private int status;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private String modifyBy;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyProcess;

	@Id
	@Column(name = "RBA_ID", unique = true, nullable = false, length = 20)
	public String getRbaId() {
		return this.rbaId;
	}

	public void setRbaId(String rbaId) {
		this.rbaId = rbaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_RATE_DEFINITRDF_ID")
	public RateDefinitionEntity getRateDefinition() {
		return this.rateDefinition;
	}

	public void setRateDefinition(RateDefinitionEntity rateDefinition) {
		this.rateDefinition = rateDefinition;
	}

	@Column(name = "RATE_DEFINITION", precision = 15, scale = 0)
	public Long getRateDefinitionId() {
		return this.rateDefinitionId;
	}

	public void setRateDefinitionId(Long rateDefinitionId) {
		this.rateDefinitionId = rateDefinitionId;
	}

	@Column(name = "SERIES", nullable = false)
	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

	@Column(name = "AXIS_NO", nullable = false)
	public int getAxisNo() {
		return this.axisNo;
	}

	public void setAxisNo(int axisNo) {
		this.axisNo = axisNo;
	}

	@Column(name = "NO_OF_VALUES")
	public Integer getNoOfValues() {
		return this.noOfValues;
	}

	public void setNoOfValues(Integer noOfValues) {
		this.noOfValues = noOfValues;
	}

	@Column(name = "HIGHEST_VALUE", length = 20)
	public String getHighestValue() {
		return this.highestValue;
	}

	public void setHighestValue(String highestValue) {
		this.highestValue = highestValue;
	}

	@Column(name = "V1", length = 20)
	public String getV1() {
		return this.v1;
	}

	public void setV1(String v1) {
		this.v1 = v1;
	}

	@Column(name = "V2", length = 20)
	public String getV2() {
		return this.v2;
	}

	public void setV2(String v2) {
		this.v2 = v2;
	}

	@Column(name = "V3", length = 20)
	public String getV3() {
		return this.v3;
	}

	public void setV3(String v3) {
		this.v3 = v3;
	}

	@Column(name = "V4", length = 20)
	public String getV4() {
		return this.v4;
	}

	public void setV4(String v4) {
		this.v4 = v4;
	}

	@Column(name = "V5", length = 20)
	public String getV5() {
		return this.v5;
	}

	public void setV5(String v5) {
		this.v5 = v5;
	}

	@Column(name = "V6", length = 20)
	public String getV6() {
		return this.v6;
	}

	public void setV6(String v6) {
		this.v6 = v6;
	}

	@Column(name = "V7", length = 20)
	public String getV7() {
		return this.v7;
	}

	public void setV7(String v7) {
		this.v7 = v7;
	}

	@Column(name = "V8", length = 20)
	public String getV8() {
		return this.v8;
	}

	public void setV8(String v8) {
		this.v8 = v8;
	}

	@Column(name = "V9", length = 20)
	public String getV9() {
		return this.v9;
	}

	public void setV9(String v9) {
		this.v9 = v9;
	}

	@Column(name = "V10", length = 20)
	public String getV10() {
		return this.v10;
	}

	public void setV10(String v10) {
		this.v10 = v10;
	}

	@Column(name = "V11", length = 20)
	public String getV11() {
		return this.v11;
	}

	public void setV11(String v11) {
		this.v11 = v11;
	}

	@Column(name = "V12", length = 20)
	public String getV12() {
		return this.v12;
	}

	public void setV12(String v12) {
		this.v12 = v12;
	}

	@Column(name = "V13", length = 20)
	public String getV13() {
		return this.v13;
	}

	public void setV13(String v13) {
		this.v13 = v13;
	}

	@Column(name = "V14", length = 20)
	public String getV14() {
		return this.v14;
	}

	public void setV14(String v14) {
		this.v14 = v14;
	}

	@Column(name = "V15", length = 20)
	public String getV15() {
		return this.v15;
	}

	public void setV15(String v15) {
		this.v15 = v15;
	}

	@Column(name = "V16", length = 20)
	public String getV16() {
		return this.v16;
	}

	public void setV16(String v16) {
		this.v16 = v16;
	}

	@Column(name = "V17", length = 20)
	public String getV17() {
		return this.v17;
	}

	public void setV17(String v17) {
		this.v17 = v17;
	}

	@Column(name = "V18", length = 20)
	public String getV18() {
		return this.v18;
	}

	public void setV18(String v18) {
		this.v18 = v18;
	}

	@Column(name = "V19", length = 20)
	public String getV19() {
		return this.v19;
	}

	public void setV19(String v19) {
		this.v19 = v19;
	}

	@Column(name = "V20", length = 20)
	public String getV20() {
		return this.v20;
	}

	public void setV20(String v20) {
		this.v20 = v20;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

}
