package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyCvgReinsDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_CVG_REINS_DETAILS"

)
public class PolicyCvgReinsDetailEntity implements java.io.Serializable {

	private long pcrId;
	private String treaty;
	private BigDecimal amount;
	private String type;
	private String reinsurerCode;
	private String policy;
	private int coverage;
	private String modifyProcess;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyBy;
	private String createdProcess;
	private Date createdTime;
	private Date createdDate;
	private String createdBy;
	private String reinsurer;
	private int status;

	@Id
	@Column(name = "PCR_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getPcrId() {
		return this.pcrId;
	}

	public void setPcrId(long pcrId) {
		this.pcrId = pcrId;
	}

	@Column(name = "TREATY", nullable = false, length = 6)
	public String getTreaty() {
		return this.treaty;
	}

	public void setTreaty(String treaty) {
		this.treaty = treaty;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "TYPE", nullable = false, length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "REINSURER_CODE", length = 6)
	public String getReinsurerCode() {
		return this.reinsurerCode;
	}

	public void setReinsurerCode(String reinsurerCode) {
		this.reinsurerCode = reinsurerCode;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "REINSURER", nullable = false, length = 6)
	public String getReinsurer() {
		return this.reinsurer;
	}

	public void setReinsurer(String reinsurer) {
		this.reinsurer = reinsurer;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
