---------
--SCORE--
---------

--ALTER USER SCORE_Login WITH LOGIN = SCORE_Login;

update SCORE.dbo.CONTROLS set TEXT_DATA = REPLACE(TEXT_DATA,'PRD','${ExchangeEnv}') WHERE TEXT_DATA LIKE '%PRD%';
update SCORE.dbo.DOCS_DEFINITIONS set PATHNAME = REPLACE(PATHNAME, 'PRD','${ExchangeEnv}') WHERE PATHNAME LIKE '%PRD%';
update SCORE.dbo.DOC_REPORTS set PATHNAME = REPLACE(PATHNAME, 'PRD','${ExchangeEnv}') WHERE PATHNAME LIKE '%PRD%';

GO