package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lu.wealins.liability.services.core.utils.Historizable;

/**
 * PolicyEndorsementEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_ENDORSEMENTS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
@Historizable(id = "penId")
public class PolicyEndorsementEntity implements java.io.Serializable {

	private long penId;
	private String polId;
	private long pevId;
	private Integer endorsementNo;
	private Integer coverage;
	private String type;
	private String valueToken;
	private String valueBefore;
	private String valueAfter;
	private Date effectiveDate;
	private Integer status;
	private String createdProcess;
	private String createdBy;
	private Date createdDate;
	private Date createdSystemDate;
	private Date createdTime;

	@Id
	@Column(name = "PEN_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getPenId() {
		return this.penId;
	}

	public void setPenId(long penId) {
		this.penId = penId;
	}

	@Column(name = "FK_POLICIESPOL_ID")
	public String getPolId() {
		return this.polId;
	}

	public void setPolId(String polId) {
		this.polId = polId;
	}

	@Column(name = "FK_POLICY_EVENTPEV_ID")
	public long getPevId() {
		return this.pevId;
	}

	public void setPevId(long pevId) {
		this.pevId = pevId;
	}

	@Column(name = "ENDORSEMENT_NO")
	public Integer getEndorsementNo() {
		return this.endorsementNo;
	}

	public void setEndorsementNo(Integer endorsementNo) {
		this.endorsementNo = endorsementNo;
	}

	@Column(name = "COVERAGE")
	public Integer getCoverage() {
		return this.coverage;
	}

	public void setCoverage(Integer coverage) {
		this.coverage = coverage;
	}

	@Column(name = "TYPE", length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "VALUE_TOKEN", length = 12)
	public String getValueToken() {
		return this.valueToken;
	}

	public void setValueToken(String valueToken) {
		this.valueToken = valueToken;
	}

	@Column(name = "VALUE_BEFORE", length = 30)
	public String getValueBefore() {
		return this.valueBefore;
	}

	public void setValueBefore(String valueBefore) {
		this.valueBefore = valueBefore;
	}

	@Column(name = "VALUE_AFTER", length = 30)
	public String getValueAfter() {
		return this.valueAfter;
	}

	public void setValueAfter(String valueAfter) {
		this.valueAfter = valueAfter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_DATE", length = 23)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "CREATED_BY", length = 6)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
