package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AccountBalanceEntity generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_BALANCES")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class AccountBalanceEntity implements java.io.Serializable {

	private long abnId;
	@JsonIgnore
	private AccountCentreEntity accountCentre;
	@JsonIgnore
	private AccountEntity account;
	private String accountId;
	private String centre;
	private int company;
	private String branch;
	private String currency;
	private int financialYear;
	private BigDecimal openingBalance;
	private BigDecimal period1;
	private BigDecimal period2;
	private BigDecimal period3;
	private BigDecimal period4;
	private BigDecimal period5;
	private BigDecimal period6;
	private BigDecimal period7;
	private BigDecimal period8;
	private BigDecimal period9;
	private BigDecimal period10;
	private BigDecimal period11;
	private BigDecimal period12;
	private BigDecimal period13;
	private BigDecimal balance;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private Date createdSystemDate;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Date modifySystemDate;
	private Set<AccountTransactionEntity> accountTransactions = new HashSet<AccountTransactionEntity>(0);

	@Id
	@Column(name = "ABN_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getAbnId() {
		return this.abnId;
	}

	public void setAbnId(long abnId) {
		this.abnId = abnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_ACCOUNT_CENTACN_ID")
	@NotFound(action = NotFoundAction.IGNORE)
	public AccountCentreEntity getAccountCentre() {
		return this.accountCentre;
	}

	public void setAccountCentre(AccountCentreEntity accountCentre) {
		this.accountCentre = accountCentre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_ACCOUNTSACC_ID")
	@NotFound(action = NotFoundAction.IGNORE)
	public AccountEntity getAccount() {
		return this.account;
	}

	public void setAccount(AccountEntity account) {
		this.account = account;
	}

	@Column(name = "ACCOUNT", nullable = false, length = 12)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "CENTRE", nullable = false, length = 16)
	public String getCentre() {
		return this.centre;
	}

	public void setCentre(String centre) {
		this.centre = centre;
	}

	@Column(name = "COMPANY", nullable = false)
	public int getCompany() {
		return this.company;
	}

	public void setCompany(int company) {
		this.company = company;
	}

	@Column(name = "BRANCH", nullable = false, length = 6)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "CURRENCY", nullable = false, length = 4)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "FINANCIAL_YEAR", nullable = false)
	public int getFinancialYear() {
		return this.financialYear;
	}

	public void setFinancialYear(int financialYear) {
		this.financialYear = financialYear;
	}

	@Column(name = "OPENING_BALANCE", precision = 15)
	public BigDecimal getOpeningBalance() {
		return this.openingBalance;
	}

	public void setOpeningBalance(BigDecimal openingBalance) {
		this.openingBalance = openingBalance;
	}

	@Column(name = "PERIOD_1", precision = 15)
	public BigDecimal getPeriod1() {
		return this.period1;
	}

	public void setPeriod1(BigDecimal period1) {
		this.period1 = period1;
	}

	@Column(name = "PERIOD_2", precision = 15)
	public BigDecimal getPeriod2() {
		return this.period2;
	}

	public void setPeriod2(BigDecimal period2) {
		this.period2 = period2;
	}

	@Column(name = "PERIOD_3", precision = 15)
	public BigDecimal getPeriod3() {
		return this.period3;
	}

	public void setPeriod3(BigDecimal period3) {
		this.period3 = period3;
	}

	@Column(name = "PERIOD_4", precision = 15)
	public BigDecimal getPeriod4() {
		return this.period4;
	}

	public void setPeriod4(BigDecimal period4) {
		this.period4 = period4;
	}

	@Column(name = "PERIOD_5", precision = 15)
	public BigDecimal getPeriod5() {
		return this.period5;
	}

	public void setPeriod5(BigDecimal period5) {
		this.period5 = period5;
	}

	@Column(name = "PERIOD_6", precision = 15)
	public BigDecimal getPeriod6() {
		return this.period6;
	}

	public void setPeriod6(BigDecimal period6) {
		this.period6 = period6;
	}

	@Column(name = "PERIOD_7", precision = 15)
	public BigDecimal getPeriod7() {
		return this.period7;
	}

	public void setPeriod7(BigDecimal period7) {
		this.period7 = period7;
	}

	@Column(name = "PERIOD_8", precision = 15)
	public BigDecimal getPeriod8() {
		return this.period8;
	}

	public void setPeriod8(BigDecimal period8) {
		this.period8 = period8;
	}

	@Column(name = "PERIOD_9", precision = 15)
	public BigDecimal getPeriod9() {
		return this.period9;
	}

	public void setPeriod9(BigDecimal period9) {
		this.period9 = period9;
	}

	@Column(name = "PERIOD_10", precision = 15)
	public BigDecimal getPeriod10() {
		return this.period10;
	}

	public void setPeriod10(BigDecimal period10) {
		this.period10 = period10;
	}

	@Column(name = "PERIOD_11", precision = 15)
	public BigDecimal getPeriod11() {
		return this.period11;
	}

	public void setPeriod11(BigDecimal period11) {
		this.period11 = period11;
	}

	@Column(name = "PERIOD_12", precision = 15)
	public BigDecimal getPeriod12() {
		return this.period12;
	}

	public void setPeriod12(BigDecimal period12) {
		this.period12 = period12;
	}

	@Column(name = "PERIOD_13", precision = 15)
	public BigDecimal getPeriod13() {
		return this.period13;
	}

	public void setPeriod13(BigDecimal period13) {
		this.period13 = period13;
	}

	@Column(name = "BALANCE", precision = 15)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_SYSTEM_DATE", length = 23)
	public Date getModifySystemDate() {
		return this.modifySystemDate;
	}

	public void setModifySystemDate(Date modifySystemDate) {
		this.modifySystemDate = modifySystemDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountBalance")
	public Set<AccountTransactionEntity> getAccountTransactions() {
		return this.accountTransactions;
	}

	public void setAccountTransactions(Set<AccountTransactionEntity> accountTransactions) {
		this.accountTransactions = accountTransactions;
	}

}
