package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * MemberDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "MEMBER_DETAILS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class MemberDetailEntity implements java.io.Serializable {

	private String memId;
	@JsonIgnore
	private ClientEntity client;
	@JsonIgnore
	private GeneralNoteEntity generalNote;
	@JsonIgnore
	private PolicyEntity policy;
	private String certificateNo;
	private BigDecimal salary;
	private String category;
	private Date dateValidFrom;
	private Long clientNo;
	private String policyId;
	private String billDestinationRef;
	private String location;
	private Set<MemberHistoryDetailEntity> memberHistoryDetails = new HashSet<MemberHistoryDetailEntity>(0);

	@Id
	@Column(name = "MEM_ID", unique = true, nullable = false, length = 25)
	public String getMemId() {
		return this.memId;
	}

	public void setMemId(String memId) {
		this.memId = memId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLIENTSCLI_ID")
	public ClientEntity getClient() {
		return this.client;
	}

	public void setClient(ClientEntity client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_GENERAL_NOTEPON_ID")
	public GeneralNoteEntity getGeneralNote() {
		return this.generalNote;
	}

	public void setGeneralNote(GeneralNoteEntity generalNote) {
		this.generalNote = generalNote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@Column(name = "CERTIFICATE_NO", length = 10)
	public String getCertificateNo() {
		return this.certificateNo;
	}

	public void setCertificateNo(String certificateNo) {
		this.certificateNo = certificateNo;
	}

	@Column(name = "SALARY", precision = 14)
	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	@Column(name = "CATEGORY", length = 8)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_VALID_FROM", length = 23)
	public Date getDateValidFrom() {
		return this.dateValidFrom;
	}

	public void setDateValidFrom(Date dateValidFrom) {
		this.dateValidFrom = dateValidFrom;
	}

	@Column(name = "CLIENT_NO", precision = 10, scale = 0)
	public Long getClientNo() {
		return this.clientNo;
	}

	public void setClientNo(Long clientNo) {
		this.clientNo = clientNo;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Column(name = "BILL_DESTINATION_REF", length = 6)
	public String getBillDestinationRef() {
		return this.billDestinationRef;
	}

	public void setBillDestinationRef(String billDestinationRef) {
		this.billDestinationRef = billDestinationRef;
	}

	@Column(name = "LOCATION", length = 6)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberDetail")
	public Set<MemberHistoryDetailEntity> getMemberHistoryDetails() {
		return this.memberHistoryDetails;
	}

	public void setMemberHistoryDetails(Set<MemberHistoryDetailEntity> memberHistoryDetails) {
		this.memberHistoryDetails = memberHistoryDetails;
	}

}
