package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserEntity generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class UserEntity  implements java.io.Serializable {


     private String usrId;
     private UserGroupEntity userGroup;
     private String password;
     private String name;
	private int userGroupId;
     private int status;
     private Integer forcePasswordChange;
     private Integer multipleLogins;
     private Date datePasswordChanged;
     private String emailExtn;
     private String faxExtn;
     private Integer printing;
     private String terminalId;
     private int language0;
     private String telExtn;
     private String title;
     private String createdProcess;
     private String modifyProcess;
     private String createdBy;
     private Date createdDate;
     private Date createdTime;
     private String modifyBy;
     private Date modifyDate;
     private Date modifyTime;
     private Date lastLoginDate;
     private Date lastLoginTime;
     private Date lastLoginSdate;
     private String printer;
     private Set<UserActionEntity> userActions = new HashSet<UserActionEntity>(0);

     @Id 
    @Column(name="USR_ID", unique=true, nullable=false, length=5)
    public String getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_USER_GROUPSURG_ID")
    public UserGroupEntity getUserGroup() {
        return this.userGroup;
    }
    
    public void setUserGroup(UserGroupEntity userGroup) {
        this.userGroup = userGroup;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="NAME", nullable=false, length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="USER_GROUP", nullable=false)
	public int getUserGroupId() {
		return this.userGroupId;
    }
    
	public void setUserGroupId(int userGroupId) {
		this.userGroupId = userGroupId;
    }

    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="FORCE_PASSWORD_CHANGE")
    public Integer getForcePasswordChange() {
        return this.forcePasswordChange;
    }
    
    public void setForcePasswordChange(Integer forcePasswordChange) {
        this.forcePasswordChange = forcePasswordChange;
    }

    
    @Column(name="MULTIPLE_LOGINS")
    public Integer getMultipleLogins() {
        return this.multipleLogins;
    }
    
    public void setMultipleLogins(Integer multipleLogins) {
        this.multipleLogins = multipleLogins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_PASSWORD_CHANGED", length=23)
    public Date getDatePasswordChanged() {
        return this.datePasswordChanged;
    }
    
    public void setDatePasswordChanged(Date datePasswordChanged) {
        this.datePasswordChanged = datePasswordChanged;
    }

    
    @Column(name="EMAIL_EXTN", length=25)
    public String getEmailExtn() {
        return this.emailExtn;
    }
    
    public void setEmailExtn(String emailExtn) {
        this.emailExtn = emailExtn;
    }

    
    @Column(name="FAX_EXTN", length=20)
    public String getFaxExtn() {
        return this.faxExtn;
    }
    
    public void setFaxExtn(String faxExtn) {
        this.faxExtn = faxExtn;
    }

    
    @Column(name="PRINTING")
    public Integer getPrinting() {
        return this.printing;
    }
    
    public void setPrinting(Integer printing) {
        this.printing = printing;
    }

    
    @Column(name="TERMINAL_ID", length=30)
    public String getTerminalId() {
        return this.terminalId;
    }
    
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    
    @Column(name="LANGUAGE0", nullable=false)
    public int getLanguage0() {
        return this.language0;
    }
    
    public void setLanguage0(int language0) {
        this.language0 = language0;
    }

    
    @Column(name="TEL_EXTN", length=15)
    public String getTelExtn() {
        return this.telExtn;
    }
    
    public void setTelExtn(String telExtn) {
        this.telExtn = telExtn;
    }

    
    @Column(name="TITLE", length=30)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="CREATED_PROCESS", nullable=false, length=15)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }

    
    @Column(name="MODIFY_PROCESS", length=15)
    public String getModifyProcess() {
        return this.modifyProcess;
    }
    
    public void setModifyProcess(String modifyProcess) {
        this.modifyProcess = modifyProcess;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    
    @Column(name="MODIFY_BY", length=5)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGIN_DATE", length=23)
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGIN_TIME", length=23)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGIN_SDATE", length=23)
    public Date getLastLoginSdate() {
        return this.lastLoginSdate;
    }
    
    public void setLastLoginSdate(Date lastLoginSdate) {
        this.lastLoginSdate = lastLoginSdate;
    }

    
    @Column(name="PRINTER", length=8)
    public String getPrinter() {
        return this.printer;
    }
    
    public void setPrinter(String printer) {
        this.printer = printer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserActionEntity> getUserActions() {
        return this.userActions;
    }
    
    public void setUserActions(Set<UserActionEntity> userActions) {
        this.userActions = userActions;
    }




}


