package lu.wealins.common.dto.editing.services.enums;

public enum DocumentType {	
	AVIS_SITUATION("AVIS_SITUATION"), 
	MANAGEMENT_MANDATE("MANDATGESTION"), MANAGEMENT_MANDATE_END("MANDATGESTIONEND"),
	POLICY_SCHEDULE("POLICY_SCHEDULE"), 
	COMMISSIONS("COMMISSIONS"), 
	ACCEPTANCE_REPORT("ACCEPTANCE_REPORT"), 
	SURRENDER("SURRENDER"), 
	CHANGE_BENEF("CHANGE_BENEF"), 
	ADD_PREMIUM("ADD_PREMIUM"), 
	SOUSCRIPTION_FOLLOWUP("SOUSCRIPTION_FOLLOWUP"), 
	CHANGE_BROKER("CHANGE_BROKER"), 
	WITHDRAWAL("WITHDRAWAL"), 
	WITHDRAWAL_ACCOUNTING_NOTE("WITHDRAWAL_ACCOUNTING_NOTE"), 
	FAX_SECURITIES_TRANSFER("FAX_SECURITIES_TRANSFER"), 
	COMMISSION_PAYMENT_SLIP("COMMISSION_PAYMENT_SLIP"),
	FAX_PAYMENT("FAX_PAYMENT"), ANNEX_FISC("ANNEX_FISC"),
	SEPA_PAYMENT("SEPA_PAYMENT"), WITHDRAWAL_FOLLOWUP("WITHDRAWAL_FOLLOWUP"), TOTAL_SURRENDER("TOTAL_SURRENDER"),
	SWIFT_PAYMENT("SWIFT_PAYMENT"), FAX_SURRENDER_DEPOSIT_BANK("FAX_SURRENDER_DEPOSIT_BANK");

	private String val;

	private DocumentType(String val) {
		this.val = val;
	}

	public String val() {
		return this.val;
	}

	public static DocumentType fromString(String val) {
		if (val != null) {
			for (DocumentType b : values()) {
				if (val.equalsIgnoreCase(b.val)) {
					return b;
				}
			}
		}
		return null;
	}
}
