package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyCvgClaimEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_CVG_CLAIMS"

)
public class PolicyCvgClaimEntity implements java.io.Serializable {

	private String pccId;
	private Long client;
	private BigDecimal paymentValue;
	private BigDecimal unitValue;
	private BigDecimal paymentXrs;
	private BigDecimal adjustment1;
	private BigDecimal adjustment3;
	private BigDecimal adjustment2;
	private Integer adjType1;
	private Integer adjType3;
	private Integer adjType2;
	private int status;
	private String createdBy;
	private String createdProcess;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private String paymentCurrency;
	private String currency;
	private BigDecimal systemBenefit;
	private Integer event;
	private String policy;
	private Integer coverage;
	private Integer rejectionReason;
	private BigDecimal afUnitValue;
	private BigDecimal estimateValue;

	@Id
	@Column(name = "PCC_ID", unique = true, nullable = false, length = 20)
	public String getPccId() {
		return this.pccId;
	}

	public void setPccId(String pccId) {
		this.pccId = pccId;
	}

	@Column(name = "CLIENT", precision = 10, scale = 0)
	public Long getClient() {
		return this.client;
	}

	public void setClient(Long client) {
		this.client = client;
	}

	@Column(name = "PAYMENT_VALUE", precision = 15)
	public BigDecimal getPaymentValue() {
		return this.paymentValue;
	}

	public void setPaymentValue(BigDecimal paymentValue) {
		this.paymentValue = paymentValue;
	}

	@Column(name = "UNIT_VALUE", precision = 15)
	public BigDecimal getUnitValue() {
		return this.unitValue;
	}

	public void setUnitValue(BigDecimal unitValue) {
		this.unitValue = unitValue;
	}

	@Column(name = "PAYMENT_XRS", precision = 15, scale = 7)
	public BigDecimal getPaymentXrs() {
		return this.paymentXrs;
	}

	public void setPaymentXrs(BigDecimal paymentXrs) {
		this.paymentXrs = paymentXrs;
	}

	@Column(name = "ADJUSTMENT_1", precision = 15)
	public BigDecimal getAdjustment1() {
		return this.adjustment1;
	}

	public void setAdjustment1(BigDecimal adjustment1) {
		this.adjustment1 = adjustment1;
	}

	@Column(name = "ADJUSTMENT_3", precision = 15)
	public BigDecimal getAdjustment3() {
		return this.adjustment3;
	}

	public void setAdjustment3(BigDecimal adjustment3) {
		this.adjustment3 = adjustment3;
	}

	@Column(name = "ADJUSTMENT_2", precision = 15)
	public BigDecimal getAdjustment2() {
		return this.adjustment2;
	}

	public void setAdjustment2(BigDecimal adjustment2) {
		this.adjustment2 = adjustment2;
	}

	@Column(name = "ADJ_TYPE_1")
	public Integer getAdjType1() {
		return this.adjType1;
	}

	public void setAdjType1(Integer adjType1) {
		this.adjType1 = adjType1;
	}

	@Column(name = "ADJ_TYPE_3")
	public Integer getAdjType3() {
		return this.adjType3;
	}

	public void setAdjType3(Integer adjType3) {
		this.adjType3 = adjType3;
	}

	@Column(name = "ADJ_TYPE_2")
	public Integer getAdjType2() {
		return this.adjType2;
	}

	public void setAdjType2(Integer adjType2) {
		this.adjType2 = adjType2;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "PAYMENT_CURRENCY", length = 4)
	public String getPaymentCurrency() {
		return this.paymentCurrency;
	}

	public void setPaymentCurrency(String paymentCurrency) {
		this.paymentCurrency = paymentCurrency;
	}

	@Column(name = "CURRENCY", length = 4)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "SYSTEM_BENEFIT", precision = 15)
	public BigDecimal getSystemBenefit() {
		return this.systemBenefit;
	}

	public void setSystemBenefit(BigDecimal systemBenefit) {
		this.systemBenefit = systemBenefit;
	}

	@Column(name = "EVENT")
	public Integer getEvent() {
		return this.event;
	}

	public void setEvent(Integer event) {
		this.event = event;
	}

	@Column(name = "POLICY", length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "COVERAGE")
	public Integer getCoverage() {
		return this.coverage;
	}

	public void setCoverage(Integer coverage) {
		this.coverage = coverage;
	}

	@Column(name = "REJECTION_REASON")
	public Integer getRejectionReason() {
		return this.rejectionReason;
	}

	public void setRejectionReason(Integer rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	@Column(name = "AF_UNIT_VALUE", precision = 15)
	public BigDecimal getAfUnitValue() {
		return this.afUnitValue;
	}

	public void setAfUnitValue(BigDecimal afUnitValue) {
		this.afUnitValue = afUnitValue;
	}

	@Column(name = "ESTIMATE_VALUE", precision = 15)
	public BigDecimal getEstimateValue() {
		return this.estimateValue;
	}

	public void setEstimateValue(BigDecimal estimateValue) {
		this.estimateValue = estimateValue;
	}

}
