package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/** 
 * PolicyPremiumEntity generated by hbm2java
 */
@Entity
@Table(name="POLICY_PREMIUMS"
    
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler","createdProcess","modifyProcess","createdBy","createdDate","createdTime","modifyDate","modifyTime","modifyBy"})
public class PolicyPremiumEntity  implements java.io.Serializable {


     private String pcpId;
     @JsonIgnore
     private PolicyEntity policy;
     private Integer lapseWarning1;
     private Integer lapseWarning2;
     private Integer lapseWarning3;
	private String policyId;
     private Integer coverage;
     private BigDecimal modalPremium;
     private String currency;
     private Integer frequency;
     private Date dateNextBilledPremium;
     private Date dateNextPremiumDue;
     private Integer collectionMethodPremium1;
     private Integer collectionMethod;
     private Integer collectionSubMethod;
     private Long bankId;
     private Integer nextEscNumber;
     private BigDecimal contributionPercentage;
     private Date previousDatePaidTo;
     private int status;
     private BigDecimal totalPremium;
     private String createdBy;
     private Date createdDate;
     private Date createdTime;
     private String createdProcess;
     private String modifyBy;
     private Date modifyDate;
     private Date modifyTime;
     private String modifyProcess;
     private BigDecimal escPocAdjustment;
     private Integer disableEscalation;
     private String fundingPolicy;
     private Integer fundingCoverge;
     private BigDecimal netPremium;
     private BigDecimal modifiedPremium;
     @JsonIgnore
     private Set<PolicyPremiumChangeEntity> policyPremiumChanges = new HashSet<PolicyPremiumChangeEntity>(0);

     @Id 
    @Column(name="PCP_ID", unique=true, nullable=false, length=18)
    public String getPcpId() {
        return this.pcpId;
    }
    
    public void setPcpId(String pcpId) {
        this.pcpId = pcpId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_POLICIESPOL_ID")
    public PolicyEntity getPolicy() {
        return this.policy;
    }
    
    public void setPolicy(PolicyEntity policy) {
        this.policy = policy;
    }

    
    @Column(name="LAPSE_WARNING_1")
    public Integer getLapseWarning1() {
        return this.lapseWarning1;
    }
    
    public void setLapseWarning1(Integer lapseWarning1) {
        this.lapseWarning1 = lapseWarning1;
    }

    
    @Column(name="LAPSE_WARNING_2")
    public Integer getLapseWarning2() {
        return this.lapseWarning2;
    }
    
    public void setLapseWarning2(Integer lapseWarning2) {
        this.lapseWarning2 = lapseWarning2;
    }

    
    @Column(name="LAPSE_WARNING_3")
    public Integer getLapseWarning3() {
        return this.lapseWarning3;
    }
    
    public void setLapseWarning3(Integer lapseWarning3) {
        this.lapseWarning3 = lapseWarning3;
    }

    
    @Column(name="POLICY", nullable=false, length=14)
	public String getPolicyId() {
		return this.policyId;
    }
    
	public void setPolicyId(String policyId) {
		this.policyId = policyId;
    }

    
    @Column(name="COVERAGE")
    public Integer getCoverage() {
        return this.coverage;
    }
    
    public void setCoverage(Integer coverage) {
        this.coverage = coverage;
    }

    
    @Column(name="MODAL_PREMIUM", precision=15)
    public BigDecimal getModalPremium() {
        return this.modalPremium;
    }
    
    public void setModalPremium(BigDecimal modalPremium) {
        this.modalPremium = modalPremium;
    }

    
    @Column(name="CURRENCY", length=5)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="FREQUENCY")
    public Integer getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_NEXT_BILLED_PREMIUM", length=23)
    public Date getDateNextBilledPremium() {
        return this.dateNextBilledPremium;
    }
    
    public void setDateNextBilledPremium(Date dateNextBilledPremium) {
        this.dateNextBilledPremium = dateNextBilledPremium;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_NEXT_PREMIUM_DUE", length=23)
    public Date getDateNextPremiumDue() {
        return this.dateNextPremiumDue;
    }
    
    public void setDateNextPremiumDue(Date dateNextPremiumDue) {
        this.dateNextPremiumDue = dateNextPremiumDue;
    }

    
    @Column(name="COLLECTION_METHOD_PREMIUM_1")
    public Integer getCollectionMethodPremium1() {
        return this.collectionMethodPremium1;
    }
    
    public void setCollectionMethodPremium1(Integer collectionMethodPremium1) {
        this.collectionMethodPremium1 = collectionMethodPremium1;
    }

    
    @Column(name="COLLECTION_METHOD")
    public Integer getCollectionMethod() {
        return this.collectionMethod;
    }
    
    public void setCollectionMethod(Integer collectionMethod) {
        this.collectionMethod = collectionMethod;
    }

    
    @Column(name="COLLECTION_SUB_METHOD")
    public Integer getCollectionSubMethod() {
        return this.collectionSubMethod;
    }
    
    public void setCollectionSubMethod(Integer collectionSubMethod) {
        this.collectionSubMethod = collectionSubMethod;
    }

    
    @Column(name="BANK_ID", precision=12, scale=0)
    public Long getBankId() {
        return this.bankId;
    }
    
    public void setBankId(Long bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="NEXT_ESC_NUMBER")
    public Integer getNextEscNumber() {
        return this.nextEscNumber;
    }
    
    public void setNextEscNumber(Integer nextEscNumber) {
        this.nextEscNumber = nextEscNumber;
    }

    
    @Column(name="CONTRIBUTION_PERCENTAGE", precision=10, scale=6)
    public BigDecimal getContributionPercentage() {
        return this.contributionPercentage;
    }
    
    public void setContributionPercentage(BigDecimal contributionPercentage) {
        this.contributionPercentage = contributionPercentage;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PREVIOUS_DATE_PAID_TO", length=23)
    public Date getPreviousDatePaidTo() {
        return this.previousDatePaidTo;
    }
    
    public void setPreviousDatePaidTo(Date previousDatePaidTo) {
        this.previousDatePaidTo = previousDatePaidTo;
    }

    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="TOTAL_PREMIUM", precision=15)
    public BigDecimal getTotalPremium() {
        return this.totalPremium;
    }
    
    public void setTotalPremium(BigDecimal totalPremium) {
        this.totalPremium = totalPremium;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=5)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=23)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    
    @Column(name="CREATED_PROCESS", nullable=false, length=15)
    public String getCreatedProcess() {
        return this.createdProcess;
    }
    
    public void setCreatedProcess(String createdProcess) {
        this.createdProcess = createdProcess;
    }

    
    @Column(name="MODIFY_BY", length=5)
    public String getModifyBy() {
        return this.modifyBy;
    }
    
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_TIME", length=23)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    
    @Column(name="MODIFY_PROCESS", length=15)
    public String getModifyProcess() {
        return this.modifyProcess;
    }
    
    public void setModifyProcess(String modifyProcess) {
        this.modifyProcess = modifyProcess;
    }

    
    @Column(name="ESC_POC_ADJUSTMENT", precision=15)
    public BigDecimal getEscPocAdjustment() {
        return this.escPocAdjustment;
    }
    
    public void setEscPocAdjustment(BigDecimal escPocAdjustment) {
        this.escPocAdjustment = escPocAdjustment;
    }

    
    @Column(name="DISABLE_ESCALATION")
    public Integer getDisableEscalation() {
        return this.disableEscalation;
    }
    
    public void setDisableEscalation(Integer disableEscalation) {
        this.disableEscalation = disableEscalation;
    }

    
    @Column(name="FUNDING_POLICY", length=14)
    public String getFundingPolicy() {
        return this.fundingPolicy;
    }
    
    public void setFundingPolicy(String fundingPolicy) {
        this.fundingPolicy = fundingPolicy;
    }

    
    @Column(name="FUNDING_COVERGE")
    public Integer getFundingCoverge() {
        return this.fundingCoverge;
    }
    
    public void setFundingCoverge(Integer fundingCoverge) {
        this.fundingCoverge = fundingCoverge;
    }

    
    @Column(name="NET_PREMIUM", precision=15)
    public BigDecimal getNetPremium() {
        return this.netPremium;
    }
    
    public void setNetPremium(BigDecimal netPremium) {
        this.netPremium = netPremium;
    }

    
    @Column(name="MODIFIED_PREMIUM", precision=15)
    public BigDecimal getModifiedPremium() {
        return this.modifiedPremium;
    }
    
    public void setModifiedPremium(BigDecimal modifiedPremium) {
        this.modifiedPremium = modifiedPremium;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="policyPremium")
    public Set<PolicyPremiumChangeEntity> getPolicyPremiumChanges() {
        return this.policyPremiumChanges;
    }
    
    public void setPolicyPremiumChanges(Set<PolicyPremiumChangeEntity> policyPremiumChanges) {
        this.policyPremiumChanges = policyPremiumChanges;
    }




}


