update CHECK_STEP set is_mandatory = 1  where check_id in (44,87) and STEP_ID in (4,27,29);


insert into  CHECK_STEP  (CHECK_ID, STEP_ID, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, VISIBLEIF, METADATA)
  values ( 68, 13, 1,1,15, 0,13,NULL,NULL);

  insert into  CHECK_STEP  (CHECK_ID, STEP_ID, IS_UPDATABLE, IS_MANDATORY, CHECK_ORDER, IS_METADATA, LABEL_ID, VISIBLEIF, METADATA)
  values ( 75, 13, 1,1,16, 0,13,NULL,NULL);



