package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DocumentCorrespEntity generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT_CORRESP"

)
public class DocumentCorrespEntity implements java.io.Serializable {

	private DocumentCorrespEntityId id;
	private String type;
	private String fullPath;
	private String fileDesc;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dcpId", column = @Column(name = "DCP_ID", nullable = false, length = 15)),
			@AttributeOverride(name = "language", column = @Column(name = "LANGUAGE", nullable = false)) })
	public DocumentCorrespEntityId getId() {
		return this.id;
	}

	public void setId(DocumentCorrespEntityId id) {
		this.id = id;
	}

	@Column(name = "TYPE", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "FULL_PATH", length = 120)
	public String getFullPath() {
		return this.fullPath;
	}

	public void setFullPath(String fullPath) {
		this.fullPath = fullPath;
	}

	@Column(name = "FILE_DESC", length = 250)
	public String getFileDesc() {
		return this.fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}

}
