package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * DocumentRequestEntity generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT_REQUESTS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class DocumentRequestEntity implements java.io.Serializable {

	private long drqId;
	@JsonIgnore
	private ClientEntity client;
	@JsonIgnore
	private PolicyEntity policy;
	@JsonIgnore
	private TransactionEntity transaction;
	private String productLine;
	private String errorNo;
	private Integer coverage;
	private Long clientId;
	private String policyId;
	private Integer type;
	private String printedProcess;
	private String printedBy;
	private Date printedDate;
	private Date printedTime;
	private String transientData;
	private String event;
	private String document;
	private Date lastPrintedDate;
	private String lastPrintedBy;
	private String description;
	private String pathname;
	private Long transaction0;
	private String createdProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String printer;
	private Date effectiveDate;
	private Date docSignedDate;
	private Date docSentDate;

	@Id
	@Column(name = "DRQ_ID", unique = true, nullable = false, precision = 14, scale = 0)
	public long getDrqId() {
		return this.drqId;
	}

	public void setDrqId(long drqId) {
		this.drqId = drqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLIENTSCLI_ID")
	public ClientEntity getClient() {
		return this.client;
	}

	public void setClient(ClientEntity client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_TRANSACTIONSTRN_ID")
	public TransactionEntity getTransaction() {
		return this.transaction;
	}

	public void setTransaction(TransactionEntity transaction) {
		this.transaction = transaction;
	}

	@Column(name = "PRODUCT_LINE", length = 12)
	public String getProductLine() {
		return this.productLine;
	}

	public void setProductLine(String productLine) {
		this.productLine = productLine;
	}

	@Column(name = "ERROR_NO", length = 10)
	public String getErrorNo() {
		return this.errorNo;
	}

	public void setErrorNo(String errorNo) {
		this.errorNo = errorNo;
	}

	@Column(name = "COVERAGE")
	public Integer getCoverage() {
		return this.coverage;
	}

	public void setCoverage(Integer coverage) {
		this.coverage = coverage;
	}

	@Column(name = "CLIENT", precision = 12, scale = 0)
	public Long getClientId() {
		return this.clientId;
	}

	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	@Column(name = "POLICY", length = 20)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "PRINTED_PROCESS", length = 12)
	public String getPrintedProcess() {
		return this.printedProcess;
	}

	public void setPrintedProcess(String printedProcess) {
		this.printedProcess = printedProcess;
	}

	@Column(name = "PRINTED_BY", length = 5)
	public String getPrintedBy() {
		return this.printedBy;
	}

	public void setPrintedBy(String printedBy) {
		this.printedBy = printedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRINTED_DATE", length = 23)
	public Date getPrintedDate() {
		return this.printedDate;
	}

	public void setPrintedDate(Date printedDate) {
		this.printedDate = printedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRINTED_TIME", length = 23)
	public Date getPrintedTime() {
		return this.printedTime;
	}

	public void setPrintedTime(Date printedTime) {
		this.printedTime = printedTime;
	}

	@Column(name = "TRANSIENT_DATA", length = 200)
	public String getTransientData() {
		return this.transientData;
	}

	public void setTransientData(String transientData) {
		this.transientData = transientData;
	}

	@Column(name = "EVENT", length = 20)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "DOCUMENT", length = 14)
	public String getDocument() {
		return this.document;
	}

	public void setDocument(String document) {
		this.document = document;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_PRINTED_DATE", length = 23)
	public Date getLastPrintedDate() {
		return this.lastPrintedDate;
	}

	public void setLastPrintedDate(Date lastPrintedDate) {
		this.lastPrintedDate = lastPrintedDate;
	}

	@Column(name = "LAST_PRINTED_BY", length = 15)
	public String getLastPrintedBy() {
		return this.lastPrintedBy;
	}

	public void setLastPrintedBy(String lastPrintedBy) {
		this.lastPrintedBy = lastPrintedBy;
	}

	@Column(name = "DESCRIPTION", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PATHNAME", length = 100)
	public String getPathname() {
		return this.pathname;
	}

	public void setPathname(String pathname) {
		this.pathname = pathname;
	}

	@Column(name = "TRANSACTION0", precision = 15, scale = 0)
	public Long getTransaction0() {
		return this.transaction0;
	}

	public void setTransaction0(Long transaction0) {
		this.transaction0 = transaction0;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "PRINTER", length = 8)
	public String getPrinter() {
		return this.printer;
	}

	public void setPrinter(String printer) {
		this.printer = printer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_DATE", length = 23)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOC_SIGNED_DATE", length = 23)
	public Date getDocSignedDate() {
		return this.docSignedDate;
	}

	public void setDocSignedDate(Date docSignedDate) {
		this.docSignedDate = docSignedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOC_SENT_DATE", length = 23)
	public Date getDocSentDate() {
		return this.docSentDate;
	}

	public void setDocSentDate(Date docSentDate) {
		this.docSentDate = docSentDate;
	}

}
