package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lu.wealins.liability.services.core.utils.Historizable;

/**
 * ClientClaimsDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "CLIENT_CLAIMS_DETAILS"

)
@Historizable(id = "ccmId")
public class ClientClaimsDetailEntity implements java.io.Serializable {

	private int ccmId;
	private ClientEntity client;
	private Date dateOfPtd;
	private Date dateDeathNotified;
	private Date dateOfDeath;
	private String causeOfDeath;
	private Date deathCertificate;
	private Date ptdCertification;
	private Date datePtdNotified;
	private String causeOfPtd;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Date dateCiNotified;
	private Date dateOfCi;
	private Date ciCertification;
	private String causeOfCi;

	@Id
	@Column(name = "CCM_ID", unique = true, nullable = false)
	public int getCcmId() {
		return this.ccmId;
	}

	public void setCcmId(int ccmId) {
		this.ccmId = ccmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLIENTSCLI_ID")
	public ClientEntity getClient() {
		return this.client;
	}

	public void setClient(ClientEntity client) {
		this.client = client;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_PTD", length = 23)
	public Date getDateOfPtd() {
		return this.dateOfPtd;
	}

	public void setDateOfPtd(Date dateOfPtd) {
		this.dateOfPtd = dateOfPtd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_DEATH_NOTIFIED", length = 23)
	public Date getDateDeathNotified() {
		return this.dateDeathNotified;
	}

	public void setDateDeathNotified(Date dateDeathNotified) {
		this.dateDeathNotified = dateDeathNotified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_DEATH", length = 23)
	public Date getDateOfDeath() {
		return this.dateOfDeath;
	}

	public void setDateOfDeath(Date dateOfDeath) {
		this.dateOfDeath = dateOfDeath;
	}

	@Column(name = "CAUSE_OF_DEATH", length = 6)
	public String getCauseOfDeath() {
		return this.causeOfDeath;
	}

	public void setCauseOfDeath(String causeOfDeath) {
		this.causeOfDeath = causeOfDeath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEATH_CERTIFICATE", length = 23)
	public Date getDeathCertificate() {
		return this.deathCertificate;
	}

	public void setDeathCertificate(Date deathCertificate) {
		this.deathCertificate = deathCertificate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTD_CERTIFICATION", length = 23)
	public Date getPtdCertification() {
		return this.ptdCertification;
	}

	public void setPtdCertification(Date ptdCertification) {
		this.ptdCertification = ptdCertification;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PTD_NOTIFIED", length = 23)
	public Date getDatePtdNotified() {
		return this.datePtdNotified;
	}

	public void setDatePtdNotified(Date datePtdNotified) {
		this.datePtdNotified = datePtdNotified;
	}

	@Column(name = "CAUSE_OF_PTD", length = 6)
	public String getCauseOfPtd() {
		return this.causeOfPtd;
	}

	public void setCauseOfPtd(String causeOfPtd) {
		this.causeOfPtd = causeOfPtd;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CI_NOTIFIED", length = 23)
	public Date getDateCiNotified() {
		return this.dateCiNotified;
	}

	public void setDateCiNotified(Date dateCiNotified) {
		this.dateCiNotified = dateCiNotified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_CI", length = 23)
	public Date getDateOfCi() {
		return this.dateOfCi;
	}

	public void setDateOfCi(Date dateOfCi) {
		this.dateOfCi = dateOfCi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CI_CERTIFICATION", length = 23)
	public Date getCiCertification() {
		return this.ciCertification;
	}

	public void setCiCertification(Date ciCertification) {
		this.ciCertification = ciCertification;
	}

	@Column(name = "CAUSE_OF_CI", length = 8)
	public String getCauseOfCi() {
		return this.causeOfCi;
	}

	public void setCauseOfCi(String causeOfCi) {
		this.causeOfCi = causeOfCi;
	}

}
