
CREATE TABLE [dbo].[STATEMENTLANGUAGEDEFAULT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LANGUAGE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_STATEMENTLANGUAGEDEAFULT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


SET IDENTITY_INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ON 

GO
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (1, N'FR')
GO
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (2, N'IT')
GO
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (3, N'NL')
GO
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (4, N'EN')
GO
INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] ([ID], [LANGUAGE]) VALUES (5, N'DE')
GO
SET IDENTITY_INSERT [dbo].[STATEMENTLANGUAGEDEFAULT] OFF
GO




