UPDATE [dbo].[DRM_LISSIA_MAPPING]
SET DATA_OUT = '4'
WHERE DATA_IN = 'Multiline';

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]
(DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
VALUES ((SELECT MAX(DRM_LISSIA_MAPPING_ID)+1 FROM [dbo].[DRM_LISSIA_MAPPING]),'PAYMENT_METHOD','Fax','3',1);

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]
(DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
VALUES ((SELECT MAX(DRM_LISSIA_MAPPING_ID)+1 FROM [dbo].[DRM_LISSIA_MAPPING]),'PAYMENT_METHOD','Swift','5',1);

INSERT INTO [dbo].[DRM_LISSIA_MAPPING]
(DRM_LISSIA_MAPPING_ID,TYPE,DATA_IN,DATA_OUT,STATUS)
VALUES ((SELECT MAX(DRM_LISSIA_MAPPING_ID)+1 FROM [dbo].[DRM_LISSIA_MAPPING]),'PAYMENT_METHOD','Swift+Fax','6',1);

GO