package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyFundInstructionDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_FUND_INSTRUCTION_DETAIL"

)
public class PolicyFundInstructionDetailEntity implements java.io.Serializable {

	private long pidId;
	private PolicyFundInstructionEntity policyFundInstruction;
	private String toFund;
	private BigDecimal toFundPcg;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private String modifyProcess;
	private Integer overrideNavPriceBasis;

	@Id
	@Column(name = "PID_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getPidId() {
		return this.pidId;
	}

	public void setPidId(long pidId) {
		this.pidId = pidId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICY_FUND_PFI_ID")
	public PolicyFundInstructionEntity getPolicyFundInstruction() {
		return this.policyFundInstruction;
	}

	public void setPolicyFundInstruction(PolicyFundInstructionEntity policyFundInstruction) {
		this.policyFundInstruction = policyFundInstruction;
	}

	@Column(name = "TO_FUND", length = 8)
	public String getToFund() {
		return this.toFund;
	}

	public void setToFund(String toFund) {
		this.toFund = toFund;
	}

	@Column(name = "TO_FUND_PCG", precision = 10, scale = 6)
	public BigDecimal getToFundPcg() {
		return this.toFundPcg;
	}

	public void setToFundPcg(BigDecimal toFundPcg) {
		this.toFundPcg = toFundPcg;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "OVERRIDE_NAV_PRICE_BASIS", precision = 3, scale = 0)
	public Integer getOverrideNavPriceBasis() {
		return this.overrideNavPriceBasis;
	}

	public void setOverrideNavPriceBasis(Integer overrideNavPriceBasis) {
		this.overrideNavPriceBasis = overrideNavPriceBasis;
	}

}
