--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.4.270.0
-- Product Home Page: http://devart.com/dbforge/sql/studio
-- Script date 30/08/2017 13:05:08
-- Source server version: 12.00.2269
-- Source connection string: Data Source=elissia-sql,1433;Integrated Security=False;User ID=elissia-flywaydb
-- Target server version: 12.00.4213
-- Target connection string: Data Source=elissia-sql,1435;Integrated Security=False;User ID=elissia-flywaydb
-- Run this script against $[CLIENT_ENV]_COMMON to synchronize it with $[CLIENT_ENV]_COMMON
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

USE $[CLIENT_ENV]_COMMON
GO
IF DB_NAME() <> N'$[CLIENT_ENV]_COMMON' SET NOEXEC ON
GO


--
-- Set transaction isolation level
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

--
-- Start Transaction
--
BEGIN TRANSACTION

--
-- Inserting data into table dbo.SYSTEM_PROPERTIES
--
SET IDENTITY_INSERT dbo.SYSTEM_PROPERTIES ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT dbo.SYSTEM_PROPERTIES(ID, CATEGORY, PROPERTY_NAME, PROPERTY_VALUE, DESCRIPTION, STATUS, CREATED_BY, CREATED_DATE) VALUES (136694, N'system', N'date.store.format', N'MM.dd.yyyy', N'Luxembourg date format', 1, N'AAAAA', '2017-08-30 00:00:00.0000000')
GO
SET IDENTITY_INSERT dbo.SYSTEM_PROPERTIES OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on dbo.SYSTEM_PROPERTIES
--
DBCC CHECKIDENT('dbo.SYSTEM_PROPERTIES', RESEED, 136694)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END


--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO
