SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[INTERNATIONALIZATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[LANGUAGE] [char](2) NOT NULL,
	[SOURCE] [varchar](100) NULL,
	[DESTINATION] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO