
/****** Object:  Table [dbo].[PRODUCTSTATEMENTLOCK]    Script Date: 22/09/2017 10:28:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PRODUCTSTATEMENTLOCK](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PRODUCTCODE] [varchar](20) NOT NULL,
	[PRODUCTNAME] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

INSERT INTO [dbo].[PRODUCTSTATEMENTLOCK]
           ([PRODUCTCODE]
           ,[PRODUCTNAME])
     VALUES
           ('4D1'
           ,'4 Life Germany')
GO





