INSERT INTO [dbo].[INTERNATIONALIZATION] ([TYPE],[LANGUAGE],[SOURCE],[DESTINATION])
VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'OPERATIONSNUMBER', 'Nombre d’opérations'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'OPERATIONSNUMBER', 'Number of operations'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'SURRENDERSNUMBER', 'Nombre de rachats sur la période'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'SURRENDERSNUMBER', 'Number of surrenders over the period'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'FULLSURRENDERSNUMBER', 'Nombre de rachats totaux sur la période'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'FULLSURRENDERSNUMBER', 'Number of full surrenders over the period'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'BENEFITSPAIDSUM', 'Somme des prestations sur la période'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'BENEFITSPAIDSUM', 'Sum of benefits paid over the period'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'RETENTIONRATE', 'Taux de retention'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'RETENTIONRATE', 'Retention rate'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'BENEFITSADMINFEEAVERAGE', 'Frais de gestion moyen sur prestation'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'BENEFITSADMINFEEAVERAGE', 'Average benefits admin fee'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'fr' , 'OPENPOLICIESSUBSCRIBERNUMBER', 'Nombre de souscripteur sur polices ouvertes'),
('EXCEL_NEW_PRODUCTION_COLUMN_HEADER' , 'en' , 'OPENPOLICIESSUBSCRIBERNUMBER', 'Open policies subscriber');

UPDATE [dbo].[INTERNATIONALIZATION]
SET [SOURCE] = 'PRODUCTIONADMINFEEAVERAGE'
WHERE [SOURCE] = 'ADMINFEEAVERAGE';

UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Frais de gestion moyens sur production'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'PRODUCTIONADMINFEEAVERAGE';