INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','BROKER', 'Broker');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','PRODUCT', 'Produit');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','ENTERINGMOVEMENTSNUMBER', 'Polices ouvertes');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','NEWPOLICIESNUMBER', 'Nouvelles polices');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','PRIMESSUM', 'Somme des primes');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','PRIMEAVERAGE', 'Primes moyenne');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','ENTRYFEEAVERAGE', 'Frais d''entrée moyen');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','ADMINFEEAVERAGE', 'Frais de gestion moyen');


INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','BROKER', 'Broker');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','PRODUCT', 'Product');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','ENTERINGMOVEMENTSNUMBER', 'Open policies');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','NEWPOLICIESNUMBER', 'New policies');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','PRIMESSUM', 'Sum primes');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','PRIMEAVERAGE', 'Average primes');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','ENTRYFEEAVERAGE', 'Average entry fee');
INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','ADMINFEEAVERAGE', 'Average admin fee');