USE [EWEALINS_UAT]
GO
/****** Object:  Table [dbo].[GENERALMESSAGE]    Script Date: 23/08/2017 16:43:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENERALMESSAGE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERS_ID] [bigint] NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[CONTENT] [varchar](512) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[POLICY]    Script Date: 23/08/2017 16:43:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[POLICY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[POLICY_ID] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[POLICYCONSULTING]    Script Date: 23/08/2017 16:43:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POLICYCONSULTING](
	[POLICY_ID] [bigint] NOT NULL,
	[USERS_ID] [bigint] NOT NULL,
	[LAST_CONSULTED] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[POLICY_ID] ASC,
	[USERS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[POLICYMESSAGE]    Script Date: 23/08/2017 16:43:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POLICYMESSAGE](
	[GENERAL_MESSAGE_ID] [bigint] NOT NULL,
	[POLICY_ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GENERAL_MESSAGE_ID] ASC,
	[POLICY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[USERS]    Script Date: 23/08/2017 16:43:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGIN] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[GENERALMESSAGE]  WITH CHECK ADD FOREIGN KEY([USERS_ID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[POLICYCONSULTING]  WITH CHECK ADD FOREIGN KEY([POLICY_ID])
REFERENCES [dbo].[POLICY] ([ID])
GO
ALTER TABLE [dbo].[POLICYCONSULTING]  WITH CHECK ADD FOREIGN KEY([USERS_ID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[POLICYMESSAGE]  WITH CHECK ADD FOREIGN KEY([GENERAL_MESSAGE_ID])
REFERENCES [dbo].[GENERALMESSAGE] ([ID])
GO
ALTER TABLE [dbo].[POLICYMESSAGE]  WITH CHECK ADD FOREIGN KEY([POLICY_ID])
REFERENCES [dbo].[POLICY] ([ID])
GO
