CREATE TABLE CONFIGURATION(
	CONFIG_ID BigInt NOT NULL IDENTITY (1,1) ,	
	TARGET_CFG nvarchar(255) NOT NULL,
	NAME_CFG nvarchar(255) NOT NULL,
	TYPE_CFG nvarchar(255) NOT NULL,
	USERS_ID bigint NOT NULL ,
	
	VALUE1 text NULL,
	VALUE2 text NULL,
	VALUE3 text NULL,
	
	CREATED_DATE datetime,
	UPDATED_DATE datetime,
	CONSTRAINT PK_CONFIG_ID  PRIMARY KEY CLUSTERED 
	(
		CONFIG_ID ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],

	CONSTRAINT FK_USERS_CONFIG FOREIGN KEY (USERS_ID) REFERENCES USERS(ID),
	
	 
) ON [PRIMARY]