INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','fr','RESIDENCECOUNTRY', 'Pays de résidence');

INSERT INTO [dbo].[INTERNATIONALIZATION]([TYPE],[LANGUAGE],[SOURCE],[DESTINATION]) VALUES ('EXCEL_NEW_PRODUCTION_COLUMN_HEADER','en','RESIDENCECOUNTRY', 'Country of residence');