drop table EDITION_USER;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EDITION_USER](
	[EDITION_USER_ID] [varchar](15) NOT NULL,
	[FIRST_NAME] [varchar](150) NULL,
	[LAST_NAME] [varchar](150) NULL,
	[PHONE] [varchar](150) NULL,
	[EMAIL] [varchar](200) NULL,
PRIMARY KEY NONCLUSTERED 
(
	[EDITION_USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO

drop table EDITION_REQUEST;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EDITION_REQUEST](
	[EDITION_REQUEST_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATION_DT] [datetime] NOT NULL,
	[CREATION_USER] [varchar](15) NOT NULL,
	[PRODUCT_ID] [varchar](12) NULL,
	[POLICY_ID] [varchar](14) NULL,
	[FUND_ID] [varchar](14) NULL,
	[CLIENT_ID] [int] NULL,
	[AGENT_ID] [varchar](8) NULL,
	[TRANSACTION_ID] [int] NULL,
	[EVENT_DT] [date] NULL,
	[STATEMENT_ID] [int] NULL,
	[IS_SIGN_NEEDED] [bit] NULL,
	[OUTPUT_CHOICE_CD] [char](3) NULL,
	[INPUT_STREAM_PATH] [varchar](max) NULL,
	[OUTPUT_STREAM_PATH] [varchar](max) NULL,
	[GED_CLASS_CD] [varchar](50) NULL,
	[GED_DOC_ID] [varchar](150) NULL,
	[GED_VERSION_ID] [varchar](150) NULL,
	[STATUS_CD] [varchar](30) NOT NULL,
	[DOCUMENT_TYPE] [varchar](100) NOT NULL,
	[EVENT_DT_END] [date] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[EDITION_REQUEST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO