ALTER TABLE TRANSFERS ADD 
	WORKFLOW_ITEM_ID int,
	USER_CPS1 varchar(5),
	CPS1_DT datetime,
	USER_CPS2 varchar(5),
	CPS2_DT datetime,
	USER_COMPTA varchar(5),
	COMPTA_DT datetime,
	CREATION_USER varchar(5),
	UPDATE_USER	varchar(5),
	TRANSACTION_ID int,
	REJECT_COMMENT varchar(1000),
	EDITING_ID int,
	POLICY_ID varchar(20),
	POLICY_OUT varchar(20),
	FDS_ID varchar(20),
	TRANSFER_SECURITIES_COMMENT varchar(1000),
	UPDATE_DT datetime;
GO

ALTER TABLE TRANSFERS ALTER COLUMN TRANSFER_TYPE varchar(30);
GO

ALTER TABLE TRANSFERS ALTER COLUMN TRANSFER_CD varchar(30);
GO

sp_rename 'TRANSFERS.CREATIONDT', 'CREATION_DT', 'COLUMN';
GO

CREATE TABLE TRANSFER_SECURITIES(
TRANSFER_SECURITIES_ID INT IDENTITY(1,1) NOT NULL,
TRANSFER_ID int,
FUND_NAME varchar(35),
ISIN varchar(12),
UNITS DECIMAL(15,6),
CREATION_USER varchar(5) NOT NULL,
CREATION_DT	datetime NOT NULL,
UPDATE_USER	varchar(5),
UPDATE_DT datetime,
 CONSTRAINT [PK_TRANSFER_SECURITIES] PRIMARY KEY CLUSTERED 
(
	TRANSFER_SECURITIES_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE TRANSACTION_FORM(
FORM_ID INT IDENTITY(1,1) NOT NULL,
WORKFLOW_ITEM_ID int NOT NULL,
POLICY_ID varchar(14) NOT NULL,
FIRST_CPS_USER varchar(5),
SECOND_CPS_USER varchar(5),
STATUS_CD varchar(10) NOT NULL,
EFFECTIVE_DATE datetime,
TRANSACTION_TYPE char(3),
TRANSACTION_FEES NUMERIC(10,6),
BROKER_TRANSACTION_FEES NUMERIC(10,6),
AMOUNT MONEY,
CURRENCY char(3),
AMOUNT_TYPE varchar(5),
PAYMENT_TYPE varchar(30),
SPECIFIC_AMOUNT_BY_FUND char(1),
CREATION_USER varchar(5) NOT NULL,
CREATION_DT	datetime NOT NULL,
UPDATE_USER	varchar(5),
UPDATE_DT datetime,
 CONSTRAINT [PK_TRANSACTION_FORM] PRIMARY KEY CLUSTERED 
(
	FORM_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE FUND_TRANSACTION_FORM (

FUND_TRANSACTION_FORM_ID INT IDENTITY(1,1) NOT NULL,
TRANSACTION_ID int,
FUND_ID varchar(8) NOT NULL,
INPUT_TYPE varchar(15),
SPLIT numeric(10,6),
PERCENTAGE numeric(10,6),
AMOUNT MONEY,
CURRENCY char(3),
UNITS numeric(15,6),
VALUATION_AMT Money,
CLOSURE bit,
CREATION_USER varchar(5) NOT NULL,
CREATION_DT	datetime NOT NULL,
UPDATE_USER	varchar(5),
UPDATE_DT datetime,
 CONSTRAINT [PK_FUND_TRANSACTION_FORM] PRIMARY KEY CLUSTERED 
(
	FUND_TRANSACTION_FORM_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO