package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataChangeEntity generated by hbm2java
 */
@Entity
@Table(name = "DATA_CHANGES"

)
public class DataChangeEntity implements java.io.Serializable {

	private long logId;
	private Date dateBefore;
	private String entity;
	private String entityId;
	private String attribute;
	private String alphaBefore;
	private BigDecimal numberAfter;
	private BigDecimal numberBefore;
	private Date dateAfter;
	private String alphaAfter;
	private Integer type;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private Date createdSdate;

	@Id
	@Column(name = "LOG_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getLogId() {
		return this.logId;
	}

	public void setLogId(long logId) {
		this.logId = logId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_BEFORE", length = 23)
	public Date getDateBefore() {
		return this.dateBefore;
	}

	public void setDateBefore(Date dateBefore) {
		this.dateBefore = dateBefore;
	}

	@Column(name = "ENTITY", nullable = false, length = 3)
	public String get() {
		return this.entity;
	}

	public void set(String entity) {
		this.entity = entity;
	}

	@Column(name = "ENTITY_ID", nullable = false, length = 50)
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@Column(name = "ATTRIBUTE", nullable = false, length = 50)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "ALPHA_BEFORE", length = 50)
	public String getAlphaBefore() {
		return this.alphaBefore;
	}

	public void setAlphaBefore(String alphaBefore) {
		this.alphaBefore = alphaBefore;
	}

	@Column(name = "NUMBER_AFTER", precision = 18, scale = 8)
	public BigDecimal getNumberAfter() {
		return this.numberAfter;
	}

	public void setNumberAfter(BigDecimal numberAfter) {
		this.numberAfter = numberAfter;
	}

	@Column(name = "NUMBER_BEFORE", precision = 18, scale = 8)
	public BigDecimal getNumberBefore() {
		return this.numberBefore;
	}

	public void setNumberBefore(BigDecimal numberBefore) {
		this.numberBefore = numberBefore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_AFTER", length = 23)
	public Date getDateAfter() {
		return this.dateAfter;
	}

	public void setDateAfter(Date dateAfter) {
		this.dateAfter = dateAfter;
	}

	@Column(name = "ALPHA_AFTER", length = 50)
	public String getAlphaAfter() {
		return this.alphaAfter;
	}

	public void setAlphaAfter(String alphaAfter) {
		this.alphaAfter = alphaAfter;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SDATE", nullable = false, length = 23)
	public Date getCreatedSdate() {
		return this.createdSdate;
	}

	public void setCreatedSdate(Date createdSdate) {
		this.createdSdate = createdSdate;
	}

}
