package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PostingSetEntity generated by hbm2java
 */
@Entity
@Table(name = "POSTING_SETS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class PostingSetEntity implements java.io.Serializable {

	private long pstId;
	private int status;
	private Long nliQtano;
	private Date createdDate;
	private Date createdTime;
	private String createdProcess;
	private String createdBy;
	private Date createdSystemDate;
	private String closedBy;
	private Date closedDate;
	private Date closedTime;
	private String closedProcess;
	private Date closedSystemDate;
	private Integer sapStatus;
	private Integer comStatus;
	private Integer reportStatus;
	private Date sapExportDate;
	
	@JsonIgnore
	private Set<AccountTransactionEntity> accountTransactions = new HashSet<AccountTransactionEntity>(0);

	@Id
	@Column(name = "PST_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getPstId() {
		return this.pstId;
	}

	public void setPstId(long pstId) {
		this.pstId = pstId;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "NLI_QTANO", precision = 15, scale = 0)
	public Long getNliQtano() {
		return this.nliQtano;
	}

	public void setNliQtano(Long nliQtano) {
		this.nliQtano = nliQtano;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Column(name = "CLOSED_BY", length = 5)
	public String getClosedBy() {
		return this.closedBy;
	}

	public void setClosedBy(String closedBy) {
		this.closedBy = closedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CLOSED_DATE", length = 23)
	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CLOSED_TIME", length = 23)
	public Date getClosedTime() {
		return this.closedTime;
	}

	public void setClosedTime(Date closedTime) {
		this.closedTime = closedTime;
	}

	@Column(name = "CLOSED_PROCESS", length = 12)
	public String getClosedProcess() {
		return this.closedProcess;
	}

	public void setClosedProcess(String closedProcess) {
		this.closedProcess = closedProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CLOSED_SYSTEM_DATE", length = 23)
	public Date getClosedSystemDate() {
		return this.closedSystemDate;
	}

	public void setClosedSystemDate(Date closedSystemDate) {
		this.closedSystemDate = closedSystemDate;
	}

	@Column(name = "SAP_STATUS")
	public Integer getSapStatus() {
		return this.sapStatus;
	}

	public void setSapStatus(Integer sapStatus) {
		this.sapStatus = sapStatus;
	}
	
	@Column(name = "COM_STATUS")
	public Integer getComStatus() {
		return this.comStatus;
	}

	public void setComStatus(Integer comStatus) {
		this.comStatus = comStatus;
	}
	
	@Column(name = "REPORT_STATUS")
	public Integer getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(Integer reportStatus) {
		this.reportStatus = reportStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postingSet")
	public Set<AccountTransactionEntity> getAccountTransactions() {
		return this.accountTransactions;
	}

	public void setAccountTransactions(Set<AccountTransactionEntity> accountTransactions) {
		this.accountTransactions = accountTransactions;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAP_EXPORT_DATE", length = 23)
	public Date getSapExportDate() {
		return this.sapExportDate;
	}

	public void setSapExportDate(Date sapExportDate) {
		this.sapExportDate = sapExportDate;
	}

}
