INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('GENDER', '2', 'MALE', null)
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('GENDER', '3', 'FEMALE', null)
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('END_ON_INSURED_DEATH', '1', 'SINGLE', 'Single')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('END_ON_INSURED_DEATH', '2', 'JOINT_FIRST', 'Joint first death')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('END_ON_INSURED_DEATH', '3', 'JOINT_SECOND', 'Joint second death')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('END_ON_INSURED_DEATH', '4', 'MULTIPLE', 'Multiple')
GO
UPDATE [dbo].[TRANSCODIFICATION] SET [ODSCODE] = 3 WHERE [SCRIPTURACODE] = 'MME' AND [TYPE] = 'TITLE'
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('TITLE', 'PP1', 'MR', 'Lissia''s code for Mister for agent')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('TITLE', 'PP2', 'MME', 'Lissia''s code for Miss for agent')
GO
INSERT [dbo].[TRANSCODIFICATION] ( [TYPE], [ODSCODE], [SCRIPTURACODE], [DESCRIPTION]) VALUES ('LANGUAGE', 'NED', 'NL', 'Dutch')
GO