package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberHistoryDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "MEMBER_HISTORY_DETAILS"

)
public class MemberHistoryDetailEntity implements java.io.Serializable {

	private long mehId;
	private MemberDetailEntity memberDetail;
	private Date dateValidFrom;
	private String category;
	private Long salary;

	@Id
	@Column(name = "MEH_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getMehId() {
		return this.mehId;
	}

	public void setMehId(long mehId) {
		this.mehId = mehId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_MEMBER_DETAIMEM_ID")
	public MemberDetailEntity getMemberDetail() {
		return this.memberDetail;
	}

	public void setMemberDetail(MemberDetailEntity memberDetail) {
		this.memberDetail = memberDetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_VALID_FROM", length = 23)
	public Date getDateValidFrom() {
		return this.dateValidFrom;
	}

	public void setDateValidFrom(Date dateValidFrom) {
		this.dateValidFrom = dateValidFrom;
	}

	@Column(name = "CATEGORY", length = 8)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "SALARY", precision = 10, scale = 0)
	public Long getSalary() {
		return this.salary;
	}

	public void setSalary(Long salary) {
		this.salary = salary;
	}

}
