package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PolicyCommissionEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_COMMISSIONS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class PolicyCommissionEntity implements java.io.Serializable {

	private String pcmId;
	@JsonIgnore
	private PolicyEntity policy;
	private BigDecimal totalIceConsultant;
	private Date initialPeriodDate;
	private Integer iceCalculation;
	private BigDecimal totalIce;
	private BigDecimal commissionablePremium;
	private String currency;
	private int coverage;
	private String policyId;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	@JsonIgnore
	private Set<PolicyCommissionScheduleEntity> policyCommissionSchedules = new HashSet<PolicyCommissionScheduleEntity>(0);

	@Id
	@Column(name = "PCM_ID", unique = true, nullable = false, length = 20)
	public String getPcmId() {
		return this.pcmId;
	}

	public void setPcmId(String pcmId) {
		this.pcmId = pcmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICIESPOL_ID")
	public PolicyEntity getPolicy() {
		return this.policy;
	}

	public void setPolicy(PolicyEntity policy) {
		this.policy = policy;
	}

	@Column(name = "TOTAL_ICE_CONSULTANT", precision = 15)
	public BigDecimal getTotalIceConsultant() {
		return this.totalIceConsultant;
	}

	public void setTotalIceConsultant(BigDecimal totalIceConsultant) {
		this.totalIceConsultant = totalIceConsultant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INITIAL_PERIOD_DATE", length = 23)
	public Date getInitialPeriodDate() {
		return this.initialPeriodDate;
	}

	public void setInitialPeriodDate(Date initialPeriodDate) {
		this.initialPeriodDate = initialPeriodDate;
	}

	@Column(name = "ICE_CALCULATION")
	public Integer getIceCalculation() {
		return this.iceCalculation;
	}

	public void setIceCalculation(Integer iceCalculation) {
		this.iceCalculation = iceCalculation;
	}

	@Column(name = "TOTAL_ICE", precision = 15)
	public BigDecimal getTotalIce() {
		return this.totalIce;
	}

	public void setTotalIce(BigDecimal totalIce) {
		this.totalIce = totalIce;
	}

	@Column(name = "COMMISSIONABLE_PREMIUM", precision = 15)
	public BigDecimal getCommissionablePremium() {
		return this.commissionablePremium;
	}

	public void setCommissionablePremium(BigDecimal commissionablePremium) {
		this.commissionablePremium = commissionablePremium;
	}

	@Column(name = "CURRENCY", length = 5)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyCommission")
	public Set<PolicyCommissionScheduleEntity> getPolicyCommissionSchedules() {
		return this.policyCommissionSchedules;
	}

	public void setPolicyCommissionSchedules(Set<PolicyCommissionScheduleEntity> policyCommissionSchedules) {
		this.policyCommissionSchedules = policyCommissionSchedules;
	}

}
