package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InforceListingEntity generated by hbm2java
 */
@Entity
@Table(name = "INFORCE_LISTING"

)
public class InforceListingEntity implements java.io.Serializable {

	private long ilgId;
	private String policy;
	private int coverage;
	private BigDecimal valo;
	private BigDecimal sumAssured;
	private int lifeAss;
	private Date lifeAssBirthday;
	private int jointLifeAss;
	private Date jointLifeAssBirthday;

	@Id
	@Column(name = "ILG_ID", unique = true, nullable = false)
	public long getIlgId() {
		return this.ilgId;
	}

	public void setIlgId(long ilgId) {
		this.ilgId = ilgId;
	}

	@Column(name = "POLICY", nullable = false, length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "COVERAGE", nullable = false)
	public int getCoverage() {
		return this.coverage;
	}

	public void setCoverage(int coverage) {
		this.coverage = coverage;
	}

	@Column(name = "VALO", precision = 15)
	public BigDecimal getValo() {
		return this.valo;
	}

	public void setValo(BigDecimal valo) {
		this.valo = valo;
	}

	@Column(name = "SUM_ASSURED", precision = 15)
	public BigDecimal getSumAssured() {
		return this.sumAssured;
	}

	public void setSumAssured(BigDecimal sumAssured) {
		this.sumAssured = sumAssured;
	}

	@Column(name = "LIFE_ASS", nullable = false)
	public int getLifeAss() {
		return this.lifeAss;
	}

	public void setLifeAss(int lifeAss) {
		this.lifeAss = lifeAss;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LIFE_ASS_BIRTHDAY", length = 23)
	public Date getLifeAssBirthday() {
		return this.lifeAssBirthday;
	}

	public void setLifeAssBirthday(Date lifeAssBirthday) {
		this.lifeAssBirthday = lifeAssBirthday;
	}

	@Column(name = "JOINT_LIFE_ASS", nullable = false)
	public int getJointLifeAss() {
		return this.jointLifeAss;
	}

	public void setJointLifeAss(int jointLifeAss) {
		this.jointLifeAss = jointLifeAss;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOINT_LIFE_ASS_BIRTHDAY", length = 23)
	public Date getJointLifeAssBirthday() {
		return this.jointLifeAssBirthday;
	}

	public void setJointLifeAssBirthday(Date jointLifeAssBirthday) {
		this.jointLifeAssBirthday = jointLifeAssBirthday;
	}

}
