UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Intermédiaire'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'BROKER';
UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Intermediary'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'en'
AND SOURCE = 'BROKER';

UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Nombre de polices sur la période'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'ENTERINGMOVEMENTSNUMBER';
UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Number of policies over the period'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'en'
AND SOURCE = 'ENTERINGMOVEMENTSNUMBER';

UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Nombre de nouvelles polices sur la période'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'NEWPOLICIESNUMBER';
UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Number of new policies over the period'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'en'
AND SOURCE = 'NEWPOLICIESNUMBER';

UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Sommes des primes sur la période (EUR)'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'PRIMESSUM';
UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Sum of premium over the period (EUR)'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'en'
AND SOURCE = 'PRIMESSUM';

UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Primes moyenne (EUR)'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'PRIMEAVERAGE';
UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Average premium (EUR)'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'en'
AND SOURCE = 'PRIMEAVERAGE';

UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Frais d’entrée moyens'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'fr'
AND SOURCE = 'ENTRYFEEAVERAGE';
UPDATE [dbo].[INTERNATIONALIZATION]
SET DESTINATION = 'Average entry fees'
WHERE TYPE = 'EXCEL_NEW_PRODUCTION_COLUMN_HEADER'
AND LANGUAGE = 'en'
AND SOURCE = 'ENTRYFEEAVERAGE';