package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExchangeInfoEntityId generated by hbm2java
 */
@Embeddable
public class ExchangeInfoEntityId  implements java.io.Serializable {


     private String polId;
     private int cliId;
     private String agtId;

    public ExchangeInfoEntityId() {
    }

    public ExchangeInfoEntityId(String polId, int cliId, String agtId) {
       this.polId = polId;
       this.cliId = cliId;
       this.agtId = agtId;
    }
   


    @Column(name="POL_ID", nullable=false, length=14)
    public String getPolId() {
        return this.polId;
    }
    
    public void setPolId(String polId) {
        this.polId = polId;
    }


    @Column(name="CLI_ID", nullable=false)
    public int getCliId() {
        return this.cliId;
    }
    
    public void setCliId(int cliId) {
        this.cliId = cliId;
    }


    @Column(name="AGT_ID", nullable=false, length=8)
    public String getAgtId() {
        return this.agtId;
    }
    
    public void setAgtId(String agtId) {
        this.agtId = agtId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExchangeInfoEntityId) ) return false;
		 ExchangeInfoEntityId castOther = ( ExchangeInfoEntityId ) other; 
         
		 return ( (this.getPolId()==castOther.getPolId()) || ( this.getPolId()!=null && castOther.getPolId()!=null && this.getPolId().equals(castOther.getPolId()) ) )
 && (this.getCliId()==castOther.getCliId())
 && ( (this.getAgtId()==castOther.getAgtId()) || ( this.getAgtId()!=null && castOther.getAgtId()!=null && this.getAgtId().equals(castOther.getAgtId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolId() == null ? 0 : this.getPolId().hashCode() );
         result = 37 * result + this.getCliId();
         result = 37 * result + ( getAgtId() == null ? 0 : this.getAgtId().hashCode() );
         return result;
   }   


}


