DELETE from BENEF_CLAUSE_STD where PRODUCT_CD not like 'WEA%';

INSERT INTO  BENEF_CLAUSE_STD VALUES ('BDLL1','FRA','BDLL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BDLL2','FRA','BDLL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('FF1','FRA','FF',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('FF2','FRA','FF',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXG1','FRA','LUXG',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXG2','FRA','LUXG',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXS1','FRA','LUXS',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXS2','FRA','LUXS',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXSEL1','FRA','LUXSEL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXSEL2','FRA','LUXSEL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXSELFR1','FRA','LUXSELFR',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUXSELFR2','FRA','LUXSELFR',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LXSF08151','FRA','LXSF0815',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LXSF08152','FRA','LXSF0815',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LXSF10151','FRA','LXSF1015',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LXSF10152','FRA','LXSF1015',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OGFD1','FRA','OGFD',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OGFD2','FRA','OGFD',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('ORLF1','FRA','ORLF',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('ORLF2','FRA','ORLF',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');


INSERT INTO  BENEF_CLAUSE_STD VALUES ('BLS1','FRA','BLS',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BLS1','NED','BLS',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BLS2','FRA','BLS',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BLS2','NED','BLS',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BV1','FRA','BV',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BV1','NED','BV',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BV2','FRA','BV',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('BV2','NED','BV',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CAPL1','FRA','CAPL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CAPL1','NED','CAPL',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CAPL2','FRA','CAPL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CAPL2','NED','CAPL',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CLL1','FRA','CLL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CLL1','NED','CLL',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CLL2','FRA','CLL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CLL2','NED','CLL',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSLBE1','FRA','LSLBE',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSLBE1','NED','LSLBE',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSLBE2','FRA','LSLBE',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSLBE2','NED','LSLBE',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('MLL1','FRA','MLL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('MLL1','NED','MLL',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('MLL2','FRA','MLL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('MLL2','NED','MLL',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OMPB1','FRA','OMPB',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OMPB1','NED','OMPB',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OMPB2','FRA','OMPB',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OMPB2','NED','OMPB',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPL1','FRA','OPL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPL1','NED','OPL',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPL2','FRA','OPL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPL2','NED','OPL',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('ORL1','FRA','ORL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('ORL1','NED','ORL',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('ORL2','FRA','ORL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('ORL2','NED','ORL',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSEBE1','FRA','PRSEBE',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSEBE1','NED','PRSEBE',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSEBE2','FRA','PRSEBE',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSEBE2','NED','PRSEBE',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PSB08161','FRA','PSB0816',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PSB08161','NED','PSB0816',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PSB08162','FRA','PSB0816',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PSB08162','NED','PSB0816',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('SPPB1','FRA','SPPB',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('SPPB1','NED','SPPB',1,'het deel van de vooroverleden begunstigde komt toe aan de overlevende begunstigde(n) in verhouding met hun respectievelijk evenredig deel.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('SPPB2','FRA','SPPB',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('SPPB2','NED','SPPB',2,'het deel van de vooroverleden begunstigde komt in gelijke delen toe aan de kinderen van de vooroverleden begunstigde, bij ontstentenis in gelijke delen aan de wettelijke erfgenamen van deze laatste. ');

INSERT INTO  BENEF_CLAUSE_STD VALUES ('CAPREPLUS1','ENG','CAPREPLUS',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts to the heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('CAPREPLUS2','ENG','CAPREPLUS',2,'the deceased beneficiary’s share of the respective death or maturity benefit shall be redistributed among the remaining surviving beneficiaries in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUSESP1','ENG','LUSESP',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts to the heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUSESP2','ENG','LUSESP',2,'the deceased beneficiary’s share of the respective death or maturity benefit shall be redistributed among the remaining surviving beneficiaries in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OLS1','ENG','OLS',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts to the heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OLS2','ENG','OLS',2,'the deceased beneficiary’s share of the respective death or maturity benefit shall be redistributed among the remaining surviving beneficiaries in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OLSD1','ENG','OLSD',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts to the heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OLSD2','ENG','OLSD',2,'the deceased beneficiary’s share of the respective death or maturity benefit shall be redistributed among the remaining surviving beneficiaries in proportion to the original share allocated to them.');

INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPPS1','ENG','OPPS',1,'the deceased beneficiary’s share of the benefit reverts to the heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPPS2','ENG','OPPS',2,'the deceased beneficiary’s share of the respective death or maturity benefit will be redistributed among the remaining surviving beneficiaries of the benefit, in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPS1','ENG','PPS',1,'the deceased beneficiary’s share of the benefit reverts to the heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPS2','ENG','PPS',2,'the deceased beneficiary’s share of the respective death or maturity benefit will be redistributed among the remaining surviving beneficiaries of the benefit, in proportion to the original share allocated to them.');

INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSP08151','ENG','LSP0815',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSP08151','PRT','LSP0815',1,'a quota do respetivo benefício do beneficiário falecido reverte em partes iguais para os filhos deste e, na ausência de filhos, para os seus herdeiros legais.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSP08152','ENG','LSP0815',2,'the deceased beneficiary’s share of the respective death or maturity benefit will be redistributed among the remaining surviving beneficiaries of the benefit, in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LSP08152','PRT','LSP0815',2,'a percentagem do benefício respetivo do beneficiário falecido é redistribuída pelos restantes beneficiários sobreviventes designados proporcionalmente à percentagem inicial que lhes foi atribuída.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUSEPO1','ENG','LUSEPO',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUSEPO1','PRT','LUSEPO',1,'a quota do respetivo benefício do beneficiário falecido reverte em partes iguais para os filhos deste e, na ausência de filhos, para os seus herdeiros legais.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUSEPO2','ENG','LUSEPO',2,'the deceased beneficiary’s share of the respective death or maturity benefit will be redistributed among the remaining surviving beneficiaries of the benefit, in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('LUSEPO2','PRT','LUSEPO',2,'a percentagem do benefício respetivo do beneficiário falecido é redistribuída pelos restantes beneficiários sobreviventes designados proporcionalmente à percentagem inicial que lhes foi atribuída.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPORT1','PRT','OPORT',1,'a quota do respetivo benefício do beneficiário falecido reverte em partes iguais para os filhos deste e, na ausência de filhos, para os seus herdeiros legais.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPORT2','PRT','OPORT',2,'a percentagem do benefício respetivo do beneficiário falecido é redistribuída pelos restantes beneficiários sobreviventes designados proporcionalmente à percentagem inicial que lhes foi atribuída.');

INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPORT1','ENG','OPORT',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPORT2','ENG','OPORT',2,'the deceased beneficiary’s share of the respective death or maturity benefit will be redistributed among the remaining surviving beneficiaries of the benefit, in proportion to the original share allocated to them.');


INSERT INTO  BENEF_CLAUSE_STD VALUES ('OLUX1','FRA','OLUX',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OLUX2','FRA','OLUX',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPPL1','FRA','OPPL',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('OPPL2','FRA','OPPL',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSELUX1','FRA','PRSELUX',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSELUX2','FRA','PRSELUX',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSEIN1','FRA','PRSEIN',1,'la part du bénéficiaire prédécédé revient au(x) bénéficiaire(s) survivant(s) à proportion de leur quote-part respective.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PRSEIN2','FRA','PRSEIN',2,'la part du bénéficiaire prédécédé revient par parts égales aux enfants du bénéficiaire prédécédé, à défaut par parts égales aux héritiers légaux de ce dernier. ');

INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN1','ENG','PPN',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN1','NOR','PPN',1,'den avdøde begunstigedes respektive andel av dødsfallsytelsen eller forfallsytelsen deles likt mellom den avdøde begunstigedes barn, og, i fravær av barn, til den avdøde begunstigedes rettslige arvinger.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN2','ENG','PPN',2,'the deceased beneficiary’s share of the benefit shall be redistributed among the remaining surviving designated beneficiaries of the death benefit/maturity benefit, respectively, in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN2','NOR','PPN',2,'prosentandelen til den avdøde begunstigede omfordeles blant de gjenværende, gjenlevende begunstigede til henholdsvis dødsfallsytelsen/forfallsytelsen i forhold til den opprinnelige andelen tildelt tidligere.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN02161','ENG','PPN0216',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN02161','NOR','PPN0216',1,'den avdøde begunstigedes respektive andel av dødsfallsytelsen eller forfallsytelsen deles likt mellom den avdøde begunstigedes barn, og, i fravær av barn, til den avdøde begunstigedes rettslige arvinger.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN02162','ENG','PPN0216',2,'the deceased beneficiary’s share of the benefit shall be redistributed among the remaining surviving designated beneficiaries of the death benefit/maturity benefit, respectively, in proportion to the original share allocated to them.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('PPN02162','NOR','PPN0216',2,'prosentandelen til den avdøde begunstigede omfordeles blant de gjenværende, gjenlevende begunstigede til henholdsvis dødsfallsytelsen/forfallsytelsen i forhold til den opprinnelige andelen tildelt tidligere.');

INSERT INTO  BENEF_CLAUSE_STD VALUES ('DD1','ENG','DD',1,'the deceased beneficiary’s share of the respective death or maturity benefit reverts equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary.');
INSERT INTO  BENEF_CLAUSE_STD VALUES ('DD2','ENG','DD',2,'the deceased beneficiary’s share of the benefit shall be redistributed among the remaining surviving designated beneficiaries of the death benefit/maturity benefit, respectively, in proportion to the original share allocated to them.');

INSERT INTO BENEF_CLAUSE_STD VALUES ('LUSESP1','ESP','LUSESP',1,'la parte del beneficiario fallecido de la correspondiente prestación por fallecimiento o por supervivencia recae en los herederos del beneficiario fallecido');
INSERT INTO BENEF_CLAUSE_STD VALUES ('LUSESP2','ESP','LUSESP',2,'la parte del beneficiario fallecido de la correspondiente prestación por fallecimiento o supervivencia se repartirá entre los restantes beneficiarios supervivientes de forma proporcional a la parte original asignada a cada uno de ellos');

INSERT INTO BENEF_CLAUSE_STD VALUES ('SP01','ESP','WEALES',1,'la parte del beneficiario fallecido de la correspondiente prestación por fallecimiento o por supervivencia recae en los herederos del beneficiario fallecido');
INSERT INTO BENEF_CLAUSE_STD VALUES ('SP02','ESP','WEALES',2,'la parte del beneficiario fallecido de la correspondiente prestación por fallecimiento o supervivencia se repartirá entre los restantes beneficiarios supervivientes de forma proporcional a la parte original asignada a cada uno de ellos');


INSERT INTO BENEF_CLAUSE_STD VALUES ('PPF10151','ENG','PPF1015',1,'the deceased beneficiary’s share of the respective death or maturity benefit shall be distributed equally to the children of the deceased beneficiary, and, in the absence of children, to the legal heirs of the deceased beneficiary.');
INSERT INTO BENEF_CLAUSE_STD VALUES ('PPF10152','ENG','PPF1015',2,'the deceased beneficiary’s share of the respective death or maturity benefit shall be redistributed among the remaining surviving designated beneficiaries of the death benefit / maturity benefit, respectively, in proportion to the original share allocated to them.');