--USE LISSIA_${ExchangeEnv};
--ALTER USER Lissia_db_login WITH LOGIN = Lissia_db_login;
--ALTER USER lissia_odbc WITH LOGIN = lissia_odbc;

update CONTROLS set ALPHA_VALUE = REPLACE(ALPHA_VALUE,'PRD','${ExchangeEnv}') WHERE ALPHA_VALUE LIKE '%PRD%';
update DOCUMENT_DEFINITIONS set PATHNAME = REPLACE(PATHNAME, 'PRD','${ExchangeEnv}') WHERE PATHNAME LIKE '%PRD%';
update DOCUMENT_CORRESP set FULL_PATH = REPLACE(FULL_PATH, 'PRD','${ExchangeEnv}') WHERE FULL_PATH LIKE '%PRD%';
update DOCUMENT_REQUESTS set PATHNAME = REPLACE(PATHNAME, 'PRD','${ExchangeEnv}') WHERE PATHNAME LIKE '%PRD%';
update USERS set PASSWORD =  '^ALhZN&6' WHERE USR_ID = 'LISSI' and '${ExchangeEnv}' <> 'UAT';
update USERS set PASSWORD =  'x6U\g_"%' WHERE USR_ID = 'LISSI' and '${ExchangeEnv}' = 'UAT';

DELETE FROM dbo.CLIENTS_IWI WHERE '${ExchangeEnv}' <> 'PRD';

GO
update CONTROLS set ALPHA_VALUE = '${systemName}' where CTL_ID = 'SYSTEM_NAME'
go
GO 
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME like '%ADD_USER%')
    DROP PROCEDURE dbo.ADD_USER
GO
CREATE PROCEDURE dbo.ADD_USER @USR_ID varchar(10), @PASSWORD varchar(20), @NAME varchar(40)
AS
BEGIN
   IF NOT EXISTS (SELECT * FROM USERS where LOGIN_ID = @USR_ID)
	BEGIN

		INSERT INTO USERS (USR_ID, LOGIN_ID, PASSWORD, NAME, USER_GROUP, STATUS, MULTIPLE_LOGINS, EMAIL_EXTN, FAX_EXTN, PRINTING, TERMINAL_ID, LANGUAGE0, TEL_EXTN, TITLE, CREATED_PROCESS, CREATED_BY, CREATED_DATE, CREATED_TIME)
		VALUES (@USR_ID,@USR_ID,@PASSWORD,@NAME,1 , 1 ,0, '', '', 0, '*', 1, '', '', 'FLYWAY', @USR_ID, getdate(), getdate());
	END
END

go
EXEC dbo.ADD_USER @USR_ID = 'AMC', @PASSWORD='H6$?Ffqk', @NAME='Samuel Cop';
EXEC dbo.ADD_USER @USR_ID = 'AZZ', @PASSWORD='u-?@=\r', @NAME='Zakaria Aziouiz';
EXEC dbo.ADD_USER @USR_ID = 'LUR', @PASSWORD='tVd}cj{', @NAME='Jérémy Ludwig';
EXEC dbo.ADD_USER @USR_ID = 'API', @PASSWORD='Ih>0;m4!', @NAME='Pim Man';
EXEC dbo.ADD_USER @USR_ID = 'FEB', @PASSWORD='|.0OY<x', @NAME='Félix Bagosora';
GO