
ALTER TABLE  CLIENT_ENDORSEMENTS  
ADD	GDPR_STARTDATE                   Datetime         NULL,
	GDPR_ENDDATE			 Datetime	  NULL,
	EXCEPT_RISK			 Char(1)	  NULL,
	EXCEPT_ACTIVITY_RISK		 Char(1)          NULL

GO