
--106 commentaire de waiting dispatch 2

-- 126 de New
UPDATE CHECK_STEP set CHECK_ID = 126 WHERE STEP_ID = 3 and CHECK_ID = 106;

-- 127 de Analysis
UPDATE CHECK_STEP set CHECK_ID = 127 WHERE STEP_ID = 4 and CHECK_ID = 106;

-- 25 commentaire de Validate Analysis (7)
UPDATE CHECK_STEP set CHECK_ID = 25 WHERE STEP_ID = 7 and CHECK_ID = 106;

-- Account opening request
SET IDENTITY_INSERT CHECK_WORKFLOW ON;

INSERT INTO CHECK_WORKFLOW ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 129,CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--129
UPDATE CHECK_STEP set CHECK_ID = 129 WHERE STEP_ID = 13 and CHECK_ID = 106;

-- Waiting ..
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 130,CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--130
UPDATE CHECK_STEP set CHECK_ID = 130 WHERE STEP_ID = 14 and CHECK_ID = 106;


-- Premium Transfer Request
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 131,CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--131
UPDATE CHECK_STEP set CHECK_ID = 131 WHERE STEP_ID = 15 and CHECK_ID = 106;

-- Validate Input
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 133,CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--133
UPDATE CHECK_STEP set CHECK_ID = 133 WHERE STEP_ID = 16 and CHECK_ID = 106;

-- Awaiting Premium
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 134, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--134
UPDATE CHECK_STEP set CHECK_ID = 134 WHERE STEP_ID = 17 and CHECK_ID = 106;

-- Premium Input and Nav
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 135,CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--135
UPDATE CHECK_STEP set CHECK_ID = 135 WHERE STEP_ID = 20 and CHECK_ID = 106;

-- Validate Premium and Nav
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 136,CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--136
UPDATE CHECK_STEP set CHECK_ID = 136 WHERE STEP_ID = 21 and CHECK_ID = 106;


-- Check documentation
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 137, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--137
UPDATE CHECK_STEP set CHECK_ID = 137 WHERE STEP_ID = 24 and CHECK_ID = 106;

-- Sending
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 138, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--138
UPDATE CHECK_STEP set CHECK_ID = 138 WHERE STEP_ID = 27 and CHECK_ID = 106;

-- Follow-up
INSERT INTO CHECK_WORKFLOW  ([CHECK_ID], [CHECK_DESC]
           ,[CHECK_EXPLAIN]
           ,[CHECK_TYPE]
           ,[DEFAULTVALUE]
           ,[CHECKCODE]
           ,[COMMENTIF])
select 132, CHECK_DESC, CHECK_EXPLAIN, CHECK_TYPE, DEFAULTVALUE, CHECKCODE, COMMENTIF from CHECK_WORKFLOW where CHECK_DESC = 'Comment' and CHECK_ID = 106;

--132
UPDATE CHECK_STEP set CHECK_ID = 132 WHERE STEP_ID = 28 and CHECK_ID = 106;
-- 41 de 16 

UPDATE CHECK_WORKFLOW set CHECKCODE = 'GRP1' where CHECK_ID = 122;

SET IDENTITY_INSERT CHECK_WORKFLOW OFF;