package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExportDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "EXPORT_DETAILS"

)
public class ExportDetailEntity implements java.io.Serializable {

	private String exdId;
	private ExportDefinitionEntity exportDefinition;
	private String fieldname;
	private int length;
	private int justification;
	private Character packing;
	private int format;
	private int origin;
	private String originData;
	private String actualValue;
	private int status;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private String modifyBy;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyProcess;

	@Id
	@Column(name = "EXD_ID", unique = true, nullable = false, length = 10)
	public String getExdId() {
		return this.exdId;
	}

	public void setExdId(String exdId) {
		this.exdId = exdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_EXPORT_DEFINEXP_ID")
	public ExportDefinitionEntity getExportDefinition() {
		return this.exportDefinition;
	}

	public void setExportDefinition(ExportDefinitionEntity exportDefinition) {
		this.exportDefinition = exportDefinition;
	}

	@Column(name = "FIELDNAME", nullable = false, length = 30)
	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	@Column(name = "LENGTH", nullable = false)
	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	@Column(name = "JUSTIFICATION", nullable = false)
	public int getJustification() {
		return this.justification;
	}

	public void setJustification(int justification) {
		this.justification = justification;
	}

	@Column(name = "PACKING", length = 1)
	public Character getPacking() {
		return this.packing;
	}

	public void setPacking(Character packing) {
		this.packing = packing;
	}

	@Column(name = "FORMAT", nullable = false)
	public int getFormat() {
		return this.format;
	}

	public void setFormat(int format) {
		this.format = format;
	}

	@Column(name = "ORIGIN", nullable = false)
	public int getOrigin() {
		return this.origin;
	}

	public void setOrigin(int origin) {
		this.origin = origin;
	}

	@Column(name = "ORIGIN_DATA", length = 15)
	public String getOriginData() {
		return this.originData;
	}

	public void setOriginData(String originData) {
		this.originData = originData;
	}

	@Column(name = "ACTUAL_VALUE", length = 20)
	public String getActualValue() {
		return this.actualValue;
	}

	public void setActualValue(String actualValue) {
		this.actualValue = actualValue;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

}
