package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MailingEntity generated by hbm2java
 */
@Entity
@Table(name = "MAILING"

)
public class MailingEntity implements java.io.Serializable {

	private MailingEntityId id;
	private String polCategory;
	private String agentName;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "polId", column = @Column(name = "POL_ID", nullable = false, length = 15)),
			@AttributeOverride(name = "agtId", column = @Column(name = "AGT_ID", nullable = false, length = 10)) })
	public MailingEntityId getId() {
		return this.id;
	}

	public void setId(MailingEntityId id) {
		this.id = id;
	}

	@Column(name = "POL_CATEGORY", length = 10)
	public String getPolCategory() {
		return this.polCategory;
	}

	public void setPolCategory(String polCategory) {
		this.polCategory = polCategory;
	}

	@Column(name = "AGENT_NAME", length = 100)
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

}
