package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupPolicyEntity generated by hbm2java
 */
@Entity
@Table(name = "GROUP_POLICIES"

)
public class GroupPolicyEntity implements java.io.Serializable {

	private String polId;
	private String schemeName;
	private String network;
	private String managing;
	private Date initialMemberStatementDate;
	private Date initialSchemeStatementDate;
	private Integer memberStatementInterval;
	private Integer schemeStatementInterval;

	@Id
	@Column(name = "POL_ID", unique = true, nullable = false, length = 14)
	public String getPolId() {
		return this.polId;
	}

	public void setPolId(String polId) {
		this.polId = polId;
	}

	@Column(name = "SCHEME_NAME", length = 25)
	public String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	@Column(name = "NETWORK", length = 8)
	public String getNetwork() {
		return this.network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	@Column(name = "MANAGING_ENTITY", length = 8)
	public String getManaging() {
		return this.managing;
	}

	public void setManaging(String managing) {
		this.managing = managing;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INITIAL_MEMBER_STATEMENT_DATE", length = 23)
	public Date getInitialMemberStatementDate() {
		return this.initialMemberStatementDate;
	}

	public void setInitialMemberStatementDate(Date initialMemberStatementDate) {
		this.initialMemberStatementDate = initialMemberStatementDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INITIAL_SCHEME_STATEMENT_DATE", length = 23)
	public Date getInitialSchemeStatementDate() {
		return this.initialSchemeStatementDate;
	}

	public void setInitialSchemeStatementDate(Date initialSchemeStatementDate) {
		this.initialSchemeStatementDate = initialSchemeStatementDate;
	}

	@Column(name = "MEMBER_STATEMENT_INTERVAL")
	public Integer getMemberStatementInterval() {
		return this.memberStatementInterval;
	}

	public void setMemberStatementInterval(Integer memberStatementInterval) {
		this.memberStatementInterval = memberStatementInterval;
	}

	@Column(name = "SCHEME_STATEMENT_INTERVAL")
	public Integer getSchemeStatementInterval() {
		return this.schemeStatementInterval;
	}

	public void setSchemeStatementInterval(Integer schemeStatementInterval) {
		this.schemeStatementInterval = schemeStatementInterval;
	}

}
