package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ExchangeInfoEntity generated by hbm2java
 */
@Entity
@Table(name = "EXCHANGE_INFOS"

)
public class ExchangeInfoEntity implements java.io.Serializable {

	private ExchangeInfoEntityId id;
	private Serializable polCcy;
	private Serializable cliCtyId;
	private Serializable category;
	private Serializable agtName;
	private Serializable nif;
	private Serializable letterSent;
	private Serializable letterSigned;
	private Serializable letterScanned;
	private Serializable letterFilled;
	private Serializable mailReturned;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "polId", column = @Column(name = "POL_ID", nullable = false, length = 14)),
			@AttributeOverride(name = "cliId", column = @Column(name = "CLI_ID", nullable = false)),
			@AttributeOverride(name = "agtId", column = @Column(name = "AGT_ID", nullable = false, length = 8)) })
	public ExchangeInfoEntityId getId() {
		return this.id;
	}

	public void setId(ExchangeInfoEntityId id) {
		this.id = id;
	}

	@Column(name = "POL_CCY")
	public Serializable getPolCcy() {
		return this.polCcy;
	}

	public void setPolCcy(Serializable polCcy) {
		this.polCcy = polCcy;
	}

	@Column(name = "CLI_CTY_ID")
	public Serializable getCliCtyId() {
		return this.cliCtyId;
	}

	public void setCliCtyId(Serializable cliCtyId) {
		this.cliCtyId = cliCtyId;
	}

	@Column(name = "CATEGORY")
	public Serializable getCategory() {
		return this.category;
	}

	public void setCategory(Serializable category) {
		this.category = category;
	}

	@Column(name = "AGT_NAME")
	public Serializable getAgtName() {
		return this.agtName;
	}

	public void setAgtName(Serializable agtName) {
		this.agtName = agtName;
	}

	@Column(name = "NIF")
	public Serializable getNif() {
		return this.nif;
	}

	public void setNif(Serializable nif) {
		this.nif = nif;
	}

	@Column(name = "LETTER_SENT")
	public Serializable getLetterSent() {
		return this.letterSent;
	}

	public void setLetterSent(Serializable letterSent) {
		this.letterSent = letterSent;
	}

	@Column(name = "LETTER_SIGNED")
	public Serializable getLetterSigned() {
		return this.letterSigned;
	}

	public void setLetterSigned(Serializable letterSigned) {
		this.letterSigned = letterSigned;
	}

	@Column(name = "LETTER_SCANNED")
	public Serializable getLetterScanned() {
		return this.letterScanned;
	}

	public void setLetterScanned(Serializable letterScanned) {
		this.letterScanned = letterScanned;
	}

	@Column(name = "LETTER_FILLED")
	public Serializable getLetterFilled() {
		return this.letterFilled;
	}

	public void setLetterFilled(Serializable letterFilled) {
		this.letterFilled = letterFilled;
	}

	@Column(name = "MAIL_RETURNED")
	public Serializable getMailReturned() {
		return this.mailReturned;
	}

	public void setMailReturned(Serializable mailReturned) {
		this.mailReturned = mailReturned;
	}

}
