BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U62')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('SLI', 1, 'U62', 1);
	END
END
GO

BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U63')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('JOD', 1, 'U63', 1);
	END
END
GO

BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U64')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('KRI', 1, 'U64', 1);
	END
END
GO

BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U65')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('DJO', 1, 'U65', 1);
	END
END
GO

BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U66')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('EMF', 1, 'U66', 1);
	END
END
GO

BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U76')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('LHS', 1, 'U76', 1);
	END
END
GO

BEGIN
	IF NOT EXISTS (SELECT * FROM WORKFLOW_QUEUE WHERE FK_USERSUSR_ID = 'U83')
	BEGIN
		INSERT INTO WORKFLOW_QUEUE (NAME0, TYPE0, FK_USERSUSR_ID, STATUS) VALUES ('SKL', 1, 'U83', 1);
	END
END
GO