package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyRequirementActionEntity generated by hbm2java
 */
@Entity
@Table(name = "POLICY_REQUIREMENT_ACTIONS"

)
public class PolicyRequirementActionEntity implements java.io.Serializable {

	private long praId;
	private PolicyRequirementEntity policyRequirement;
	private String userActionCode;
	private String notes;
	private Integer systemAction;
	private Date followUpDate;
	private int status;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private Date createdSystemDate;

	@Id
	@Column(name = "PRA_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getPraId() {
		return this.praId;
	}

	public void setPraId(long praId) {
		this.praId = praId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_POLICY_REQUIPRQ_ID")
	public PolicyRequirementEntity getPolicyRequirement() {
		return this.policyRequirement;
	}

	public void setPolicyRequirement(PolicyRequirementEntity policyRequirement) {
		this.policyRequirement = policyRequirement;
	}

	@Column(name = "USER_ACTION_CODE", length = 6)
	public String getUserActionCode() {
		return this.userActionCode;
	}

	public void setUserActionCode(String userActionCode) {
		this.userActionCode = userActionCode;
	}

	@Column(name = "NOTES", length = 100)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "SYSTEM_ACTION")
	public Integer getSystemAction() {
		return this.systemAction;
	}

	public void setSystemAction(Integer systemAction) {
		this.systemAction = systemAction;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FOLLOW_UP_DATE", length = 23)
	public Date getFollowUpDate() {
		return this.followUpDate;
	}

	public void setFollowUpDate(Date followUpDate) {
		this.followUpDate = followUpDate;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", nullable = false, length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

}
