---------
--CVSA--
---------
--USE CVSA;

--ALTER USER CVSA_Login WITH LOGIN = CVSA_Login;

update dbo.CONTROLS set TEXT_DATA = REPLACE(TEXT_DATA,'PRD','${ExchangeEnv}') WHERE TEXT_DATA LIKE '%PRD%';
update dbo.DOCS_DEFINITIONS set TEMPLATE = REPLACE(TEMPLATE, 'PRD','${ExchangeEnv}') WHERE TEMPLATE LIKE '%PRD%';
update dbo.DOCS_DEFINITIONS set DESTINATION_PATH = REPLACE(DESTINATION_PATH, 'PRD','${ExchangeEnv}') WHERE DESTINATION_PATH LIKE '%PRD%';
update dbo.DOCS_REPORTS set PATHNAME = REPLACE(PATHNAME, 'PRD','${ExchangeEnv}') WHERE PATHNAME LIKE '%PRD%';

GO