package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AgentHierarchyEntity generated by hbm2java
 */
@Entity
@Table(name = "AGENT_HIERARCHIES"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class AgentHierarchyEntity implements java.io.Serializable {

	private static final long serialVersionUID = 6930007881924772768L;
	private long aghId;
	@JsonIgnore
	private AgentEntity masterBroker;
	private AgentEntity agent;
	private Integer rateOrigin;
	private Integer rateApplication;
	private String writingAgent;
	private Integer type;
	private BigDecimal rate;
	private Date startDate;
	private Date endDate;
	private Integer status;
	private String createdBy;
	private Date createdTime;
	private Date createdDate;
	private String createdProcess;
	private String modifyBy;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyProcess;
	
	@Id
	@Column(name = "AGH_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getAghId() {
		return this.aghId;
	}

	public void setAghId(long aghId) {
		this.aghId = aghId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENT_ID")
	@NotFound(action = NotFoundAction.IGNORE)
	public AgentEntity getMasterBroker() {
		return this.masterBroker;
	}

	public void setMasterBroker(AgentEntity masterBroker) {
		this.masterBroker = masterBroker;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_AGENTSAGT_ID")
	@OrderBy("name")
	public AgentEntity getAgent() {
		return this.agent;
	}

	public void setAgent(AgentEntity agentOwner) {
		this.agent = agentOwner;
	}

	@Column(name = "RATE_ORIGIN")
	public Integer getRateOrigin() {
		return this.rateOrigin;
	}

	public void setRateOrigin(Integer rateOrigin) {
		this.rateOrigin = rateOrigin;
	}

	@Column(name = "RATE_APPLICATION")
	public Integer getRateApplication() {
		return this.rateApplication;
	}

	public void setRateApplication(Integer rateApplication) {
		this.rateApplication = rateApplication;
	}

	@Column(name = "WRITING_AGENT", length = 8)
	public String getWritingAgent() {
		return this.writingAgent;
	}

	public void setWritingAgent(String writingAgent) {
		this.writingAgent = writingAgent;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "RATE", precision = 12, scale = 7)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_PROCESS", length = 15)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_PROCESS", length = 15)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

}
