package lu.wealins.liability.services.core.persistence.entity;
// Generated Dec 1, 2016 12:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * OrderEntity generated by hbm2java
 */
@Entity
@Table(name = "ORDERS"

)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "createdProcess", "modifyProcess", "createdBy", "createdDate", "createdTime", "modifyDate", "modifyTime", "modifyBy" })
public class OrderEntity implements java.io.Serializable {

	private long ordId;
	private Date modifySystemDate;
	private Date createdSystemDate;
	private Integer type;
	private String modifyProcess;
	private Date modifyTime;
	private Date modifyDate;
	private String modifyBy;
	private String createdProcess;
	private Date createdTime;
	private Date createdDate;
	private String createdBy;
	private String contractRef;
	private String fund;
	private Date settledDate;
	private Date orderDate;
	private BigDecimal value0;
	private BigDecimal price;
	private BigDecimal units;
	private int status;
	private Integer faxNumber;
	@JsonIgnore
	private Set<TransactionEntity> transactions = new HashSet<TransactionEntity>(0);
	@JsonIgnore
	private Set<FundEntity> funds = new HashSet<FundEntity>(0);

	@Id
	@Column(name = "ORD_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getOrdId() {
		return this.ordId;
	}

	public void setOrdId(long ordId) {
		this.ordId = ordId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_SYSTEM_DATE", length = 23)
	public Date getModifySystemDate() {
		return this.modifySystemDate;
	}

	public void setModifySystemDate(Date modifySystemDate) {
		this.modifySystemDate = modifySystemDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_SYSTEM_DATE", length = 23)
	public Date getCreatedSystemDate() {
		return this.createdSystemDate;
	}

	public void setCreatedSystemDate(Date createdSystemDate) {
		this.createdSystemDate = createdSystemDate;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "CREATED_PROCESS", nullable = false, length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", nullable = false, length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CONTRACT_REF", length = 12)
	public String getContractRef() {
		return this.contractRef;
	}

	public void setContractRef(String contractRef) {
		this.contractRef = contractRef;
	}

	@Column(name = "FUND", nullable = false, length = 8)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SETTLED_DATE", length = 23)
	public Date getSettledDate() {
		return this.settledDate;
	}

	public void setSettledDate(Date settledDate) {
		this.settledDate = settledDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_DATE", length = 23)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "VALUE0", precision = 15)
	public BigDecimal getValue0() {
		return this.value0;
	}

	public void setValue0(BigDecimal value0) {
		this.value0 = value0;
	}

	@Column(name = "PRICE", precision = 15, scale = 6)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "UNITS", precision = 15, scale = 6)
	public BigDecimal getUnits() {
		return this.units;
	}

	public void setUnits(BigDecimal units) {
		this.units = units;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "FAX_NUMBER")
	public Integer getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(Integer faxNumber) {
		this.faxNumber = faxNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<TransactionEntity> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<TransactionEntity> transactions) {
		this.transactions = transactions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "HAS", joinColumns = {
			@JoinColumn(name = "FK_ORDERSORD_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "FK_FUNDSFDS_ID", nullable = false, updatable = false) })
	public Set<FundEntity> getFunds() {
		return this.funds;
	}

	public void setFunds(Set<FundEntity> funds) {
		this.funds = funds;
	}

}
