  ALTER TABLE CLIENTS ALTER COLUMN EMAIL char(100) NULL
  GO
  
  ALTER TABLE CLIENT_CONTACT_DETAILS ALTER COLUMN EMAIL char(100) NULL 
  GO
  ALTER TABLE CLIENT_ENDORSEMENTS ALTER COLUMN EMAIL char(100) NULL
  GO
  ALTER TABLE AGENTS ALTER COLUMN EMAIL char(100) NULL
  GO
  ALTER TABLE POSTING_SETS ALTER COLUMN SAP_STATUS smallint null
  GO
  