
CREATE TABLE [dbo].[TRANSACTION_TAX](
	[TRN_TAX_ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[ORIGIN] [varchar](10) NULL,
	[POLICY] [varchar](16) NULL,
	[CURRENCY] [varchar](3) NULL,
	[TAX_COUNTRY] [varchar](3) NULL,
	[POLICY_EFFECT_DATE] [date] NULL,
	[TRN_DATE] [date] NULL,
	[TRN_TYPE] [varchar](5) NULL,
	[PREV_TRN_TAX_ID] [int] NULL,
	[POLICY_VALUE] [decimal](15, 2) NULL,
	[TRN_NET_AMT] [decimal](15, 2) NULL,
	[STATUS] [int] NULL,
	[CREATION_DT] [datetime] NULL,
	[CREATION_USER] [varchar](100) NULL,
	[UPDATE_DT] [datetime] NULL,
	[UPDATE_USER] [varchar](100) NULL,
	[ORIGIN_ID] [decimal](14, 0) NULL
	)



CREATE TABLE TRANSACTION_TAX_DETAILS (
    TRN_TAX_DETAIL_ID int IDENTITY(1,1) PRIMARY KEY,
    TRN_TAX_ID int FOREIGN KEY REFERENCES TRANSACTION_TAX(TRN_TAX_ID),
    PREMIUM_DATE DATE,
    PREMIUM_VALUE_BEFORE DECIMAL(15,2),
    PREMIUM_VALUE_AFTER DECIMAL(15,2),
	SPLIT_PERCENT DECIMAL(5,2),
	CAPITAL_GAIN_AMT DECIMAL(15,2),
	CREATION_DT DATETIME,
	CREATION_USER VARCHAR(100),
	UPDATE_DT DATETIME,
	UPDATE_USER VARCHAR(100)
);

